### ISSUE TITLE
При выделении точечных сущностей не учитывается значение angle

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#10]
Если в энтити присутствует параметр angles(string), то при выделении энтити отображается заданное при помощи angles положение. Однако, если вместо angles(string) использован параметр angle(integer), т. е. только значение yaw, то он не учитывается, и энтити сохраняет положение по умолчанию.

Также, если это возможно, было бы неплохо, если бы положение точечных энтити автоматически отображалось с учётом angle/angles, без необходимости выделять объект.

**Comment by UnrealKaraulov** [comment]
должно быть автоматически видимо я что-то недоделал, если не забуду то исправлю

**Comment by UnrealKaraulov** [comment]
только заметил issue ) на почту не захожу а на гитхабе никаких уведомлений не бывает я так понял

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Вероятно, нужно "пинговать" никнейм, чтобы уведомление появилось. Ну, либо использовать опцию All activity/Custom в Watch для получения уведомлений.

**Comment by UnrealKaraulov** [comment]
> @UnrealKaraulov Вероятно, нужно "пинговать" никнейм, чтобы уведомление появилось. Ну, либо использовать опцию All activity/Custom в Watch для получения уведомлений.

какая entity использует Angle вместо Angles?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Ну, вообще, angle - это упрощённый вариант angles, вероятно, изначальный. Действует для любых энтити, по сути, которым может быть задано какое-либо вращение при помощи angles. Просто зачастую некоторым энтити даже нет необходимости задавать другое изменение углов, кроме как поворот вокруг вертикальной оси. И на оригинальных картах Valve/Gearbox повсеместно используется angle вместо angles.

**Comment by UnrealKaraulov** [comment]
я просто не могу найти в исходниках где оно используется, по идее нигде

**Comment by UnrealKaraulov** [comment]
в regamedll смотрел этот параметр совсем не используется судя по всему

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D есть уверенность в том что этот параметр используется гдето кроме точечных entity?

**Comment by UnrealKaraulov** [comment]
ну или я не так понял можно какой-нибудь пример или скрин

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov :
{
"wad" "\quiver\valve\halflife.wad;\quiver\valve\decals.wad;\quiver\valve\xeno.wad;\quiver\valve\sample.wad"
"gametitle" "1"
"startdark" "1"
"MaxRange" "6300"
"message" "Black Mesa Inbound"
"sounds" "3"
"classname" "worldspawn"
}
{
"origin" "-1784 24 -500"
"targetname" "runnerguy"
"angle" "270"
"classname" "monster_scientist"
}
{
"origin" "-2798 882 531"
"targetname" "trainwalk"
"angle" "87"
"classname" "monster_scientist"
}
Это самое начало энтпатча c0a0.

При поиске по стандартным картам ХЛ на букву "c" (c*.bsp, включая карту crossfire) показывается 4110 найденных значений "angle" на 100 карт. Как я уже писал, используется повсеместно и далеко за примером лезть не нужно.

**Comment by Qwertyus3D** [comment]
Карта c2a3b имеет 222 случая использования "angle", на остальных - от 6 до 108 случаев использования.

**Comment by Qwertyus3D** [comment]
Если вопрос в том, где ещё, кроме точечных энтити используется, то точно также используется для func_door, func_door_rotating, func_button, func_rot_button, func_wall, func_breakable, func_train, trigger_push, func_tank, func_tankrocket, func_tankmortar, func_tanklaser, func_conveyor, func_platrot, func_water, env_bubbles, trigger_hurt (поиск вручную по картам). На точечных энтити абсолютно на всех. Думаю, для любой энтити, на которую в принципе действует angles, будет действовать в качестве упрощённой альтернативы и angle.

**Comment by Qwertyus3D** [comment]
Я так предполагаю, предрелизные версии игры делались с FGD, в котором практически для всех энтити использовался параметр angle. Вероятно, позже они пришли к необходимости в отдельных случаях использовать поворот энтити по pitch и roll, и добавили angles. И уже после релиза в том FGD, который вошёл в комплект SDK ХЛ, angles стало использоваться по умолчанию, во избежание путаницы. Но на картах ХЛ и Опфора angle используется везде.

**Comment by UnrealKaraulov** [comment]
А что именно не хватает, отображения угла поворота точечных ентити? (типа  стрелки какой-то?)

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Основное пожелание - чтобы энтити с параметром angle были сориентированы в соответствии с указанным углом поворота, потому что сейчас этого нет. Дополнительное пожелание я уже делал в ветке оригинальной программы: https://github.com/wootguy/bspguy/issues/86 Конечно, хотелось бы, чтобы было видно, в какую именно сторону "смотрят" точечные энтити в принципе. Не важно, повёрнуты они или нет. Хотя бы при выделении объекта. Потому что в ряде случаев это имеет значение. Можно указательную стрелку отображать, либо подсвечивать фронтальную сторону параллелепипеда энтити.

**Comment by UnrealKaraulov** [comment]
Я понял, просто я совсем не разбираюсь в том как использовать рендер и шейдеры :) Даже рендер MDL моделей до сих пор добавить не смог, но я попробую все это сделать как-нибудь)

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Так ведь для параметра angles всё работает, тут вроде как нужно скопировать ту же функцию для angle. Остальное уже как второстепенные пожелания по улучшению функционала. П. С. Спасибо за обновление!

**Comment by UnrealKaraulov** [comment]
> @UnrealKaraulov Так ведь для параметра angles всё работает, тут вроде как нужно скопировать ту же функцию для angle. Остальное уже как второстепенные пожелания по улучшению функционала. П. С. Спасибо за обновление!

Я проверял "angle" не работает ни для каких entity, в игре угол поворота не изменяется.

**Comment by UnrealKaraulov** [comment]
похоже на то что оно работает только для точечных entity в игре...

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D все я понял кажись, для дверей точно не работает, и для многих других тоже. (как и angles)

Но для всего чего должно работать, сделаю что бы работало :)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал https://github.com/UnrealKaraulov/newbspguy/actions/runs/3451983520

**Comment by UnrealKaraulov** [comment]
https://github.com/UnrealKaraulov/newbspguy/commit/b89a825026eed87419a96a35944fe6fab4a15d78
