### ISSUE TITLE
Cannot move origin with transformation tool on new created brushes 

### ISSUE THREAD

**Issue by GarompaEstomper** [UnrealKaraulov/newbspguy#100]
I don't know if its a display issue or not, but this is important for creating the teleport brushes after merging.

How to reproduce the issue:

1- create a new brush entity
2- use the transformation tool and set it to Move, and Origin
3- right click the origin and center it, then align it to bottom
4- the origin will be looking fine, but deselecting the brush entity and selecting it again will show that the origin didn't move

**Comment by UnrealKaraulov** [comment]
Thanks, in new version I can fix some bugs with Transformation.

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper in latest build all issues with transformation fixed ?

**Comment by GarompaEstomper** [comment]
> @GarompaEstomper in latest build all issues with transformation fixed ?

Yes and No, now its worse hehehe, the origin of the new created brush appears now at the 0 0 0 origin of the map for some reason, instead of being at the center of the created brush. Right clicking on it and choosing any option (center, align bottom or whatever) moves the origin just a little bit nearby the origin  0 0 0 so thats broken too. 
Moving the origin with the axis arrows by grabbing it with the mouse works bad too, but this feature does not really matter at least to me. Doing this the origin moves VERY slowly, and only in the X axis (pink axis) no matter if you are grabbing the pink, blue or green axis (x y or z, it always will move in the X pink axis)

But, the position of the origin at least is now saved correctly, which is a step forward :)

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper yes origin position without entity offset, it can be fixed

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper fixed in latest build ?

Also now align works in two modes, in object and in origin.

**Comment by GarompaEstomper** [comment]
> @GarompaEstomper fixed in latest build ?

Yes, now it all works fine as it should and the origin is saved properly too :) great work!! I used to use the old bspguy to do this part before
