### ISSUE TITLE
Crash and weird behavior with unknown characters (ü and maybe others)

### ISSUE THREAD

**Issue by GarompaEstomper** [UnrealKaraulov/newbspguy#102]
Recently I came across a problem with some maps that contained entities with the word "targetname" "tür".
It displayed the "ü" as a "?" and when selecting the name to change it the newbspguy did weird things with the character/letter input, deleting the last 2 chars, disappearing the entire input, etc, weird stuff. 

I was not going to report this, but then today, it crashed because of that. I had to change all those characters to a normal character in a text editor then import the ent file again. I believe this is easily reproducible, just create a bunch of entities that trigger each other and have a ü and try to edit them later.

I believe there might be other characters that may cause this.

**Comment by Qwertyus3D** [comment]
Cürsed

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper latest newbspguy release has this issue? 

I think if font not support this character can be entered. 

Just don't use bad characters.
