### ISSUE TITLE
Can compile, but can't link on Arch Linux

### ISSUE THREAD

**Issue by malespiaut** [UnrealKaraulov/newbspguy#103]
Hello,

I've downloaded the latest revision 3560fb4 with all the dependencies.

I've generated the Makefile using the command `cmake -S . -B build`.

Linking bspguy fails, and throw the following error:

```
/usr/bin/ld: CMakeFiles/bspguy.dir/src/editor/BspRenderer.cpp.o: in function `BspRenderer::loadClipnodes()':
BspRenderer.cpp:(.text._ZN11BspRenderer13loadClipnodesEv+0x239): undefined reference to `tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, long)'
```

Best regards

**Comment by karakakarkarkar** [comment]
> Hello,
> 
> I've downloaded the latest revision [3560fb4](https://github.com/UnrealKaraulov/newbspguy/commit/3560fb4b0745e1b10bd8da96a661970e17645da3) with all the dependencies.
> 
> I've generated the Makefile using the command `cmake -S . -B build`.
> 
> Linking bspguy fails, and throw the following error:
> 
> ```
> /usr/bin/ld: CMakeFiles/bspguy.dir/src/editor/BspRenderer.cpp.o: in function `BspRenderer::loadClipnodes()':
> BspRenderer.cpp:(.text._ZN11BspRenderer13loadClipnodesEv+0x239): undefined reference to `tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, long)'
> ```
> 
> Best regards

This is "for each" loop (with multithreading)? I don't know why not works linking ... I bad know linux arch :(

**Comment by UnrealKaraulov** [comment]
@malespiaut I don't know linux arch
