### ISSUE TITLE
Спрайты для ентити (fgd) отображаются повёрнутыми на 90 градусов

### ISSUE THREAD

**Issue by Nord1cWarr1or** [UnrealKaraulov/newbspguy#104]
![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/99011793-a867-4c54-9205-f40dc759caed)

**Comment by Qwertyus3D** [comment]
Да, и при этом передняя и задняя стороны спрайта развёрнуты в противоположных направлениях.

**Comment by UnrealKaraulov** [comment]
исправлено в последней версии?

**Comment by Nord1cWarr1or** [comment]
> исправлено в последней версии?

https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2024.02.22_15-03
Проверил эту, программа открывается, затем сразу закрывается. В терминале следующее:
![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/4628b695-1fb8-4ce0-aa77-a43f488361f6)

**Comment by Qwertyus3D** [comment]
Нерабочие последние три релиза, крашатся. Так что пока без исправлений.

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or @Qwertyus3D краш должен быть пофикшен в последней версии.

**Comment by Nord1cWarr1or** [comment]
Теперь они перевёрнуты на 180 градусов.
![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/2b44989c-30a2-4292-89aa-07d5b56dd0c3)

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or ага вижу:(

но стало ведь лучше чем было )))))))

в следующем билде постараюсь исправить

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or в последнем билде

https://github.com/UnrealKaraulov/newbspguy/assets/88730285/627ef9b8-70d0-456d-862c-cea9bf99228f

Лучше стало или нет?

**Comment by Nord1cWarr1or** [comment]
Да, сейчас нормально
