### ISSUE TITLE
Не отображаются некоторые текстуры

### ISSUE THREAD

**Issue by Nord1cWarr1or** [UnrealKaraulov/newbspguy#105]
Стандартная карта cs_office
![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/b2c9f4c1-f9e7-4cab-be03-c2ae1451383c)

Пути к директориям указаны:
![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/956df780-2537-414f-8614-e3943e7edfdf)
![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/f3db2d0d-db45-47ec-98cf-0150c962c660)
![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/bc2a09bf-b7b8-4c0e-b8b1-27e62f38b4fa)

**Comment by Qwertyus3D** [comment]
Я так понимаю, указана в ресурсах только папка cstrike, а папка valve не указана. Поэтому не подгружаются текстуры оттуда.

**Comment by Nord1cWarr1or** [comment]
> Я так понимаю, указана в ресурсах только папка cstrike, а папка valve не указана. Поэтому не подгружаются текстуры оттуда.

Указал, не помогло.

![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/368d986a-f498-4b01-ad5d-9fd56815699f)

**Comment by Qwertyus3D** [comment]
Значит, текстур нету там, где они должны быть. Либо нужного wad-файла нет в указанной папке, либо в нём нет указанных текстур, либо сам файл битый. На данный момент проблем с подгрузкой текстур у программы нет, если пути правильно указаны.

**Comment by UnrealKaraulov** [comment]
> > Я так понимаю, указана в ресурсах только папка cstrike, а папка valve не указана. Поэтому не подгружаются текстуры оттуда.
> 
> Указал, не помогло.
> 
> ![изображение](https://private-user-images.githubusercontent.com/47604048/306990863-368d986a-f498-4b01-ad5d-9fd56815699f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTA5MzgsIm5iZiI6MTcwODYxMDYzOCwicGF0aCI6Ii80NzYwNDA0OC8zMDY5OTA4NjMtMzY4ZDk4NmEtZjQ5OC00YjAxLWFkNWQtOWZkNTY4MTU2OTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE0MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMjkzYmJlMmIxYTMyZTI1ZDBmNWNkZTYwNmRkZTA0Yzg1M2YzMGM4MDBlMGExNjNiOTg0ZTY0Y2Q1NGI1NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bqXI3lFUjMghwxQMQO-tJ3eVdUkfc4IUkW8I50nk90o)

а если cstrike и valve просто написать, без полного пути

**Comment by karakakarkarkar** [comment]
возможно действительно файла нет в папке или сборка сервера заточена под windows и используются пути с различными регистрами букв в названии wad  файлов

**Comment by karakakarkarkar** [comment]
пути к fgd и папкам с ресурсами можно указать относительные, там автоматически подставлят все возможные комбинации, и в итоге проверит так же и папку GAMEDIR+относительный путь.

**Comment by Nord1cWarr1or** [comment]
> пути к fgd и папкам с ресурсами можно указать относительные, там автоматически подставлят все возможные комбинации, и в итоге проверит так же и папку GAMEDIR+относительный путь.

Помогло выставление отнсительного пути. Спасибо.

Однако, тогда не совсем понятно, почему абсолютный путь не сработал? Это как-то нелогично.

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or ошибка была 
![image](https://github.com/UnrealKaraulov/newbspguy/assets/88730285/67ed185b-58f8-4624-8e5c-a97cb2834a0e)
исправлено теперь там будут работать и абсолютные пути
