### ISSUE TITLE
[CS 1.6] Moving/creating a ladder crashes the game in case of interaction

### ISSUE THREAD

**Issue by eXPc023** [UnrealKaraulov/newbspguy#109]
Open a map with ladder in BspGuy.
Move it from the origin/or create another one.
Save it and open the map in Counter-Strike 1.6.
Try to use the ladder.
Game hangs/crashes.

**Comment by karakakarkarkar** [comment]
@eXPc023 can you upload sample map?

**Comment by UnrealKaraulov** [comment]
@eXPc023 issue closed because no map attached.

**Comment by eXPc023** [comment]
?? You can use any map to reproduce the behavior: cs_assault, de_nuke, cs_siege...
You need to have CS anyway to reproduce this anyway, so you'd already have those maps...

**Comment by eXPc023** [comment]
And why are you closing an issue before 24 hours? Maybe I live in a different time zone and my time is limited? And I told you to how to reproduce the issue? Is it too hard for you to load a map from Counter-Strike? You know what? I don't care if this is going to be fixed or not. This behavior is simply unacceptable.

**Comment by UnrealKaraulov** [comment]
@eXPc023 I do close issue if no sample map attached.
