### ISSUE TITLE
Карта не отображается в программе, если в расширении файла есть заглавные буквы

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#11]
Если расширение файла не "bsp", а что-то типа "BSP" или "Bsp", то карта не отображается программой. Оригинал, кстати, вообще сразу вылетает, а форк не вылетает, но карту не показывает.

**Comment by UnrealKaraulov** [comment]
Понял если не забуду исправлю

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D исправил в https://github.com/UnrealKaraulov/newbspguy/commit/861eb287d065d21abc577928a281b36e932029a3
