### ISSUE TITLE
Вылеты при создании новых энтити

### ISSUE THREAD

**Issue by DenAkimov** [UnrealKaraulov/newbspguy#112]
При попытке создать новую энтити или BSP модель, при копировании существующих энтитей/BSP моделей или при их удалении происходит вылет. Иногда перед вылетом пропадает worldspawn:

![image](https://github.com/UnrealKaraulov/newbspguy/assets/153075618/53172641-68b6-4a04-ad64-62a0cc1f173c)

Вылет с точечными энтити начался со сборки: "version add 0.01 :)"
Вылет с BSP моделями начался со сборки: "Fix face validation. Some bugfixes. Etc."

**Comment by UnrealKaraulov** [comment]
@GusTheForkliftOperator исправил, вернув часть изменений обратно.
