### ISSUE TITLE
Не работает масштабирование BSP моделей.

### ISSUE THREAD

**Issue by DenAkimov** [UnrealKaraulov/newbspguy#113]
Оси можно двигать, реальные размеры не меняются. 

![image](https://github.com/UnrealKaraulov/newbspguy/assets/153075618/21c8fba8-1d44-4b9f-bdb6-c5b90b320b30)

**Comment by Qwertyus3D** [comment]
В феврале ( https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2024.02.23_17-46 ) было сделано изменение масштабирования - после каждого изменения размера браша была добавлена очистка задействованных под этот браш клипнодов. Это нужно было, чтобы клипноды не увеличивались после каждого действия. Из-за этого появилась небольшая задержка изменения - программе нужно около секунды, чтобы выполнить очистку. Пока программа делает очистку, нельзя дёргать оси изменения размера - это приводит к сбоям их работы. Оси могут пропасть, либо перестать менять модель, либо сдвигаются непропорционально размерам модели. Чтобы этого не происходило, когда меняете размер браша, нужно было чуть-чуть подождать, пока модель "мигнёт" после изменения размера. И только тогда опять можно двигать оси.

Чуть позже, насколько я вижу, появились какие-то проблемы с масштабированием в плане стабильности - программа стала вылетать, оси стали пропадать после выполнения более чем 1 изменения размера, даже если ждёшь очистку. По крайней мере вижу, что в ряде более поздних билдов это происходит.

В последних билдах вижу, что, вероятно, появились какие-то проблемы с очисткой - ощущение, что она задерживается или не срабатывает, т. к. иногда нет "мигания" модели. После этого оси начинают глючить. Это происходит вплоть до предпоследнего рабочего релиза https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2024.03.26_10-06

Самый новый текущий билд вообще имеет проблему того, что модель не меняется в размерах сразу, когда двигаешь оси. А меняется только после очистки, видимо. При этом есть вылеты при повторных изменениях размера.

Я бы предложил по поводу задержки на очистку прятать оси до тех пор, пока очистка не выполнена. Чтобы нельзя было тянуть оси в этот момент. Если, конечно, нет каких-то других идей, как повысить стабильность. Ну и последний билд явно самый глючный, надо исправлять.

**Comment by DenAkimov** [comment]
> В феврале ( https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2024.02.23_17-46 ) было сделано изменение масштабирования - после каждого изменения размера браша была добавлена очистка задействованных под этот браш клипнодов. Это нужно было, чтобы клипноды не увеличивались после каждого действия. Из-за этого появилась небольшая задержка изменения - программе нужно около секунды, чтобы выполнить очистку. Пока программа делает очистку, нельзя дёргать оси изменения размера - это приводит к сбоям их работы. Оси могут пропасть, либо перестать менять модель, либо сдвигаются непропорционально размерам модели. Чтобы этого не происходило, когда меняете размер браша, нужно было чуть-чуть подождать, пока модель "мигнёт" после изменения размера. И только тогда опять можно двигать оси.
> 
> Чуть позже, насколько я вижу, появились какие-то проблемы с масштабированием в плане стабильности - программа стала вылетать, оси стали пропадать после выполнения более чем 1 изменения размера, даже если ждёшь очистку. По крайней мере вижу, что в ряде более поздних билдов это происходит.
> 
> В последних билдах вижу, что, вероятно, появились какие-то проблемы с очисткой - ощущение, что она задерживается или не срабатывает, т. к. иногда нет "мигания" модели. После этого оси начинают глючить. Это происходит вплоть до предпоследнего рабочего релиза https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2024.03.26_10-06
> 
> Самый новый текущий билд вообще имеет проблему того, что модель не меняется в размерах сразу, когда двигаешь оси. А меняется только после очистки, видимо. При этом есть вылеты при повторных изменениях размера.
> 
> Я бы предложил по поводу задержки на очистку прятать оси до тех пор, пока очистка не выполнена. Чтобы нельзя было тянуть оси в этот момент. Если, конечно, нет каких-то других идей, как повысить стабильность. Ну и последний билд явно самый глючный, надо исправлять.

Понятно, давно не пользовался программой и пропустил данное изменение. Потестил в последней версии (с водой на карте bounce.bsp, новые модели создать нельзя - вылет), действительно иногда очистка не проходит и оси сбиваются. При этом происходит вылет если пытаться отменить с помощью undo именно это холостое масштабирование.

**Comment by UnrealKaraulov** [comment]
Да все заметил похоже я чето перемудрил в обнове, хотел упростить код но как-то не очень успешно. Ловлю неинициализированные переменные и т.п Сколько не пытался найти в чем дело не смог, то просто откатываю изменения и буду дальше багфиксами заниматься, пока все руки не доходили)

**Comment by UnrealKaraulov** [comment]
@GusTheForkliftOperator исправил, вернув часть изменений обратно.

**Comment by DenAkimov** [comment]
Очистка проходит только один раз, после этого не работает (или по крайней мере не объявляет о себе миганием). Оси сбиваются. Если отменять изменения функцией undo, то можно получить... интересные результаты.

![image](https://github.com/UnrealKaraulov/newbspguy/assets/153075618/3fa58bfd-732f-437e-a072-9a819bee7e57)

**Comment by DenAkimov** [comment]
https://github.com/user-attachments/assets/2c54f8f6-ba5f-456d-b47c-b9098ddc0bad

**Comment by DenAkimov** [comment]
Оси все таки работают нормально, если между каждым движением ждать несколько секунд. При этом "мигание" происходит только при первом изменении, и не соответсвует прохождению очистки (можно поломать оси сразу после "мигания").

**Comment by UnrealKaraulov** [comment]
да я уже забросил обновы пока что :( 

лень в одно рыло все делать) может через год вернусь к обновам))

**Comment by UnrealKaraulov** [comment]
> Оси можно двигать, реальные размеры не меняются.
> 
> ![image](https://private-user-images.githubusercontent.com/153075618/319603324-21c8fba8-1d44-4b9f-bdb6-c5b90b320b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTA1OTQsIm5iZiI6MTczMTMxMDI5NCwicGF0aCI6Ii8xNTMwNzU2MTgvMzE5NjAzMzI0LTIxYzhmYmE4LTFkNDQtNGI5Zi1iZGI2LWM1YjkwYjMyMGIzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwNzMxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWQ1YjJhY2UzZDczOWMzOWY4OTJkMTg0NmZhY2FiM2JiNDJlNTY4YzZjMTY0MWUwZGU5ZjYxZDZlZGJjYmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZIMZlUtnOgMKqWqsYVs4jTmEdlPX39CByoyn1Cs_Neg)

Что в последней версии, проблема сохраняется?

**Comment by DenAkimov** [comment]
Размеры можно менять без проблем если ждать несколько секунд между каждым движением оси. 

> В феврале ( https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2024.02.23_17-46 ) было сделано изменение масштабирования - после каждого изменения размера браша была добавлена очистка задействованных под этот браш клипнодов. Это нужно было, чтобы клипноды не увеличивались после каждого действия. Из-за этого появилась небольшая задержка изменения - программе нужно около секунды, чтобы выполнить очистку. Пока программа делает очистку, нельзя дёргать оси изменения размера - это приводит к сбоям их работы. Оси могут пропасть, либо перестать менять модель, либо сдвигаются непропорционально размерам модели. Чтобы этого не происходило, когда меняете размер браша, нужно было чуть-чуть подождать, пока модель "мигнёт" после изменения размера. И только тогда опять можно двигать оси.

Мигание происходит только один раз при первом изменении, и не соотвествует завершению очистки клипнодов ибо сразу после мигания можно обломать оси.

**Comment by DenAkimov** [comment]
Сейчас вроде бы гораздо стабильнее. Оси какое-то время не двигаются, но не сбиваются и программа не вылетает.

**Comment by UnrealKaraulov** [comment]
@DenAkimov я исправлял серьезные косяки, теперь и фпс не должно садиться во время маштабирования, и в GUI transform widget не должно быть зависаний, похоже что стало лучше но какая-то проблема все еще имеется?

**Comment by DenAkimov** [comment]
Проблем пока не обнаружил.

**Comment by UnrealKaraulov** [comment]
Ладно тогда закрываю issue если проблема решилась
