### ISSUE TITLE
Windows XP compatibility is broken in the newest version

### ISSUE THREAD

**Issue by B3HKO** [UnrealKaraulov/newbspguy#114]
I was happy, that this cool tool will run on Win XP, but when I started it :
![crash](https://github.com/UnrealKaraulov/newbspguy/assets/138452412/d001dbcf-6bba-4644-8078-b88a89783448)
This is the latest version on clean Windows XP x86 SP3.
Who knows for how long the compatibility is broken, I didn't try the previous versions.
CompareStringEx is supported on Windows Vista or above in the kernel, if I recall correctly.
I'm open for providing more info about the error and testing for you.

**Comment by UnrealKaraulov** [comment]
Yes windows xp build not works because require CompareStringEx function :(

**Comment by B3HKO** [comment]
I tried on random some versions thru the many release pages. I don't think, that there is even one version ever, that works on Windows XP.
Are you sure you use CompareStringEx function deliberately? Sometimes due to a wrong compile tool versions or compile parameters, Windows XP compatibility is broken because of missing functions, which are not even used at all. This is easily fixable with the right tools and parameters.
I can test in XP for you.

**Comment by UnrealKaraulov** [comment]
@B3HKO https://github.com/tumagonx/xompie/ can be used to return Windows XP compatibility?

**Comment by UnrealKaraulov** [comment]
For example using hex editor (or just notepad++) replace kernel32.dll in bspguy.exe to kernelxp.dll and put this file from repository to bspguy.exe directory.

**Comment by UnrealKaraulov** [comment]
No, now CloseThreadpoolWork not found 🤣 

Need use another build tools I think

**Comment by B3HKO** [comment]
I also tried my set of tools, tring to "XP-fy" the exe, but with no success.
I think, the only option is to set up a virtual machine, install XP and install XP compatible compiler.
Older Visual $tudio is not the only option for a compiler, MinGW, GCC and such.
The question is: would you bother?

**Comment by UnrealKaraulov** [comment]
@B3HKO fixed in latest build

**Comment by B3HKO** [comment]
Uhmm... , "Now WinXP release really works on WinXP", how you decided that XD
I tried the last 3 releases and they still give the "CompareStringEx" error.
So, what is happening?
