### ISSUE TITLE
Moving origin in new bsp models is not displayed right or is wrong

### ISSUE THREAD

**Issue by GarompaEstomper** [UnrealKaraulov/newbspguy#116]
As the title says. I create new bsp models and scale them to use as seamless teleports when merging maps. For this to work fine, I use transformation tool to move the new model's origin by right click and choosing "center", but it does not center it, it ends up looking a few units off the center :S, but sometimes, it does look fine. But when I load the map into the old bspguy the origin does not even appear ha. And if I close and load it again with newbspguy the origin that looked fine is now not looking fine haha.

This doesnt happen in the old bspguy so I use that one only for this task of creating the models and moving the center. Yet at the same time during tests the teleports work fine like if the origin is truly in the center, so most probably this is just a visual glitch. But it is very reproducible.

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper not fixed in latest newbspguy version?

**Comment by GarompaEstomper** [comment]
Yes this is already fixed

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper this is strange) but okay! thanks for bugreport)
