### ISSUE TITLE
[Enhancement] Add Faces/Vertices to Existing Models

### ISSUE THREAD

**Issue by marigi64** [UnrealKaraulov/newbspguy#117]
I figure this is a rather big request, but would it be possible to implement a way to add new vertices/faces to existing models/Worldspawn as part of the face editor?

Some Goldsrc maps have missing faces on complex geometry due to being assigned to Worldspawn. For example some hanging rockets in hl1 (c2a5d). 

![map_hole](https://github.com/UnrealKaraulov/newbspguy/assets/53112738/62c47a55-1b2e-447d-a7a2-c2628e45d9fd)
A feature for adding faces/verts to Worldspawn could greatly help fix these problems.

**Comment by UnrealKaraulov** [comment]
@marigi64 you can use manually verts manipulation with Face editor widget to edit near faces, or add model with needed forms and place them.
