### ISSUE TITLE
Some models display wrong in their x or z directions

### ISSUE THREAD

**Issue by GarompaEstomper** [UnrealKaraulov/newbspguy#118]
Specially the spore plant from opposing force shows up in the editor facing one way but ingame it faces the other. This one is inverted in the Y axis I think but needs confirmation.
Then, most weapons rotate inverted in their X axis if i'm not mistaken. If you want ingame your gun to have 20 0 0  then you must do that in the editor but to calculate the rotation visually in the editor you have to use the negative -20 0 0 to see how it really will be ingame.

**Comment by Qwertyus3D** [comment]
It may depend on different models you have in different folders where BSPGuy look for them. Or, if it's a problem of negative pitch, you can add this type of entity into list of negative Pitch entities in Rendering settings.

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper
