### ISSUE TITLE
[suggestion] Monstermaker fix

### ISSUE THREAD

**Issue by GarompaEstomper** [UnrealKaraulov/newbspguy#119]
Would help greatly in converting and fixing maps for sven if you can add a fix that transforms the monstermakers into squadmakers and automatically also adds the auto size bbox spawnflag (spawnflag 32). Since monstermaker and squadmaker share spawnflags, it should be super easy to add this, just replace all "classname" "monstermaker" with "classname" "squadmaker" and add +32 to the spawnflags number.

**Comment by Qwertyus3D** [comment]
Open Entity Report, filter entities by Class - Monstermaker. Select ALL the list using Shift button. Go to the Flags in the entity settings, check flag 32 (sixth checkbox). Then go in Smart Edit tab, find Classname field and replace 'monstermaker' with 'squadmaker'. Wait for the program to rename all the selected entities.

That's all!!

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper You can use the tip from Qwertyus3D for this purpose.
