### ISSUE TITLE
Добавить сортировку на наличие определённого флага у выбранного типа энтити

### ISSUE THREAD

**Issue by SmileyAG** [UnrealKaraulov/newbspguy#12]
Было бы здорово, если была бы опция вроде `Flags filter`, с помощью которой я мог бы проверить какое кол-во энтитей определённого типа имеют нужный мне флаг.

Название флага можно парсить из .fgd файла, а если нету, тогда мы просто указываем его битность, примерная позиция где должен быть этот фильтр:

![0](https://user-images.githubusercontent.com/58108407/177424732-4b941f95-cc9b-49ff-aff4-1a6d0409cb8b.PNG)

Пример как будет выглядеть лист поиска для `func_door` :

```
Starts Open (1)
2
Don't link (4)
Passable (8)
16
Toggle (32)
64
128
Use Only (256)
Monsters Can't (512)
```

**Comment by UnrealKaraulov** [comment]
> Было бы здорово, если была бы опция вроде `Flags filter`, с помощью которой я мог бы проверить какое кол-во энтитей определённого типа имеют нужный мне флаг.
> 
> Название флага можно парсить из .fgd файла, а если нету, тогда мы просто указываем его битность, примерная позиция где должен быть этот фильтр:
> 
> ![0](https://user-images.githubusercontent.com/58108407/177424732-4b941f95-cc9b-49ff-aff4-1a6d0409cb8b.PNG)
> 
> Пример как будет выглядеть лист поиска для `func_door` :
> 
> ```
> Starts Open (1)
> 2
> Don't link (4)
> Passable (8)
> 16
> Toggle (32)
> 64
> 128
> Use Only (256)
> Monsters Can't (512)
> ```

А чем это отличается от keyvalue filter ?

**Comment by UnrealKaraulov** [comment]
@SmileyAG а чем это отличается от keyvalue filter ? может лучше туда выпадающий список сделать

**Comment by UnrealKaraulov** [comment]
Все понял, посмотрю что можно сделать

**Comment by UnrealKaraulov** [comment]
@SmileyAG https://github.com/UnrealKaraulov/newbspguy/commit/b1b41cbd87c07bf4254d4459fd1854eade9eb067

Правильно я понял?

**Comment by SmileyAG** [comment]
> @SmileyAG [b1b41cb](https://github.com/UnrealKaraulov/newbspguy/commit/b1b41cbd87c07bf4254d4459fd1854eade9eb067)
> 
> Правильно я понял?

Да, именно. Спасибо огромное за реализацию такой фичи! Закрываю теперь этот issue.
