### ISSUE TITLE
Decouple lightmap texture filtering options from other textures

### ISSUE THREAD

**Issue by SirYodaJedi** [UnrealKaraulov/newbspguy#120]
Currently, disabling texture filtering in settings sets nearest filtering for *all* textures, including lightmaps. This is inaccurate; even in software renders, lightmaps always use linear interpolation, regardless of gl_texturemode. (Skyboxes are also like this in vanilla Half-Life, but only in hardware rendering and not in Quake source ports.) Nonetheless, having the option to display lightmaps with nearest filtering would sometimes be useful.

So the texture filtering option should be split into three options:
* Texture filtering [ `No` (nearest) / `Yes` (Linear) ]  - this is what the current option would map to
* Filter lightmaps [ `Always (default)` / `Never` / `Synchronized` ] - "synchronized" would use whatever the regular texture filtering setting is set to
* Filter skyboxes [ `Always (default)` / `Never` / `Synchronized` ]  - if/when skybox rendering is implemented, and shouldn't affect Quake 1 skies if those are implemented

Also, it'd be nice to have a hotkey that toggles the main texture filtering setting on the fly, like hitting F in Jack.

**Comment by UnrealKaraulov** [comment]
Sorry, I don't have time to add these little things.
