### ISSUE TITLE
BSPX support

### ISSUE THREAD

**Issue by SirYodaJedi** [UnrealKaraulov/newbspguy#121]
This is mostly used by IdTech 2+3 source ports, but Xash FGWS supports some of it as well. The features I think are practical and feasible to implement are such:

- [ ] Parse BSPX headers.
    - [ ] Load [known lumps](https://developer.valvesoftware.com/wiki/BSPX); see [FTE](https://github.com/fte-team/fteqw) and [ericw-tools](https://github.com/ericwa/ericw-tools) for reference implementations

- [ ] Be able to toggle between regular lightmaps and lightmaps using `DECOUPLED_LM`, `RGBLIGHTING`, or `LMSHIFT`+`LMOFFSET`+`LMSTYLE`
    - [ ] Option to embed a LIT file as an `RGBLIGHTING` lump, or extract said lump to a LIT file.

- [ ] Be able to toggle between regular 4-style lightstyles and 65k-style `LMSTYLE16` lightstyles, regardless of which type of lightmap is being viewed.

- [ ] Be able to work with LIGHTINGDIR "deluxmaps" in the same way as you can for lightmaps (they're just [normal maps](https://en.wikipedia.org/wiki/Normal_mapping) which are formatted like lightmaps)
    - [ ] Option to embed a LUX file as an `LIGHTINGDIR` lump, or extract said lump to a LUX file.

- [ ] Be able to parse FTE-style env_cubemap entities to create `ENVMAP` and `SURFENVMAP` lumps, optionally stripping said entities after creating the lumps
    - [ ] Be able to recreate those entities from the `ENVMAP` lump.

**Comment by SirYodaJedi** [comment]
Ramblings about stuff outside of the practicality and feasibility criteria:
Ability to load/view/edit `LIGHTING_E5BGR9` lightmaps would be neat, but niche and probably difficult. `BRUSHLIST` lump editing would have to wait for #101. MDL2BSP could write to the `VERTEXNORMALS` lump, I guess.

**Comment by SirYodaJedi** [comment]
> Option to embed a LIT file as an RGBLIGHTING lump, or extract said lump to a LIT file.

reference: https://github.com/jpiolho/QEBSPEditor can do this (but is coded in C#)

**Comment by UnrealKaraulov** [comment]
@SirYodaJedi I can't do it, no have time for this.
