### ISSUE TITLE
Option to toggle transparency of clipnodes

### ISSUE THREAD

**Issue by tosroka** [UnrealKaraulov/newbspguy#123]
In the original bspguy it is possible to toggle clipnode transparency (in settings->rendering). Here, showing clipnodes is moved to Map->Show clipnodes, but the transparency option seems to be missing.

I'm using NewBSPGuy v4.26, ubuntu version.

**Comment by UnrealKaraulov** [comment]
![image](https://github.com/user-attachments/assets/017cab8b-6fb8-4164-9397-7994dd39a4fc)
@Madghostek
