### ISSUE TITLE
Some Faces lose Lightmaps upon loading

### ISSUE THREAD

**Issue by marigi64** [UnrealKaraulov/newbspguy#128]
I've found on some maps, faces get incorrectly flagged as "special" and end up losing their lightmaps
for example in "c1a4i.bsp"
![facebug](https://github.com/user-attachments/assets/ddfb757c-6fc3-4419-a1c6-8a1778bf323b)

**Comment by UnrealKaraulov** [comment]
@marigi64 thanks, fixed in https://github.com/UnrealKaraulov/newbspguy/commit/35dc1849e1aba8f921b8c25d60848bef9e2a55f3
