### ISSUE TITLE
No Chinese characters support.

### ISSUE THREAD

**Issue by KianaKaslanaK424** [UnrealKaraulov/newbspguy#133]
![image](https://github.com/user-attachments/assets/8dc0b058-ddcd-4260-bf9c-ee8cd4a6c726)

I'm interested in your newbspguy tool, but it doesn't support Chinese characters.

So could we add support for Chinese characters? Both Traditional and Simplified Chinese are fine.

**Comment by KianaKaslanaK424** [comment]
The ?? in the picture is Chinese characters.

**Comment by UnrealKaraulov** [comment]
@KianaKaslanaK424 you can give Chinese font file? and try to replace calibri.ttf to chinese.ttf file and test it after

**Comment by UnrealKaraulov** [comment]
@KianaKaslanaK424 msjh.ttc can be used as default Chinese font?

**Comment by UnrealKaraulov** [comment]
@KianaKaslanaK424 fixed in https://github.com/UnrealKaraulov/newbspguy/commit/2797374df8f7cf50efc61d578533fce577431cae

**Comment by UnrealKaraulov** [comment]
but sorry I don't know Chinese language, for generate translation file I use microsoft copilot bot.

![image](https://github.com/user-attachments/assets/12c4064e-2870-47bf-aa71-3008515c641d)
![image](https://github.com/user-attachments/assets/ee7d06b5-43aa-42a2-9f7a-070ba3223cc1)

**Comment by KianaKaslanaK424** [comment]
Maybe I'll find someone to translate
