### ISSUE TITLE
Copy pasting brush models creates a new model!

### ISSUE THREAD

**Issue by GarompaEstomper** [UnrealKaraulov/newbspguy#134]
Copy and pasting (paste or paste on origin) a brush model will create a new duplicate copy brush instead of making a copy of the same model and will also save that copied model as if it was being extracted, to a bsp on the specified extraction folder in the config. 
This is a big issue and it wasn't happening before. Unintentionally breaks maps CRC by creating new brush models, and extracting them, meaning that this will not be just a ripent and will give people version differs... also rarely it makes bspguy crash when doing it.

EDIT:  This problem is present since [NightBuild_2024.11.26_09-19](https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2024.11.26_09-19)

**Comment by UnrealKaraulov** [comment]
fixed in https://github.com/UnrealKaraulov/newbspguy/commit/90057b111a940268037176576f92d3981d7e422d
