### ISSUE TITLE
bspguy не запоминает язык

### ISSUE THREAD

**Issue by Den555By** [UnrealKaraulov/newbspguy#135]
Почему то при запуске он на английском языке, хотя в файле конфигурации стоит русский. Получается каждый раз нужно вручную заново выбирать русский

**Comment by Den555By** [comment]
> Почему то при запуске он на английском языке, хотя в файле конфигурации стоит русский. Получается каждый раз нужно вручную заново выбирать русский

**Comment by UnrealKaraulov** [comment]
https://github.com/UnrealKaraulov/newbspguy/commit/49f560b1e4ea1b6ec51485ed59b4d963af796dbd

исправлено
