### ISSUE TITLE
Preserve map CRC and Same directory for entity file,  settings not saving

### ISSUE THREAD

**Issue by GarompaEstomper** [UnrealKaraulov/newbspguy#136]
As the title says, I can edit the settings, and save everything perfect, except those 2 settings. Whatever I do, everytime I close the bspguy and open it again they are OFF by default.
I have to turn them on everytime I open newbspguy.

I can manually edit the config file and save it just fine, but whenever I open newbspguy again those two options get reset again to OFF

This issue is present since [NightBuild_2024.11.23_09-31](https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2024.11.23_09-31)

**Comment by UnrealKaraulov** [comment]
Fixed in https://github.com/UnrealKaraulov/newbspguy/commit/a94f96c4eb13cd457e2869860062c169e05cfaf1
