### ISSUE TITLE
Current issues with version mismatch (Preserve CRC and copypaste bug) in Sven Co-op

### ISSUE THREAD

**Issue by GarompaEstomper** [UnrealKaraulov/newbspguy#137]
Hello!
@UnrealKaraulov i have no way of contacting you, so the only thing I can do is send this message here. This is now a serious issue within the Sven Co-op community, and the usage of this tool has broken many, many maps. I beg you to please join the SCMapDB discord here https://discord.gg/KmbacjTr and read the general chat.

The issues are as follows:

- newbspguy build since 23 november 2024 has a bug that creates a new brush model number when copypasting (doing the same as the duplicate option), instead of making a new entity with the same model number. This breaks the bsp version or CRC when editing.

- Preserve CRC checkbox in the settings is always off by default. Unexperienced people that want to help and ripent maps will not know this is an issue in Sven Co-op. It would be best to have this option always ON by default and also have a warning message before saving that warns you when it detects that the CRC will be modified.

Maybe you don't know about this but these things in Sven Co-op create a huge issue where clients cannot join servers if they dont have the same CRC version map. Anyone can ripent a map without knowing and servers or clients download the latest fixes to the maps and then cannot play. And this has happened A LOT recently.

EDIT:  Someone suggested a good idea, to have an icon or a "RIPENT"  "NOT RIPENT"  alert word somewhere in a corner of the screen warning about the state of the edit. If the CRC changes its no longer a ripent.

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper fixed in https://github.com/UnrealKaraulov/newbspguy/commit/90057b111a940268037176576f92d3981d7e422d
