### ISSUE TITLE
CTRL+C any brush model crashes

### ISSUE THREAD

**Issue by GarompaEstomper** [UnrealKaraulov/newbspguy#138]
Well, as it says. doing ctrl+c or right click>copy, simply crashes newbspguy.
I'll be using the version of 11.22 that seems to be the last working fine and this is not happening on that one.

**Comment by UnrealKaraulov** [comment]
> Well, as it says. doing ctrl+c or right click>copy, simply crashes newbspguy. I'll be using the version of 11.22 that seems to be the last working fine and this is not happening on that one.

On any map or only on a specific one?

**Comment by UnrealKaraulov** [comment]
@GarompaEstomper fixed in latest version?

**Comment by GarompaEstomper** [comment]
I can't really tell because now its worse, the last version crashes when loading a map. Any map.
And yes, the copy brush crash was on any map too. haha

**Comment by UnrealKaraulov** [comment]
@UnrealKaraulov this two issues fixed in latest commit https://github.com/UnrealKaraulov/newbspguy/commit/042a53ce25e0678819d2f05bf56756db82890502 ?

**Comment by UnrealKaraulov** [comment]
> I can't really tell because now its worse, the last version crashes when loading a map. Any map. And yes, the copy brush crash was on any map too. haha

@GarompaEstomper  this two issues fixed in latest version  ?

**Comment by GarompaEstomper** [comment]
Yes, mostly. At least I tested quickly and it does not crash anymore in both cases. But now when copying a brush model, it also extracts the model to a .bsp into the work folder.
For example, I copypaste a box brush *5, and then in the bspguy folder appears a "copyModel5.bsp" just like when you extract a model.
