### ISSUE TITLE
Windows XP compatibility is still broken

### ISSUE THREAD

**Issue by B3HKO** [UnrealKaraulov/newbspguy#139]
I tried several releases after v4.27 (including 4.27), and Windows XP still gives the "CompareStringEx" error.
:(

**Comment by UnrealKaraulov** [comment]
@B3HKO thanks for report, fixed in latest build.

https://github.com/UnrealKaraulov/newbspguy/commit/f97042924474fb88dabaf7746f98c8db2bf81bf7
