### ISSUE TITLE
Turns out, the XP build is cursed XD ...

### ISSUE THREAD

**Issue by B3HKO** [UnrealKaraulov/newbspguy#140]
Nope, the XP build is still broken, throws the same error in the new "NightBuild_2024.12.20_12-19".
Just a suggestion: Since, this is a 3rd issue created, just wait for me to test a build before self proclaim the bug for fixed and close the issue XD
Other Github apps/progs/tools from you shows analogical problems under XP, so I'm assuming it is more of a compiler issue,
than using something unsupported in the code.
What compilers and parameters you use for the XP build?

**Comment by UnrealKaraulov** [comment]
@B3HKO fixed in https://github.com/UnrealKaraulov/newbspguy/commit/553a5070f846325287e2b47cc5e786c29a068f8e ?

**Comment by UnrealKaraulov** [comment]
@B3HKO thanks for report, fixed in latest build.

https://github.com/UnrealKaraulov/newbspguy/commit/acc06b60c36dc6b2109e3d751ef9b9ddae157a1e
