### ISSUE TITLE
Crash when copying and pasting entities.

### ISSUE THREAD

**Issue by mfaizsyahmi** [UnrealKaraulov/newbspguy#18]
~~It's a hit or miss bug that happens many times, but not all the time.~~  
The crash happens when you click on "paste" (either options) in the main view context menu.

I confirmed that this does not occur with the original w00tguy's bspguy. Only on this fork.

---
update: Figured out the exact way to reproduce this crash.

### steps to reproduce:

1. Have Keyvalue editor open
2. switch to raw edit mode
3. copy and paste
4. program crash

**Comment by UnrealKaraulov** [comment]
@mfaizsyahmi in latest build, same issue ?

**Comment by UnrealKaraulov** [comment]
https://github.com/UnrealKaraulov/newbspguy/actions/runs/3451983520

**Comment by UnrealKaraulov** [comment]
@mfaizsyahmi try https://github.com/UnrealKaraulov/newbspguy/actions/runs/3452012167
