### ISSUE TITLE
Lightmap Editor Not Showing Pixel Edits

### ISSUE THREAD

**Issue by marigi64** [UnrealKaraulov/newbspguy#20]
Changes to a lightmap made via clicking pixels on the lightmap editor aren't shown until after it is saved.

This did work in previous versions though.

**Comment by UnrealKaraulov** [comment]
@marigi64 thanks for report!

Fixed in https://github.com/UnrealKaraulov/newbspguy/commit/28b9b178af7a551f78d58fb09b1dd1e4379bce2f
