### ISSUE TITLE
Экспорт в obj проблема с UV

### ISSUE THREAD

**Issue by kirill-mapper** [UnrealKaraulov/newbspguy#21]
После экспорта в obj смещены V текстурные координаты, похоже что неправильно преобразуется Cдвиг по оси Y, будто положительному значению присваивается его же отрицательное значение, а отрицательному положительное и так у всех текстур.
![изображение](https://user-images.githubusercontent.com/95088806/202795883-ab711f69-8bfb-41ca-bace-985cdb61a404.png)

**Comment by UnrealKaraulov** [comment]
@kirill-mapper знаю о проблеме, пока что не знаю как решить

**Comment by UnrealKaraulov** [comment]
@kirill-mapper исправил в https://github.com/UnrealKaraulov/newbspguy/commit/e015fd2cb8c4abb8d54f7bc5313ae962a7728b32

благодарю за багрепорт :)
