### ISSUE TITLE
Экспорт в obj Основные проблемы в построении модели.

### ISSUE THREAD

**Issue by kirill-mapper** [UnrealKaraulov/newbspguy#22]
При стандартном импорте obj, все нормали перевернутые, на виде слева, справа как должно быть:

![изображение](https://user-images.githubusercontent.com/95088806/202866147-d095b455-a636-445d-8cca-0170a1fe7ee8.png)

Но существует главная проблема, которая заключается в неправильном построении модели. Суть в том, что после импорта элемент визуально разделен на треугольники, триангулирован правильно, но по факту триангуляции как таковой нет, элемент является одним полигоном, а его триангуляция построена из множества вершин и граней соединенных друг с другом последовательно и все эти грани модели являются открытыми, что приводит к умножению вершин и граней в несколько раз. 

![изображение](https://user-images.githubusercontent.com/95088806/202865172-51041099-104e-4b05-9e38-7ffaee69bfc8.png)
В принципе, это не является такой уж большой проблемой и исправляется через 3д редактор соединив вершины и грани между собой у отдельных элементов или применив какой нибудь метод оптимизации, как в правом варианте

**Comment by UnrealKaraulov** [comment]
@kirill-mapper я плохо разбираюсь в .obj, да и в 3д в целом. 

Кстати даже не знаю для чего может понадобиться экспорт в obj :) просто сделал потому что имелись для этого все функции.

постараюсь что-то из этого исправить.

**Comment by UnrealKaraulov** [comment]
@kirill-mapper как проверить нормали эти?))

**Comment by UnrealKaraulov** [comment]
@kirill-mapper 

Исправил нормали https://github.com/UnrealKaraulov/newbspguy/commit/72516982015a24f9a3d0226ea0310dc6df4dbf73 

И убрал триангуляцию при экспорте в obj https://github.com/UnrealKaraulov/newbspguy/commit/3f010abaa46320ba730b704be57716d2da75b195

Теперь стало лучше?  

Закрываю пока что, если будут проблемы открою назад.

**Comment by kirill-mapper** [comment]
@UnrealKaraulov Да, спасибо большое, это прям то что и нужно было, теперь разный 3д софт будет разбивать полигоны, согласно своим методам триангуляции и работать с такими полигонами в разы проще. 
Еще заметил, что в самом newbspguy теперь появилась собственная триангуляция в варфрейме, вместо родного фарфрема, так должно быть?

**Comment by UnrealKaraulov** [comment]
@kirill-mapper спасибо исправил

**Comment by kirill-mapper** [comment]
@UnrealKaraulov Обнаружил небольшую проблемку в структуре obj из-за которого 3ds max не переваривает группы объектов, а импортирует только как единый мешь объект. Причем blender и Maya работает нормально с текущей структурой. 
Сейчас получается, что структура такая, - имя объекта, группы, имя материала, координаты вершин, нормалей, текстур, построение фейса по индексам и так с каждым фейсом.
А нужно, чтобы после группы шел **список координат вершин, нормалей и текстур всей группы**, а уже потом  материалы, поверхности(фейсы) по индексам.
Либо же другой вариант, когда вначале идет **весь список координат из всех групп**, а после объекты, группы, материалы, фейсы.

**Comment by kirill-mapper** [comment]
Вот три примера работающих структур в 3ds max и оригинальный из newbspguy.
[newbspguyORIGINAL.txt](https://github.com/UnrealKaraulov/newbspguy/files/10051069/newbspguyORIGINAL.txt)
[newbspguyWORK1.txt](https://github.com/UnrealKaraulov/newbspguy/files/10051070/newbspguyWORK1.txt)
[newbspguyWORK2.txt](https://github.com/UnrealKaraulov/newbspguy/files/10051071/newbspguyWORK2.txt)
[newbspguyWORK3.txt](https://github.com/UnrealKaraulov/newbspguy/files/10051072/newbspguyWORK3.txt)

**Comment by KarKarKarKarkarkar** [comment]
@UnrealKaraulov
