### ISSUE TITLE
Предложение для киллерфичи связанной с экпортом/импортом lightmap.

### ISSUE THREAD

**Issue by evgeniy-mapper** [UnrealKaraulov/newbspguy#24]
Доброго времени суток.
**Предложение**:
Поскольку есть возможность экпорта/импорта всех лайтмапов в одну текстуру, получаются аккуратно сложенные "шелы", как в развертке, было бы очень полезно добавить экпорт самой карты в "obj", развертка которой будет совпадать с данной текстурой. Простыми словами, чтобы была возможность экпортировать карту, как модель, затекстуренную лайтмапами. 

Это нужно для того, чтобы потом перезапечь новое освещение модели, используя 3D рендеры, таким образом можно будет получить качественное, просчитанное освещение и после импортировать готовую текстуру обратно.
![изображение](https://user-images.githubusercontent.com/118622365/202870960-725a3ecc-3f3a-4624-9046-f2e2281298d2.png)

Спасибо.

**Comment by UnrealKaraulov** [comment]
@evgeniy-mapper мне кажется я не так хорошо разбираюсь в obj что бы это сделать. Но попробую поковырять:)

**Comment by UnrealKaraulov** [comment]
@evgeniy-mapper не в ближайшее время, к сожалению плохо разбираюсь в 3д что бы это реализовать.

**Comment by UnrealKaraulov** [comment]
@evgeniy-mapper я не уверен на сколько это удачно будет работать ведь надо будет экспортировать огромную кучу текстур, и для каждого фейса привязывать ее ?

**Comment by evgeniy-mapper** [comment]
@UnrealKaraulov Нет, всего одна текстура, на ней развертка всей карты по частям. Экпортнул все лайтмапы и попробовал наглядно показать, как я это представляю, уж не знаю насколько это сложно реализовать. Чтобы все фейсы карты компоновались в одну развертку.
![изображение](https://user-images.githubusercontent.com/118622365/202924786-02863be3-4fd3-4ae2-a408-0ed83356e786.png)
![изображение](https://user-images.githubusercontent.com/118622365/202924772-0ea0df8c-11d7-46ec-ab7a-ebf06c425695.png)
И у меня еще вопрос, а если экпортировать карту только с lightmaps видом  в obj, точно такую же как она визуализируется в newbspguy, будет ли у неё, какая либо развертка и текстура? 
![изображение](https://user-images.githubusercontent.com/118622365/202925165-b653d872-696d-493a-b853-d36baa4d4860.png)

**Comment by evgeniy-mapper** [comment]
Например, сейчас я могу вручную каждый кусочек модели сопоставить с общей текстурой лайтмапов и целиком воссоздать целую карту, по частям, потом перезапечь освещение и импортировать назад новую текстуру. Но это будет достаточно неудобно, поэтому и возникла эта идея.

**Comment by UnrealKaraulov** [comment]
@evgeniy-mapper идея интересная, но не уверен что смогу сделать все одной текстурой, т.к в 3д программировании не силен, тут надо знать как рассчитать UV и как создать для каждого фейса материал основанный на одной текстуре. Подумаю

**Comment by KarKarKarKarkarkar** [comment]
@UnrealKaraulov
