### ISSUE TITLE
Singleplayer entity support for Clean/Optimize

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#25]
Просьба для функций Clean/Optimize сделать какую-нибудь галочку, которая запретит удаление с карты стандартных синглплеерных сущностей в ходе оптимизации. Автор утилиты предусмотрел функционал для Sven Co-op, который подразумевает, что, к примеру, trigger_autosave на карте не требуется. Вследствие чего эти триггеры удаляются после оптимизации. Не уверен, удаляется ли ещё что-либо важное для обычного синглплеера (сам с другими проблемами не столкнулся), но если да, то можно объединить в одну опцию. А то не слишком удобно после оптимизации заново восстанавливать энтити только потому, что они не нужны в Sven Co-op.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D работаю над этим, сделаю побольше настроек в редакторе, туда и эти списки включу

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал в последней версии возможность настраивать эти списки под конкретную игру 

https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2022.11.21_13-49

Так работает?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Опции в настройках появились, но есть проблема со вставкой нужных энтити в новые разделы. Кнопочки "Add new" срабатывают, только если нажимаешь на кнопку под первым пунктом раздела, остальные кнопки не реагируют на нажатие. Может быть, оставить по одной кнопке внизу каждого раздела? Чтобы не путаться, и чтобы сразу было видно, как добавляется новая строчка.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Ещё одна проблема вылезла. В новых билдах после релиза от 12 ноября точечные энтити не двигаются. При выделении пишется CONCAVE SOLID.

**Comment by Qwertyus3D** [comment]
Проблема после https://github.com/UnrealKaraulov/newbspguy/actions/runs/3478431219

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D исправил обе проблемы (https://github.com/UnrealKaraulov/newbspguy/commit/7ea1aa0745f7aaf6bdda093f58bdbb7cd64e7f34 и https://github.com/UnrealKaraulov/newbspguy/commit/2b48bab3f0a24d2dc4c8f452699d76dfc6a1ace5) Теперь работает ?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Да, красота теперь :) Спасибо! Есть ещё один вопрос, создам другую тему.
