### ISSUE TITLE
Проблемы по сборке через CMake (Win)

### ISSUE THREAD

**Issue by Psycrow101** [UnrealKaraulov/newbspguy#26]
Во время сборки проекта под win через cmake с использованием MSVC тулчейна v143 столкнулся со следующими проблемами:

1. отсутствует CMakeLists и другие необходимые для сборки файлы в glfw;
2. в CMakeLists для MSVC почему-то не указан явный стандарт c++17, хотя для другого тулчейна указан, а в vcxproj установлен stdcpplatest.

Мб glfw сделать как git сабмодуль?

**Comment by UnrealKaraulov** [comment]
Не знаю зачем я вообще оставил cmakefile для windows. Т.к проект для студии имеется.

**Comment by Psycrow101** [comment]
Для работы в другой IDE. Например в CLion

**Comment by UnrealKaraulov** [comment]
@Psycrow101 думал что только Visual Studio пользуются)))



> Мб glfw сделать как git сабмодуль?

Хочу что бы все работало "из коробки" а не заставлять людей выискивать рабочие версии imgui/glfw , в imgui так каждую версию чето убирают и потом перестает собираться)))

**Comment by UnrealKaraulov** [comment]
@Psycrow101 в игноре были cmake файлы, вернул назад.

**Comment by UnrealKaraulov** [comment]
@Psycrow101 используется filesystem по этому в Visual Studio почему-то пришлось поставить c++ latest, иначе не компилилось адекватно. (требовало include experimental и т.п)

Какие изменения еще надо внести что бы CMAKE работало ? Я по моему указывал там C++17...
Я просто не пользуюсь и не знаю чего не хватает)))

**Comment by Psycrow101** [comment]
> @Psycrow101 в игноре были cmake файлы, вернул назад.

Не хватает
glfw/CMake/glfw3Config.cmake.in
glfw/CMake/glfw3.pc
glfw/CMake/cmake_uninstall.cmake.in
glfw/src/mappings.h.in

> Какие изменения еще надо внести что бы CMAKE работало ?

https://github.com/Psycrow101/newbspguy/commit/efc0d76f91908015978bc64e39da15f77a297da1

**Comment by UnrealKaraulov** [comment]
@Psycrow101 файлы вернул, тоже в gitignore были

**Comment by Psycrow101** [comment]
Спасибо. Создал pr с остальными фиксами
https://github.com/UnrealKaraulov/newbspguy/pull/28

Теперь все собирается отлично
