### ISSUE TITLE
Optimization options' reset

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#29]
Такая проблема - когда удаляешь все энтити из какой-то категории (например, Ents that never need any hulls), то при следующем запуске программы восстанавливается список всех дефолтных энтити данной категории. Кстати, можно было бы добавить сброс к дефолтным настройкам, в виде отдельной кнопки.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал кнопку ресет, плюс там же немного убрал явное упоминание Sven как основной игры, все таки редактор хочу сделать так что бы поддерживало больше игр чем один только Sven )))

https://github.com/UnrealKaraulov/newbspguy/commit/f2ec7ff92f2d3df49be47b36af3435e8dfb5c610
