### ISSUE TITLE
Текущая версия программы не работает

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#3]
Не работает версия программы, скомпилированная после коммита Small optimize:
https://github.com/UnrealKaraulov/newbspguy/commit/c662462dd612b85b6ea4507bc462681351d84f73
https://github.com/UnrealKaraulov/newbspguy/blob/c662462dd612b85b6ea4507bc462681351d84f73/vs-project/Release/bspguy.exe

Windows 10 Pro, при запуске окно программы тут же закрывается. Работает предыдущая версия, после коммита VERY DEEP OPTIMIZE:
https://github.com/UnrealKaraulov/newbspguy/commit/27dc76501df570fdce47719ebb24a78909b459f8
https://github.com/UnrealKaraulov/newbspguy/blob/27dc76501df570fdce47719ebb24a78909b459f8/vs-project/Release/bspguy.exe

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D все еще не работает?

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D теперь в https://github.com/UnrealKaraulov/newbspguy/actions билды последние для Win/Linux

**Comment by Qwertyus3D** [comment]
Теперь я не нахожу файлов для скачивания :)

**Comment by Qwertyus3D** [comment]
Нашёл с трудом, рандомно покликав ссылки. Программа работает, спасибо.
https://github.com/UnrealKaraulov/newbspguy/actions/runs/1892282194
