### ISSUE TITLE
Hide / unhide entity options

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#30]
Я вроде предлагал это улучшение автору, но у него дело совсем не движется :) В общем, крайне полезно было бы иметь возможность любую выделенную энтити спрятать из окна просмотра кнопкой Hide. И добавить возможность, соответственно, вернуть отображение обратно. Самая простая реализация - Hide в контекстном меню энтити и Unhide all (неактивная, если ничего не спрятано) в меню Edit. Немного продвинутее - добавить чекбоксы-галочки в меню Entity Report напротив каждой энтити, чтобы было видно, какие энтити на данный момент спрятаны, какие нет. И можно было прямо по списку их прятать / показывать. Смысл сокрытия очевиден - некоторые энтити наслаиваются друг на друга и мешают манипуляциям с ними. А так - скрыл ненужные и работаешь, потом отобразил снова.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделаю. Кстати есть возможность открывать сразу несколько карт, но я просто отключил ее так как автору оригинала это не понравилось) но так как я решил поддерживать свой форк то думаю верну обратно

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Очень хотелось бы данную фичу увидеть одной из первых после решения проблем с текущими багами. Т. к. она действительно добавляет удобства при работе. :)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал в последнем обновлении

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D добавил теперь и в Entity Report (голубым цветом и всплывающая подсказка что можно нажать "показать" )

**Comment by Qwertyus3D** [comment]
Это офигенно, отдельное спасибо! Заметил только такую штуку, что в списке энтить нельзя вызвать контекстное меню на той энтите, которая в данный момент не выделена. Было бы удобно, чтобы вызвалось, для того же Hide / unhide. И ещё не работает Ctrl+A. чтобы в списке все пункты выделить сразу.

**Comment by Qwertyus3D** [comment]
И ещё, когда группу скрытых энтить выделяешь и жмёшь Unhide, то не весь выделенный список отображается, а только первый пункт.

**Comment by UnrealKaraulov** [comment]
> Это офигенно, отдельное спасибо! Заметил только такую штуку, что в списке энтить нельзя вызвать контекстное меню на той энтите, которая в данный момент не выделена. Было бы удобно, чтобы вызвалось, для того же Hide / unhide. И ещё не работает Ctrl+A. чтобы в списке все пункты выделить сразу.

CTRL+A наверное и не работало, т.к не предусмотрено изменение сразу всех Entity, можно перетащить WORLD тогда все сущности перемещаются вместе с картой

Если будет конкретный пример когда нужно выделить все сущности в Entity Report, может подумаю над добавлением.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D ну я щас загрузил обнову, там правый клик должен лучше работать в Entity Report.

**Comment by Qwertyus3D** [comment]
Да, клик работает.

>> Если будет конкретный пример когда нужно выделить все сущности в Entity Report, может подумаю над добавлением.

Ну, простой пример. Я по фильтру отбираю тип энтить, который хочу скрыть с глаз полностью, выделяю всё по CTRL+A в списке, щелчок - все энтити скрыты.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D добавил поддержку хоткея CTRL+A в Entity Report.

Закрываю, если все работает как надо то хорошо :)
