### ISSUE TITLE
Option to cut off path of WADs + WAD information

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#31]
Повтор запроса на улучшение, сделанного в ветке исходной программы. Добавить функцию стирания путей к WAD-файлам в свойствах карты. Это может быть частью оптимизации, либо сделать отдельную кнопочку где-то в окне свойств WORLDSPAWN. Пути нужны только при компиляции, а в готовой карте они мешают чтению списка WAD.

Чтобы было:
halflife.wad;xeno.wad;liquids.wad
вместо:
/my lovely Steam directory location/steamapps/common/Half-Life/valve/halflife.wad;/my lovely Steam directory location/steamapps/common/Half-Life/valve/xeno.wad;/my lovely Steam directory location/steamapps/common/Half-Life/valve/liquids.wad;

Некоторые мододелы вставляют более десятка WAD в карту, и чтение этой информации представляет серьёзную проблему.

Также можно было бы добавить информацию об используемых WAD в виджет Debug info. Чтобы был виден весь список WAD карты, и какие из них на данный момент подключены, а каких не хватает (а то иногда текстур не видно и пойди разберись). И ещё иногда получается так, что в список WAD карты попадают WAD, которые фактически не задействованы. Т. е. ни одна текстура из них не используется. Получается, что карта требует WAD, который ей не нужен. И была бы полезна информация о том, какие текстуры не найдены, либо о том, что из данного WAD никакие текстуры на карте не используются.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D 

Но если название wad файла одинаковое, но разные папки 
Например
cstrike/wadname.wad
valve/wadname.wad

Или таких случаев не бывает?

**Comment by Qwertyus3D** [comment]
Нет, движок же не ищет WADы в конкретных папках. Он приоритетом грузит файлы с указанным именем из папки мода, если их там нет - то из основной директории игры, либо из fallback_dir и ей подобных. Пути к WADам нужны только при компиляции карты, потом это избыточная информация. Тем более, что пути там не относительные, а вполне конкретные и привязанные к ПК пользователя, на котором делается компиляция. Которые не будут иметь отношения к папке мода или игры пользователя.

**Comment by Qwertyus3D** [comment]
Например, VHLT сами удаляют пути при компиляции, для них это стандартная процедура. К тому же, в BSP имеется лимит на общее число символов в графе wad, но многие об этом даже не знают. Т. е. теоретически, если пути не удалять, то карта может скомпилиться с урезанным списком WAD.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D https://github.com/UnrealKaraulov/newbspguy/commit/26868a4a191e67445a7457333262bf40deda307f ?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Традиционно, не компилится :D

**Comment by UnrealKaraulov** [comment]
> @UnrealKaraulov Традиционно, не компилится :D

исправил :)

**Comment by Qwertyus3D** [comment]
Спасибо, тоже работает. Правда, не сразу отыскал, где это. Но реализовано удобно! 👍

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D ну не знал куда это засунуть :) 

в General настройки?

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D а вторую часть не сделал

**Comment by Qwertyus3D** [comment]
Я просто не подумал, что это в виде автоматической настройки сделано. Поэтому искал какую-нибудь кнопку или пункт меню, но оказалось даже проще. Мне нравится, можно так и оставить!

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D добавил в дебаг вывод информации о текстурах

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Последние два билда крашатся в процессе прогрузки карты. Карту видно некоторое время, потом вылетает, до окончания прогрузки.

**Comment by UnrealKaraulov** [comment]
какая карта?

**Comment by Qwertyus3D** [comment]
Любая у меня.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D да я поспешил убрать reloadTextures не заметил что там устанавливается texturesloaded в false, надо отменить изменения в коде тогда крашить не будет, но я на работе и возможно только завтра утром сделаю

**Comment by Qwertyus3D** [comment]
Понял, жду. И вопрос по ходу дела - а что, редактор не позволяет визуализировать клип-браши, которые ограничивают движение игрока? Я так понял, он их вообще не отображает, и нет даже опции, по которой можно их включить/отключить. Либо это где-то в общей мешанине клипнодов.

**Comment by Qwertyus3D** [comment]
И ещё очепятка: 
![XZ](https://user-images.githubusercontent.com/98685264/205488489-49706e4b-ee98-4085-b2e5-9c96133d13d0.jpg)

**Comment by UnrealKaraulov** [comment]
> Понял, жду. И вопрос по ходу дела - а что, редактор не позволяет визуализировать клип-браши, которые ограничивают движение игрока? Я так понял, он их вообще не отображает, и нет даже опции, по которой можно их включить/отключить. Либо это где-то в общей мешанине клипнодов.

Я в этом не особо разбираюсь честно говоря :)
Кто это такие клип браши? Можно пример?

**Comment by Qwertyus3D** [comment]
Ну, когда маппер не хочет, чтобы игрок куда-нибудь запрыгнул или свалился, то создаётся невидимый браш с текстурой Clip. И игрок не может сквозь него физически пройти. Т. е. технически эта информация в скомпиленной карте есть. Но нет возможности как-то отдельно в опциях рендера включить и посмотреть, в каких местах проход ограничен.

**Comment by UnrealKaraulov** [comment]
Аа ну я понял, не уверен что смогу сделать отдельно рендер для таких, но надо будет проверить

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D что на счет крашей в https://github.com/UnrealKaraulov/newbspguy/commit/597784a7d5ca0e2d0ada9682ab7193f2d1c342ed

**Comment by Qwertyus3D** [comment]
Запускается, но поломалась поддержка включения/отключения FGD. Отображает путь вместе enabled? и не находит FGD, соответственно. И вообще, файл "похудел" на 200 Кб примерно :)

**Comment by Qwertyus3D** [comment]
Этот вариант https://github.com/UnrealKaraulov/newbspguy/actions/runs/3615915432 всё ещё крашится.

**Comment by UnrealKaraulov** [comment]
> Ну, когда маппер не хочет, чтобы игрок куда-нибудь запрыгнул или свалился, то создаётся невидимый браш с текстурой Clip. И игрок не может сквозь него физически пройти. Т. е. технически эта информация в скомпиленной карте есть. Но нет возможности как-то отдельно в опциях рендера включить и посмотреть, в каких местах проход ограничен.

Я так понял их отображает сейчас, но только если они в виде отдельной сущности. 
Самому даже интересно как сделать что бы отображались и worldpawn. 

https://github.com/UnrealKaraulov/newbspguy/commit/771e3272709679fc0ffa5bd9f169f366ba548df1

Что на счет этого варианта по крашам?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Всё так же вылет.

**Comment by UnrealKaraulov** [comment]
> @UnrealKaraulov Всё так же вылет.

Вылетает только при открытом окне DEBUG или при загрузке карты?

@Qwertyus3D у меня нет вылета на картах cstrike/valve , можно какой-то конкретный пример карты ?

**Comment by Qwertyus3D** [comment]
У меня вылетает любая. 2-3 секунды крутится Загрузка, потом вылет

**Comment by Qwertyus3D** [comment]
Пробовал удалять настройки из конфига по отдельности, и весь конфиг целиком, всё равно крэш.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D а ОС какая Windows или Linux

**Comment by Qwertyus3D** [comment]
Win10

**Comment by UnrealKaraulov** [comment]
[bspguy.zip](https://github.com/UnrealKaraulov/newbspguy/files/10153698/bspguy.zip)
@Qwertyus3D это версия с DEBUG, должно писать log.txt в папку с программой, после вылета надо его мне скинуть сюда (log.txt) я попробую узнать где вылетело.

**Comment by Qwertyus3D** [comment]
Не хватало ДЛЛ, скачал с dll-files.com. Теперь вылет сразу же:
![0xc](https://user-images.githubusercontent.com/98685264/205629076-4920656c-79e9-4647-adbc-65a1e3a59ea8.jpg)
Лога нет.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D понял, сделал что бы не требовало DLL
[bspguy.zip](https://github.com/UnrealKaraulov/newbspguy/files/10153820/bspguy.zip)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D тоже не получается запустить? :(

**Comment by Qwertyus3D** [comment]
```
Start bspguy editor with map: D:\Games\Steam\steamapps\common\Half-Life\valve\maps\c0a0.bsp
Load settings from : D:\Games\Xash3D\_Tools_\BSPGuy\bspguy.cfg
Parsing .\_Res_\fgd\halflife_2022_op4.fgd
Bsp version: 30
Read lump id: 0. Len: 28066. Offset 1275736.
Read lump id: 1. Len: 168320. Offset 124.
Read lump id: 2. Len: 928816. Offset 1303804.
Read lump id: 3. Len: 59520. Offset 201540.
Read lump id: 4. Len: 52573. Offset 1223160.
Read lump id: 5. Len: 48600. Offset 261060.
Read lump id: 6. Len: 50760. Offset 309660.
Read lump id: 7. Len: 73640. Offset 360420.
Read lump id: 8. Len: 616395. Offset 606764.
Read lump id: 9. Len: 60544. Offset 434060.
Read lump id: 10. Len: 33096. Offset 168444.
Read lump id: 11. Len: 9118. Offset 494604.
Read lump id: 12. Len: 34520. Offset 571412.
Read lump id: 13. Len: 67688. Offset 503724.
Read lump id: 14. Len: 832. Offset 605932.
WARNING: Unrecognized type body (line 3227) in FGD halflife_2022_op4
Generated 158 point entities cubes
(CRC "232076952")
Saving CRC key to Worldspawn
Loading WAD E:\SteamLibrary\steamapps\common\Sven Co-op\svencoop\halflife.wad
Loading WAD E:\SteamLibrary\steamapps\common\Sven Co-op\svencoop\decals.wad
Loading WAD E:\SteamLibrary\steamapps\common\Sven Co-op\svencoop\xeno.wad
Missing WAD: sample.wad
Loaded 77 embedded textures
Used 1 wad files(include map file)
Calculating lightmaps
Fit 3682 lightmaps into 1 atlases
```

**Comment by Qwertyus3D** [comment]
По поводу ошибки FGD, она не может быть связана с вылетом. Т. к. вылет был и без FGD вообще. А так строчка такая:
`@PointClass base(Monster) studio("models/v_tripmine.mdl") body(3) sequence(7) = monster_tripmine : "Active tripmine" `
Это как бы указано, какое body и sequence должны использоваться по дефолту при использовании модели v_tripmine.mdl для размещения на карте. FGD делался с перспективой на редактор с поддержкой моделей. Вроде строчка правильная сама по себе.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D понял ну это можно будет использовать, если я когда-нибудь смогу добавить рендер моделей :) Уже пытался, но не получается, максимум что я смог, это кучу рандомных треугольников нарисовать вместо модели :)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D 
[bspguy.zip](https://github.com/UnrealKaraulov/newbspguy/files/10154156/bspguy.zip)
Вот еще одна дебаг версия, тут уже краш дамп и обработчик исключений сделал :)

Мне нужен log.txt и если появится, то "bspguy____.dmp" файл.

**Comment by Qwertyus3D** [comment]
```
Crash WINAPI_LASTERROR:0. Exception code: C0000005. Exception address: P
Generating minidump at path D:\Games\Xash3D\_Tools_\BSPGuy\bspguy_20221205_123255.dmpCrash WINAPI_LASTERROR:0. Exception code: C0000005. Exception address: P
Generating minidump at path D:\Games\Xash3D\_Tools_\BSPGuy\bspguy_20221205_123255.dmp
```
[bspguy_20221205_123255.zip](https://github.com/UnrealKaraulov/newbspguy/files/10154173/bspguy_20221205_123255.zip)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D краш в драйвере видеокарты видимо у меня драйвер видеокарты как-то обходит ошибку и я краша не вижу.

Я обновление выпустил, может теперь не крашит ? 
https://github.com/UnrealKaraulov/newbspguy/commit/87d78ff9ad5f4f195d079acfac5664b6acd5aa83

**Comment by Qwertyus3D** [comment]
Вылетает, только теперь ещё быстрее :D

**Comment by Qwertyus3D** [comment]
Я как бы карту в процессе загрузки вижу, энтити на ней отображаются тоже, виджеты. Нет такого, чтобы видеоподсистема не срабатывала. Не уверен, что проблема в драйвере. Ошибка ведь появилась после ["добавил в дебаг вывод информации о текстурах](https://github.com/UnrealKaraulov/newbspguy/issues/31#issuecomment-1336169344). Хотя, если у тебя не крашится, то тоже непонятно.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D  как на счет этой [bspguy.zip](https://githu.com/UnrealKaraulov/newbspguy/files/10154593/bspguy.zip)
 , dmp файлы и log.txt надо :) возможно щас более полная будет информация о краше.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я как бы изменения вернул, не знаю крашить может только окно debug если оно сразу появляется

**Comment by Qwertyus3D** [comment]
Ппц ссылка, "githu.com не позволяет установить соединение." Никак не мог понять, почму страница не открывается.

**Comment by Qwertyus3D** [comment]
Ошибки всё те же
```
Crash
 WINAPI_LASTERROR:0.
 Exception code: C0000005.
 Exception address: 00007FF9AB06C9C9.
 Main module address: 00007FF7DA570000
Generating minidump at path D:\Games\Xash3D\_Tools_\BSPGuy\bspguy_20221205_134921(2).dmp
Crash
 WINAPI_LASTERROR:0.
 Exception code: C0000005.
 Exception address: 00007FF9AB06C9C9.
 Main module address: 00007FF7DA570000
Generating minidump at path D:\Games\Xash3D\_Tools_\BSPGuy\bspguy_20221205_134921(1).dmp
```
[BSPGuyDump.zip](https://github.com/UnrealKaraulov/newbspguy/files/10154704/BSPGuyDump.zip)

**Comment by Qwertyus3D** [comment]
Попробовал убрать виджет Debug с экрана (висел свёрнутым), не помогло.

**Comment by Qwertyus3D** [comment]
Кстати, без карты ведь программа вообще не запускается. Если просто по exe щёлкнуть. Когда-то давно я из-за этого решил, что она вообще не рабочая, и никак не мог понять, в чём дело.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я слегка не туда вставил textureLoaded = false, из-за чего могло крашить.

https://github.com/UnrealKaraulov/newbspguy/commit/31ba604e56afe4c3b7c15ae6a60612d4774fde41 перестал крашить?

**Comment by Qwertyus3D** [comment]
Проверил 2 билда, оба крашат.

**Comment by Qwertyus3D** [comment]
> Самому даже интересно как сделать что бы отображались и worldpawn.
> 
> [771e327](https://github.com/UnrealKaraulov/newbspguy/commit/771e3272709679fc0ffa5bd9f169f366ba548df1)

Думаю, надо Дядю Мишу спрашивать, кроме него мало кто ответит, какая информация остаётся в карте после компиляции.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D информации предостаточно, но вопрос в том как научиться ее использовать:)

На счёт краша если открыть пустую карту(просто bspguy.exe запустить), то не крашит? Если потом создать bsp модель, сразу краш?

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D нет возможности скачать Visual Studio 2022 ?) Там было бы видно откуда краш произошел(открыть проект, выбрать debug, в свойствах проекта bspguy ввести в вкладке "отладка" путь к любой карте в аргументы вместо того что там и нажать запустить отладку :)

**Comment by UnrealKaraulov** [comment]
В общем завтра отменю изменения переделаю вывод списка wad, или есть ещё предположение где могло бы крашить, сегодня на работе до утра

**Comment by Qwertyus3D** [comment]
Visual Studio 2022... И сколько гигов хлама придётся поставить? :)

**Comment by Qwertyus3D** [comment]
У меня какая-то версия стоит вообще-то, но у меня нет опыта, что там нужно использовать.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D хлама много)) ладно я завтра буду разбираться, возможно придётся вставить свою geforce видеокарту старую что бы баг поймать)

**Comment by Qwertyus3D** [comment]
> На счёт краша если открыть пустую карту(просто bspguy.exe запустить), то не крашит? Если потом создать bsp модель, сразу краш?

Эм, так у меня программа вообще никогда без карты не запускалась сроду. Она всегда на долю секунды мигает окном, и всё. Я могу её только путём клика на файле с нужной картой открыть, больше никак.

**Comment by Qwertyus3D** [comment]
Там мелькает какое-то консольное окно, скорее всего, со справкой по использованию командной строки, большего разглядеть невозможно.

**Comment by Qwertyus3D** [comment]
[BSPGuyInfo.zip](https://github.com/UnrealKaraulov/newbspguy/files/10156562/BSPGuyInfo.zip)
Может это поможет? Файлики, которые поячвились после запуска прог glewinfo.exe и visualinfo.exe.

**Comment by Qwertyus3D** [comment]
Хах, хотя сейчас порылся и нашёл пару версий старых, которые открываются без карты.

**Comment by Qwertyus3D** [comment]
В общем, реально, старые билды показывают окно без карты, вот этот последний рабочий у меня:
[Fix main command line / help](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3487778551)
Те, что позже, открывать редактор перестают.

**Comment by Qwertyus3D** [comment]
И ещё, программа где-то дополнительно хранит файл конфигурации, кроме папки с самой программой. Я убрал оттуда все конфиги, а она всё равно подгружает откуда-то настройки, ничего не понимаю.

**Comment by Qwertyus3D** [comment]
Ага, видимо, тут: C:\Users\...\AppData\Roaming\bspguy

**Comment by Qwertyus3D** [comment]
Хм, оказалось, последний билд тоже открывает окно программы. Но при загрузке карты вылет. Теперь уже тестировал, удалив все настройки.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D да я делал для удобства потом случайно убрал, ну так как для ImGui существует файловый браузер, то грех было им не воспользоваться)) 
То есть по умолчанию должен редактор открываться, с пустой картой (которая доступна для редактирования, хотя я не пробовал создавать карту через создание bsp моделей, это уже какое-то извращение получится :) )))

@Qwertyus3D я примерно понимаю откуда мог бы взяться краш, завтра верну async загрузку текстур, я ее убрал только из-за того что крашилось при работе с std::map из другого потока.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D последний билд все еще крашится или наконец то перестал ? 

https://github.com/UnrealKaraulov/newbspguy/commit/4ff3b7361d263b7f74039a46144ac5006fe1dc0d

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Заработал, родимый :D

**Comment by Qwertyus3D** [comment]
Напоминаю про опечатку https://github.com/UnrealKaraulov/newbspguy/issues/31#issuecomment-1336390855

И по поводу списка текстур по WAD, добавить бы туда пункт, который бы показывал список текстур, которые не найдены в подключенных WAD. Т. е. допустим, если нужные WAD вообще не подключены, то туда выводится весь список текстур карты. А когда подключены, то отдельным списком не найденные текстуры.

**Comment by Qwertyus3D** [comment]
И я так понял, текстуры из decals.wad учитываются, как использованные, но не отображаются.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D добавил вывод не найденных текстур и опечатку 

на счет decals.wad немного не понял :(

**Comment by Qwertyus3D** [comment]
Ну практически любую карту ХЛ открыть, текстур в ней использовано больше, чем сумма текстур в загруженных WAD. При этом файл decals.wad в списке текстур не отображается. Видимо, потому, что сам редактор его не подгружает. Текстуры в infodecal считает, но т. к. фактически их не отрисовывает, то и пропускает в списке WAD.
![dec](https://user-images.githubusercontent.com/98685264/205889585-443436ab-b126-40ea-8ba5-b8c2e8a83095.jpg)

**Comment by Qwertyus3D** [comment]
Можно сделать тогда, например, пункт infodecal, по имени энтити, и туда выводить список деколей карты.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D аа, эти текстуры их нет в карте. Сделаю отдельно как-нибудь :)

**Comment by Qwertyus3D** [comment]
Ну, как нет. В infodecal прописаны, значит есть :)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D в самой карте нет, они только прописаны в этих сущностях, программа не читает их и не рисует
ну то есть не поддерживает на данный момент

**Comment by Qwertyus3D** [comment]
Ну, я и имел в виду, что сделать парсинг имён текстур из infodecal карты и добавить в список, для полноты.

**Comment by UnrealKaraulov** [comment]
Добавил в DEBUG окно "decals.wad" со списком используемых текстур

**Comment by UnrealKaraulov** [comment]
Закрываю пока что, если нет вопросов

**Comment by Qwertyus3D** [comment]
Спасибо, теперь полный функционал!
