### ISSUE TITLE
Saving a map with .BSP extension

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#32]
Продолжение проблемы, когда карта не открывалась, если расширение файла было с заглавными буквами. Теперь выходит, что при сохранении такой карты (MAP.BSP, к примеру) программа не перезаписывает файл, а сохраняет его в виде MAP.BSP.bsp. Т. е. дописывает расширение маленькими буквами.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D удалил код отвечающий за это поведение https://github.com/UnrealKaraulov/newbspguy/commit/2fd48a3ae13a440ecee2908237bbeb534abe65d7 , должно помочь

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Да, помогло.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D хорошо, у меня так часто бывает какой-то непонятный код непонятно для чего пишу а потом стираю его же :)
