### ISSUE TITLE
Raw edit bug on removing keys

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#34]
Допустим, имеем такую энтить:
```
{
"origin" "1792 1360 296"
"model" "sprites/flare1.spr"
"rendercolor" "0 0 0"
"renderamt" "70"
"rendermode" "3"
"renderfx" "0"
"angle" "286"
"classname" "env_glow"
}
```
Открываем режим Raw edit и пытаемся удалить строчку "renderamt" "70" с помощью кнопки **Х** напротив. Строчка удаляется, но:
1. Значение 70 по-прежнему остаётся действующим при просмотре настроек через раздел Attributes. Т. е. по факту эта строчка не удалилась.
2. Идущая ниже строчка "rendermode" "3" обнуляет своё значение, что также подтверждается и при просмотре Attributes. Т. е. нажатие на **X** затирает значение в следующей строке, а не в той, напротив которой она стоит.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D кажется исправил. Но такой дичи я еще никогда не встречал :)

Выполнение строки ```std::find(keyOrder.begin(), keyOrder.end(), key)``` в функции ```removeKeyvalue``` подменяло значение key на рандомное )))

**Comment by UnrealKaraulov** [comment]
https://github.com/UnrealKaraulov/newbspguy/commit/a42e4ed4573c177d70d5f12b3e5c1c05c82e6a14
