### ISSUE TITLE
Transparency for solid entities

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#35]
Небольшое улучшение в виде отдельной опции в разделе Render flags - для энтити со значением SOLID (rendermode 4) не отрисовывать синий фон-заливку, чтобы они выглядели так же, как в игре, с прозрачностью. Для лестниц, решёток, кустиков и т. д.

**Comment by Qwertyus3D** [comment]
В идеале бы, учитывать значение renderamt у энтить (0-255), если выбран любой режим rendermode, кроме Normal (0). Потому что во всех остальных режимах прозрачность учитывается. Единственная особенность для спрайтов, это что если выбран режим Color (1), то любое значение, кроме 0, просто делает энтить видимой, а 0 - невидимой. Но прозрачность должна касаться текстур, сам каркас энтити должен быть видим, конечно.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D  Ну... Мне пришлось узнать что такое шейдеры, и вроде как получается, думаю к вечеру сделаю обнову :)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал что-то, работать должно кое-как :)

Работает?

**Comment by Qwertyus3D** [comment]
Да, кое-как - работает. В том плане, что прозрачность подключилась, хотя она не 100%-ная (в случае, когда renderamt 0). Текстуры всё-же видно. Может, это даже неплохо. Стёкла прозрачные, уже хорошо. Главный вопрос, что транспарентные текстуры (типа тех, что с синим фоном) лишь немного прозрачны. Синий этот фон виден, как мелкая сетка, которая лишь немного прозрачная. А нужно бы, чтобы пиксели определённого цвета (последний цвет в текстуре, вроде) вообще были невидимы.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D Opengl сглаживает текстуры, по этому по краям синий цвет не особо синий.

**Comment by Qwertyus3D** [comment]
И если renderamt 0 явно не указан в свойствах энтити, то программа считает, что энтить должна быть видима. Но это неверно, т. к. когда renderamt не задан явно, он по умолчанию равен 0. И для любого другого указанного режима, кроме Normal (0), такая энтить должна быть невидимой.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D 
Но если полную прозрачность сделать, то объекты станут полностью прозрачными, и не видимыми в программе 

Добавил 0 renderamt если не указан

**Comment by Qwertyus3D** [comment]
> @Qwertyus3D Opengl сглаживает текстуры, по этому по краям синий цвет не особо синий.

У меня не с краями проблема, у меня весь синий фон плющит. В зависимости от угла зрения текстура может быть или вообще непрозрачной, или полосисто-прозрачной.

**Comment by UnrealKaraulov** [comment]
Можно пример карты я посмотрю

**Comment by Qwertyus3D** [comment]
![blue256](https://user-images.githubusercontent.com/98685264/208424180-53635a32-2c5a-4760-a904-7160d5135ee2.jpg)
Это пример максимальной прозрачности, скажем так.

**Comment by Qwertyus3D** [comment]
На любой карте, где есть подобные текстуры.

**Comment by Qwertyus3D** [comment]
![blue257](https://user-images.githubusercontent.com/98685264/208424522-7eb78194-52e9-426f-8325-41175187c213.jpg)
Прозрачность "плавает" при поворотах камеры от мелкой синей сетки до совсем непрозрачных участков.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D ну это сглаживание, я убрал сглаживание, должно быть лучше, позже я сделаю что бы лучше работала прозрачность. (конвертировать текстуру в RGBA)

В последнем билде нормально отображается?

**Comment by Qwertyus3D** [comment]
Теперь просто нет сглаживания, но синяя сетка осталась.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D 
У меня без сглаживания так:
![image](https://user-images.githubusercontent.com/88730285/208426374-8322950c-0d48-4757-9479-04404ce470fc.png)
Со сглаживанием:
![image](https://user-images.githubusercontent.com/88730285/208426506-9d184f1e-40eb-4ea3-b1ca-fcca20df7499.png)

**Comment by Qwertyus3D** [comment]
Нет, у меня так же, как на скринах выше. А если объект выделен, то это сетка - чёрная. Только если до этого текстура сглаживалась, то сейчас она пикселизованная. 
![black256](https://user-images.githubusercontent.com/98685264/208427016-e43cdf04-2922-4afe-90a6-452c833330ec.jpg)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я честно не знаю ни одной ХЛ карты, и где найти эти кусты) наугад потыкал не нашел таких ))) Можно конкретно название карты ?)

**Comment by Qwertyus3D** [comment]
Я так думаю, возможно, программа ещё бэкфейсы пытается отрисовывать. А движок игры рисует только переднюю текстуру. с2a5 карта.

**Comment by Qwertyus3D** [comment]
Карта роли не играет, я думаю. Видимо, шейдер опять привязан к видеокарте.

**Comment by UnrealKaraulov** [comment]
> Карта роли не играет, я думаю. Видимо, шейдер опять привязан к видеокарте.

ну как бы если я не увижу это место как я смогу исправить ошибку)

**Comment by Qwertyus3D** [comment]
Так у меня с любой транспарентной текстурой косяк одинаковый, неважно, трава это, забор, лестница или ограда.

**Comment by Qwertyus3D** [comment]
Ещё забавный факт, что стекло прозрачно, но точечные энтити сквозь него не видно, только браши.

**Comment by Qwertyus3D** [comment]
Это видно сквозь стекло:
![Glass1](https://user-images.githubusercontent.com/98685264/208433177-976cf2e8-e3e4-4f93-959e-451fe5a76d6b.jpg)
А это - за ним:
![Glass2](https://user-images.githubusercontent.com/98685264/208433229-299110fc-85bc-4bb7-969a-6829c8377e12.jpg)
Карта as_a1.

**Comment by Qwertyus3D** [comment]
Даже не все браши видно.

**Comment by Qwertyus3D** [comment]
Теперь работает. Но другие энтити сквозь эту прозрачность не видны, только геометрия с непрозрачными текстурами.
![rgba](https://user-images.githubusercontent.com/98685264/208454726-e5452340-1f23-43da-93eb-6de2ffc79f7b.jpg)

**Comment by Qwertyus3D** [comment]
И напомню, что синий цвет - это наиболее используемый вариант. А так цвет фона может быть любым, т. к. прозрачный цвет задаётся в палитре текстуры. Надеюсь, это учитывается.

**Comment by Qwertyus3D** [comment]
И на всякий случай не помешает опция в настройках рендера, для включения-выключения рендермодов текстур.

**Comment by UnrealKaraulov** [comment]
> И напомню, что синий цвет - это наиболее используемый вариант. А так цвет фона может быть любым, т. к. прозрачный цвет задаётся в палитре текстуры. Надеюсь, это учитывается.

Цвет фона может быть в спрайтах другой, в wad ведь только синий?

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D Вроде бы в SPRITE берется первый цвет из палитры а в WAD только синий? Разве не так?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov В спрайтах не помню. как устроено (особенно со многокадровыми), там как-то в сам спрайт, видимо, пишется инфа о прозрачном цвете. Точно не первый. В текстурах (что вады, что модели) для транспарентности берётся последний цвет палитры. Он может быть любым. Синий используют для удобства, но на деле любой цвет в ячейке 255. Причём, там, по сути не важен даже цвет. В палитре могут быть повторения по цвету. Но прозрачными будут читаться те пикселы, которые проиндексированы на ячейку 255. Тот же синий цвет отдельных пикселов может быть непрозрачным, если эти пикселы нарисованы синим цветом из другой ячейки.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D так на счет объектов за прозрачными текстурами, кажется пофиксил, не уверен но вроде бы лучше стало

**Comment by Qwertyus3D** [comment]
Вообще никакой разницы. :D

**Comment by Qwertyus3D** [comment]
Тут нужна сортировка по прозрачности. Наверное, можно даже в исходниках Ксаша подсмотреть, но не уверен, что прямо оттуда утянуть выйдет.

**Comment by Qwertyus3D** [comment]
А, ой. Есть разница. Для стёкол! Я не нашёл сразу. Теперь то же самое нужно не для полупрозрачности, а для транспарентности сделать.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Со стёклами работает 👍 Теперь решётки/лесенки.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D добавил в этот список все что с текстурами '{' 

В общем там как-то все сложно, в 2 этапа рисуется карта, сначала прозрачные потом непрозрачные объекты, добавил в прозрачные те которые идут с текстурой '{'

Должно теперь нормально работать.

**Comment by Qwertyus3D** [comment]
Краш

**Comment by UnrealKaraulov** [comment]
Уже завтра вечером тогда исправлю,после работы.

Я на нескольких картах проверял вроде как не крашилось.

**Comment by Qwertyus3D** [comment]
Странная симптоматика, но дебаг-компил просто закрывается после запуска. Краша как бы и нет.
```
Поток 0x63ac завершился с кодом 0 (0x0).
"bspguy.exe" (Win32). Загружено "C:\Windows\System32\SHCore.dll". 
"bspguy.exe" (Win32). Загружено "C:\Windows\System32\kernel.appcore.dll". 
Поток 0x4e20 завершился с кодом 0 (0x0).
Поток 0x16c8 завершился с кодом 0 (0x0).
Программа "[4724] bspguy.exe" завершилась с кодом 0 (0x0).
```

**Comment by Qwertyus3D** [comment]
И как бы без карты оно запускается. Но при попытке открыть карту вылетает.

**Comment by Qwertyus3D** [comment]
Упс, крашит именно на той карте, as_a1.

**Comment by Qwertyus3D** [comment]
```
Start bspguy editor with map: D:\Games\Xash3D\Ashfield\maps\as_a1.bsp
Load settings from : D:\Games\Xash3D\_Tools_\BSPGuy/bspguy.cfg
Parsing D:\Games\Xash3D\_Tools_\BSPGuy//_Res_/fgd/halflife_2022_op4.fgd
Bsp version: 30
Read lump id: 0. Len: 105152. Offset 124.
Read lump id: 1. Len: 144120. Offset 105276.
Read lump id: 2. Len: 6344. Offset 249396.
Read lump id: 3. Len: 242784. Offset 255740.
Read lump id: 4. Len: 227142. Offset 498524.
Read lump id: 5. Len: 210024. Offset 725666.
Read lump id: 6. Len: 229160. Offset 935690.
Read lump id: 7. Len: 283300. Offset 1164850.
Read lump id: 8. Len: 2319261. Offset 1448150.
Read lump id: 9. Len: 129840. Offset 3767411.
Read lump id: 10. Len: 167020. Offset 3897251.
Read lump id: 11. Len: 39674. Offset 4064271.
Read lump id: 12. Len: 141396. Offset 4103945.
Read lump id: 13. Len: 264716. Offset 4245341.
Read lump id: 14. Len: 20032. Offset 4510057.
WARNING: Unrecognized type body (line 3317) in FGD halflife_2022_op4
Generated 159 point entities cubes
(CRC "1578850597")
Warning: in map as_a1 found unused model: 191.
Crash
 WINAPI_LASTERROR:B7.
 Exception code: C0000005.
 Exception address: 00000000104CB885.
 Main module address: 0000000010000000
Generating minidump at path D:\Games\Xash3D\_Tools_\BSPGuy\bspguy_20221219_193436(2).dmp
Crash
 WINAPI_LASTERROR:0.
 Exception code: C0000005.
 Exception address: 00000000104CB885.
 Main module address: 0000000010000000
Generating minidump at path D:\Games\Xash3D\_Tools_\BSPGuy\bspguy_20221219_193436(1).dmp
Start bspguy editor with map: D:\Games\Steam\steamapps\common\Half-Life\valve\maps\c2a3e.bsp
Load settings from : D:\Games\Xash3D\_Tools_\BSPGuy/bspguy.cfg
Parsing D:\Games\Xash3D\_Tools_\BSPGuy//_Res_/fgd/halflife_2022_op4.fgd
Bsp version: 30
Read lump id: 0. Len: 15317. Offset 873940.
Read lump id: 1. Len: 97720. Offset 124.
Read lump id: 2. Len: 2600. Offset 889260.
Read lump id: 3. Len: 44508. Offset 122204.
Read lump id: 4. Len: 2782. Offset 871156.
Read lump id: 5. Len: 29784. Offset 166712.
Read lump id: 6. Len: 10640. Offset 196496.
Read lump id: 7. Len: 55840. Offset 207136.
Read lump id: 8. Len: 486033. Offset 385120.
Read lump id: 9. Len: 34496. Offset 262976.
Read lump id: 10. Len: 24360. Offset 97844.
Read lump id: 11. Len: 7468. Offset 297472.
Read lump id: 12. Len: 27180. Offset 355316.
Read lump id: 13. Len: 50376. Offset 304940.
Read lump id: 14. Len: 2624. Offset 382496.
WARNING: Unrecognized type body (line 3317) in FGD halflife_2022_op4
(CRC "3581799585")
Saving CRC key to Worldspawn
Calculating lightmaps
Loading WAD D:/Games/FWGS/valve/decals.wad
Loading WAD D:/Games/FWGS/valve/halflife.wad
Loading WAD D:/Games/FWGS/valve/liquids.wad
Loading WAD D:/Games/FWGS/valve/xeno.wad
Loaded 59 wad textures
Fit 2618 lightmaps into 1 atlases
Generated 159 point entities cubes
Loading WAD D:/Games/FWGS/valve/decals.wad
Loading WAD D:/Games/FWGS/valve/halflife.wad
Loading WAD D:/Games/FWGS/valve/liquids.wad
Loading WAD D:/Games/FWGS/valve/xeno.wad
Loaded 59 wad textures
Debug: Used 2 wad files(include map file)
Loaded 2440 clipnode leaves
adios
```

[BSPGuy.zip](https://github.com/UnrealKaraulov/newbspguy/files/10262174/BSPGuy.zip)

**Comment by Qwertyus3D** [comment]
Там, где не крашит, энтити стали видны сквозь решётки.

**Comment by Qwertyus3D** [comment]
И почему-то de_dust2 не открывает дебажный компил, как обычно (имею в виду, тот компил, который Студия создаёт).

**Comment by UnrealKaraulov** [comment]
понял, я там мелкую ошибку допустил и если на карте есть неиспользуемая модель то крашит ее

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D а через студию не получается запустить отладку? Там по идее должно написать строку кода где ошибка

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov 

> дебаг-компил просто закрывается после запуска

Нет ошибки, только консольное сообщение о том, что программа закрылась.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D исправил краш

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Теперь работает, но в отдельных случаях остался эффект. что энтить с прозрачностью не видна сквозь перекрывающую её прозрачную текстуру.

**Comment by Qwertyus3D** [comment]
И остался вопрос https://github.com/UnrealKaraulov/newbspguy/issues/54

**Comment by UnrealKaraulov** [comment]
> @UnrealKaraulov Теперь работает, но в отдельных случаях остался эффект. что энтить с прозрачностью не видна сквозь перекрывающую её прозрачную текстуру.

@Qwertyus3D еще есть эта проблема? Если да то на какой карте, я посмотрю.

**Comment by Qwertyus3D** [comment]
Да повсеместно можно увидеть. с2а5, например.
![tran1](https://user-images.githubusercontent.com/98685264/210134409-769daeff-1275-49b5-8caa-58dc88f3cd2b.jpg)
![tran2](https://user-images.githubusercontent.com/98685264/210134411-2a4b40da-a325-463b-8c38-a29a3b378dca.jpg)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D спасибо за примеры, посмотрю почему так.

**Comment by Qwertyus3D** [comment]
Можно ли добавить опцию, делающую "кубики" точечных энтить полупрозрачными? Список прозрачных энтить на них не влияет, они всё равно непрозрачные. Да и в целом было бы удобно иметь возможность регулировать их отрисовку по одной галочке. Т. к. точечные энтити, если это не модели или спрайты, то в игре вообще невидимые. А в редакторе будет удобно рисовать их полупрозрачными для манипуляций с соседними энтитями.

И ещё можно было бы для списка полупрозрачных брашевых энтить сделать поддержку маски названия. типа trigger_, чтоб сразу все триггеры делать полупрозрачными, а не раздувать список.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D нужно как-то менять видно функцию рендера, в opengl нужно сначала рисовать непрозрачные, затем прозрачные в порядке удаления от камеры

```// Pseudo code
void Renderer::renderLoop() {
    // 1. Render opaque objects
    for (auto& object : opaqueObjects) {
        render(object);
    }

    // 2. Sort transparent objects based on distance from camera
    std::sort(transparentObjects.begin(), transparentObjects.end(), [&](const Object& a, const Object& b) {
        float distA = distance(cameraPosition, a.position);
        float distB = distance(cameraPosition, b.position);
        return distA > distB;
    });

    // 3. Render transparent objects back-to-front
    for (auto& object : transparentObjects) {
        render(object);
    }
}```

пока не вкурсе как это сделать правильно :(

**Comment by KarKarKarKarkarkar** [comment]
Я сделал сортировку и это работало, но жрет все ресурсы, каждый кадр сортировать список сущностей по дистанции от камеры, это казалось бы очень легкая задача у меня снизило ФПС до 10 на достаточно неплохом ПК

**Comment by Qwertyus3D** [comment]
Печально. А как насчёт поддержки рендера спрайтов, хотя бы с прозрачным фоном? Или текстур с прозрачным фоном на моделях? На брашевых энтитях прозрачный фон ведь поддерживается уже.

**Comment by KarKarKarKarkarkar** [comment]
> Печально. А как насчёт поддержки рендера спрайтов, хотя бы с прозрачным фоном? Или текстур с прозрачным фоном на моделях? На брашевых энтитях прозрачный фон ведь поддерживается уже.

Да это можно, но опять возникнет проблема перекрытия части прозрачных объектов за ними, сделаю, но вероятно прозрачность сделаю опцией в рендер настройках. 

Был бы человек разбирающийся в шейдерах и рендере, можно было бы перенести на другой рендер который не содержит таких косяков с отображением прозрачности, ну или хотя бы сортировку моделей по расстоянию от камеры, что бы не садило ФПС в ноль. Хотя я еще завтра поковыряюсь, по идее еще текстура неба не должна перекрывать все другие прозрачные объекты, но я не помню каким образом она отрисовывается, если найду то для нее порядок рендера тоже надо изменить что бы другие прозрачные объекты были видны за ней.

В общем тупость opengl мешает, и вроде как стандартными средствами прозрачность не пофиксить. Не знаю как в goldsrc рендер opengl работает адекватно, возможно надо там подсмотреть что-нибудь.

**Comment by Qwertyus3D** [comment]
В исходниках Ксаш-движка можно смотреть, как всё настроено. А в Ксашмоде рендер ещё более продвинутый.

**Comment by KarKarKarKarkarkar** [comment]
@Qwertyus3D сортировка по дальности кстати даже если добавить то работает частично, если объект из нескольких прозрачных частей, то они перекрывают друг друга, например деревья на карте cs_estate из двух прозрачных частей, и если смотреть сквозь одну, то она перекрывает остальную часть. В общем программа изначально не была предназначена для этого

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я в рендере не разобрался, но вроде как с альфатестом стало намного лучше, хотя бы часть прозрачных объектов не перекрывает другие. (ну там к примеру деревья на cs_estate теперь не перекрывают друг друга и полупрозрачные объекты, т.к там 100% прозрачность) щас еще проверю и загружу обнову

**Comment by Qwertyus3D** [comment]
Да, вижу, что сортировка улучшилась.

**Comment by UnrealKaraulov** [comment]
> Да, вижу, что сортировка улучшилась.

Если заменить стандартные текстуры (SKY,TRIGGER и т.п) более прозрачными вариантами, то через alphatest через них тоже будет нормально видно, подумаю над этим. Не получается сделать сортировку объектов для рендера потому что они привязаны к ID сущностей, типа 

renderEnt[id] = ents[id]

Можно будет потом поковырять, в принципе возможно добавить сортировку но надо будет часть кода переписывать, а это мне пока лень)))

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D убрал гору ненужного кода связанного с шейдерами, обновил шейдеры для моделей, и добавил поддержку прозрачных текстур в .MDL, теперь модели с прозрачностью тоже должны отображаться нормально.

**Comment by Qwertyus3D** [comment]
Вообще, под прозрачными текстурами следует скорее понимать аддитивные текстуры, а текстуры с прозрачным фоном скорее лучше называть транспарентными. Транспарентные текстуры вижу, что заработали, спасибо, полезная обнова (думал намутить с её помощью комплект служебных моделек под отображение разных энтить). Хром и аддитив пока нет.

**Comment by UnrealKaraulov** [comment]
В последнем билде фпс должен стать намного больше. Случайно нашел места в коде которые вызывали сильную нагрузку на процессор.

**Comment by Qwertyus3D** [comment]
Ну, это, если аддитив и хром (кстати, на брашах тоже может быть хром, но точно не знаю, как это работает) не планируются, то можно было бы закрыть, наверное. По поводу производительности сложно сказать, что изменилось (иногда при быстром движении через карту небольшие лаги мелькают), но транспарентность вроде как реализована. Разве что декали и спрайты ещё остаются...

**Comment by SirYodaJedi** [comment]
Reading through a google translation of this thread, I didn't see this mentioned, so I thought I'd clarify:

Index # 255 (the last color in the palette) is always converted to black by the engine for textures with the `{` prefix, regardless of if the texture is being rendered as transparent or translucent. This is why there isn't a blue (or whatever color 255 is) highlight around transparency in-game when texture filtering is enabled.

(I tried to word the above in a way that Google Translate shouldn't mangle it; I don't speak Cyrillic, so I'm sorry for being that annoying American that speaks English in a foreign land 😅.)

**Comment by UnrealKaraulov** [comment]
Не знаю как правильно реализовать сортировку без потери фпс, по этому я оставляю все как есть.

@SirYodaJedi в новых версиях используется 255 или же принудительно синий.
