### ISSUE TITLE
Broken Pitch rendering

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#36]
Программа некорректно отрисовывает angles. А именно, поворот по Pitch не учитывает значения Yaw. Независимо от поворота по Yaw Pitch всегда наклоняет энтить в одном направлении. Т. е., например, при Yaw 90 поворот по Pitch визуально суммируется со значением Roll (т. е. как бы тоже крутит по оси Roll). При Yaw 180 поворот по Pitch наклоняет объект в противоположном направлении относительно правильного. При Yaw 270 значение Pitch визуально вычитается из значения Roll (т. е. как бы крутит по той же оси, но в противоположном направлении). Т. е. только когда Yaw = 0, тогда поворот по Pitch корректный.

**Comment by Qwertyus3D** [comment]
Баг присутствовал и в старых версиях программы (когда ещё только angles поддерживалось, и отрисовка углов работала только при выделении энтити).

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D можно пример ?

Я когда делал, есть различные ентити у которых некоторые значения тупо не поддерживаются, их игнорит поворот или частично игнорит. Надо смотреть совпадает ли координаты и визуально в игре.

**Comment by Qwertyus3D** [comment]
Согласен, есть энтити, поворот которых по определённой оси не поддерживается. Но тогда они и не должны поворачиваться по указанной оси совсем. А если поворот действует, то он должен работать корректно. А он работает, но некорректно. Можно просто любую энтить с angles посмотреть и убедиться в этом. Если нужен конкретный пример, то я обнаружил это на примере трупа учёного на с2а5, который лежит на камне под дамбой. В игре указанные значения поворачивают энтить так, как нужно (-8 по Y выравнивает положение тела относительно склона камня, подошвами ног вниз). А в BSPGuy отображается неверное направление (выглядит так, как будто левая сторона модели будет задрана вверх). При значениях -8 90 0 визуально происходит вращение по Х, а не по Y, из-за того, что модель развёрнута на 90 градусов по Z. Но по оси X модель продолжает поворачиваться так, как если бы поворота по Z не было.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D В движке может быть жестко закодированные значения типа -1 -2 (повернут вверх, повернут вниз), это зависит от движка, я не знаю всех вариантов

**Comment by Qwertyus3D** [comment]
Это не то. Там именно угол. И это происходит с любой энтитью. Любая энтить даёт наклон по Y в фиксированном направлении. Вокруг своей оси разрешено поворачивать все энтити, кроме спрайтов (для них не актуален поворот вокруг вертикальной оси, т. к. спрайт всегда смотрит на игрока). Pitch должен раскачивать модель влево-вправо в зависимости от того, какой поворот модель получает вокруг своей оси. А в программе поворот по Pitch имеет строго фиксированное направление, как ни крути модель вокруг оси. Просто всегда в одну и ту же сторону наклон.

**Comment by Qwertyus3D** [comment]
Если совсем тупо объяснять, то Pitch в программе визуально наклоняет любую модель относительно глобальной оси координат. Как если бы был предусмотрен наклон только в одном направлении.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я не знаю где на каких картах кто находится тем более трупы ученых каких-то)

можно конкретный пример на какой карте, какая entity работает не так как должна?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Да я же писал выше:
1. `Если нужен конкретный пример, то я обнаружил это на примере трупа учёного на с2а5, который лежит на камне под дамбой.`
2. `И это происходит с любой энтитью. Любая энтить даёт наклон по Y в фиксированном направлении.`

Т. е. любую энтить можно взять и попробовать прописать ей разные значения angles. Первое значение из трёх 0 0 0 - это и есть Pitch. И он любую энтить в редакторе наклонит строго в одном и том же направлении, какие значения не задавай для Yaw и Roll.

Я себе сделал FGD, который учитывает реальные размеры моделей в игре, с ним тело учёного в редакторе выглядит так: 
![c2guy](https://user-images.githubusercontent.com/98685264/204004786-08233994-e3b7-4415-9ae9-93a9e2821ee1.jpg)

Там угол по Pitch -8 задан, а в редакторе это выглядит, как будто модель приподнята по Roll. Левая сторона приподнята вверх, вместо того, что должна быть нижняя часть (со стороны направляющей) опущена вниз.

В игре всё выглядит, как положено (немного не идеально, но правильно в целом):
![c2map](https://user-images.githubusercontent.com/98685264/204005902-a0fd066d-056e-4487-8779-b406c67849b7.jpg)
Тело лежит вдоль склона, левая сторона не задрана.

Повторюсь, дело вообще не в этой модели. Любую энтить можно попробовать крутить в редакторе, и с любой энтитью будет то же самое. Pitch будет игнорировать то, на какой угол энтить повёрнута по Yaw и Roll. И будет наклонять всегда в одну и ту же сторону.

**Comment by UnrealKaraulov** [comment]
Понятно просто я вроде как проверял с брашевыми ентити проблем не было. Ну попробую изменить вариант поворота матрицы, взял щас несколько из GLM исходникам

**Comment by UnrealKaraulov** [comment]
![image](https://user-images.githubusercontent.com/88730285/204041871-50ab0479-839a-4e4d-ac4a-91ade6a3c501.png)
![image](https://user-images.githubusercontent.com/88730285/204041907-e54e4515-84db-45bb-95b0-51980ed7ac34.png)

Вот пример func_breakable почти 100% совпадение.

**Comment by Qwertyus3D** [comment]
Чтобы увидеть проблему, нужно задать более выраженное значение Yaw. 20 - это маленький угол, из-за чего и возникает иллюзия, что всё нормально. Нужно ставить 90/180/270, тогда будет видно различие. Когда мы поворачиваем энтить на прямой угол, наклон по Pitch должен очевидно происходить в другом направлении. Но этого не происходит. Независимо от Yaw, наклон по Pitch будет в одну и ту же сторону. Я уже не знаю, как ещё объяснить.

**Comment by Qwertyus3D** [comment]
И вообще, зачем вращать то, что вращать не требуется? Зачем вращать func_breakable? У этой энтити вообще не поддерживается angles. Надо вращать те энтити, у которых angles предусмотрены.

**Comment by UnrealKaraulov** [comment]
> И вообще, зачем вращать то, что вращать не требуется? Зачем вращать func_breakable? У этой энтити вообще не поддерживается angles. Надо вращать те энтити, у которых angles предусмотрены.

ну как видно на скрине, поддерживаются

**Comment by Qwertyus3D** [comment]
На скрине видно ANGLES NOT SUPPORTED :D

**Comment by UnrealKaraulov** [comment]
Только **Y** не поддерживается в breakable

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D  вот например значения angles для игрока:
![image](https://user-images.githubusercontent.com/88730285/204049048-35512dff-a601-4d4f-bcae-a44803ff4b0d.png)
![image](https://user-images.githubusercontent.com/88730285/204049063-3fc66dd7-a4f9-4b2f-bf45-b32b62acd7c6.png)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D это значит что не работает что ли?)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D вот все 3 YAW PITCH ROLL выставил

и практически 100% совпадает

![image](https://user-images.githubusercontent.com/88730285/204049398-fd8c064f-ef77-4246-bb7c-12ff14068fea.png)
![image](https://user-images.githubusercontent.com/88730285/204049415-c49bc554-3249-46ba-86ab-f5e437c349ab.png)

**Comment by Qwertyus3D** [comment]
"Работает" и "работает правильно" - это 2 разные вещи. Проверить на энтите, которая полноценно поддерживает angles, что мешает? И задать угол 90/180/270 по Yaw? А по Pitch 45. Я пытаюсь объяснить, как проверять, это же не просто так я писал. Смотреть надо не на то, наклоняется энтить или нет, а как она наклоняется в зависимости от заданного значения Yaw.

**Comment by Qwertyus3D** [comment]
Для этого даже в игру не нужно лезть. Прямо в самой программе видно, что наклон по Pitch относительно выбранного значения Yaw неверный.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D так я же кидаю скрины, info_player_start, все значения ставлю и в игре сущность наклонена именно под таким углом как и в редакторе.

почему-то в rotate надо -pitch тогда работает как на скрине

**Comment by Qwertyus3D** [comment]
Вот энтить лежит без поворотов 0 0 0:
![0 0 0](https://user-images.githubusercontent.com/98685264/204050359-2092477f-35db-4209-855c-eb08f9e9dc7d.jpg)
Вот мы наклоняем её по Pitch на 45 0 0:
![45 0 0](https://user-images.githubusercontent.com/98685264/204050428-f0810d22-513a-47ab-9f04-5a7941fec8fc.jpg)
При этом видно, что вниз наклоняется та сторона, на которой расположена направляющая.
Вот мы повернули энтить по Yaw на 0 90 0:
![0 90 0](https://user-images.githubusercontent.com/98685264/204050559-f8188b21-07f7-4a69-b222-727de4d0b7d1.jpg)
Вот мы к повороту по Yaw добавляем наклон по Pitch: 45 90 0:
![45 90 0](https://user-images.githubusercontent.com/98685264/204050643-9bb4b50b-145d-4fe5-b539-70e7d9070e8f.jpg)
Что получилось? Энтить наклонилась тупо в ту же сторону. Вместо того, чтобы ушла под землю та сторона, на которой была направляющая, а противоположная сторона поднялась, мы видим, что энтить завалилась на бок в том же направлении, без учёта поворота модели по Yaw.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D так, я изменил что-то и кажется это заработало... :)

Причем я уже раз 20 пытался так сделать и никак не работало, перебрал может 10 функций rotate matrix )

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D https://github.com/UnrealKaraulov/newbspguy/commit/bd13889c0962f8a7d29597ec0293459a09a7f008

тут проблема решена или я опять глюк словил?)) 

тут еще какие-то косяки с func_ сущностями, у них или PITCH или YAW , одновременно и то и то не работает. не могу понять в чем дело :) причем редактор поддерживает, а в игре нет.

**Comment by Qwertyus3D** [comment]
Да не важно сейчас, что в игре. Важно, что сам редактор какую-то ересь показывает, это же очевидно.

**Comment by UnrealKaraulov** [comment]
> Да не важно сейчас, что в игре. Важно, что сам редактор какую-то ересь показывает, это же очевидно.

зачем вообще отображать в редакторе то что не будет соответствовать увиденному в игре? 

мне нужно что бы объекты располагались так как будут в игре

но что-то все равно не так, не понимаю что

**Comment by Qwertyus3D** [comment]
Я продемонстрировал сейчас скринами в точности то, что я показывал скринами из игры. В игре правильно всё, как должно быть по логике, а редактор показывает неправильное положение.

**Comment by UnrealKaraulov** [comment]
![image](https://user-images.githubusercontent.com/88730285/204051344-efdc93b4-0df0-43c9-9d1e-aeb8200cf86a.png)

![image](https://user-images.githubusercontent.com/88730285/204051377-b97233d7-d3d5-4cc9-907f-4a6acfb3753f.png)
раньше работало правильно в игре, теперь игрок смотрит вниз, а в редакторе нет

**Comment by Qwertyus3D** [comment]
Модель должна вращаться вокруг своей оси координат. А она вместо этого по Pitch вращается тупо в одном направлении.  Вот что неправильно.

**Comment by Qwertyus3D** [comment]
Для редактора Pitch - это наклон в одну конкретную сторону. Точка.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D мне надо что бы соответствовало игре, иначе если в редакторе изменишь углы модельки, а в игре она окажется в е@#$нях то что это за редактор?)

**Comment by Qwertyus3D** [comment]
Так это и не соответствует игре вообще.

**Comment by Qwertyus3D** [comment]
Для игры вращение относительно центра энтити либо разрешено, либо нет. Но нет такого, чтобы энтити наклонялись в одну конкретную сторону. Такого в игре не происходит никогда.

**Comment by Qwertyus3D** [comment]
Как если бы Pitch был условно наклоном на север, и всё. На север можно наклонять, а на юг, запад и восток - нельзя. Вот как это "работает" в редакторе.

**Comment by Qwertyus3D** [comment]
Попробовал последний билд [Update BspRenderer.cpp](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3550468872). Нет, ерунда там. Всё также заваливает модель в одном направлении, не учитывая того, повёрнута она или нет.

**Comment by Qwertyus3D** [comment]
Только крутит теперь в противоположную сторону, что вообще неверно.

**Comment by Qwertyus3D** [comment]
Хотя, если судить по игре, то без разворота энтити по Yaw "ноги" модели уходят вниз при отрицательном значении. Вообще-то это правильно, по идее. Т. к. в игре наблюдается такой же эффект. Проблема только, что Pitch продолжает наклонять модели только в одном направлении.

**Comment by UnrealKaraulov** [comment]
> Первое значение из трёх 0 0 0 - это и есть Pitch.

Это с сайта Valve "angles are X, Y and Z also known as Roll, Pitch and Yaw."

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D с последним обновлением https://github.com/UnrealKaraulov/newbspguy/commit/4d70f5663df25bdcb1b38343893251564ead2508 у меня адекватно работают брашевые entity как в редакторе так и в игре, info_player_start тоже адекватно стало показывать направление взгляда игрока, как в редакторе так и в игре одинаковые углы.

https://youtu.be/7v4NLwFlB4Q

Но тот мертвый ученый наклонен не под тем углом все равно :) может у него правила наклона другие и отличаются от других сущностей... ?:)

**Comment by Qwertyus3D** [comment]
> Это с сайта Valve "angles are X, Y and Z also known as Roll, Pitch and Yaw."

OMG, ну а FGD что показывает на любой энтите с поддержкой angles??? X, Y и Z это безусловно Roll, Pitch и Yaw. Только порядок значений такой:
`Pitch Yaw Roll (Y Z X) (angles)`
Это в любой справке по энтитям прописано...
https://twhl.info/wiki/page/monster_barney
https://simple.wikipedia.org/wiki/Pitch,_yaw,_and_roll

**Comment by Qwertyus3D** [comment]
Pitch - наклон, Yaw - поворот, Roll - вращение. Я всю дорогу толкую о том, что энтить наклоняется строго в определённом направлении, независимо от угла поворота или вращения. Последний апдейт частично исправил ситуацию, но поломал поддержку angle, потому что для angle берётся значение Z, среднее из трёх, но редактор теперь думает иначе и не поворачивает энтить на указанный угол вообще.

**Comment by Qwertyus3D** [comment]
Ещё раз. У энтити есть направляющая. Yaw (Z) вращает энтить вокруг вертикальной оси, меняя её расположение, как по компасу. Pitch (Y) производит наклон энтити. При правильной механике, если значение Pitch отрицательное, направляющая должна наклониться вниз, а при положительном значении - подняться вверх. И это должно работать с учётом того, как энтить повернулась по Yaw (Z). Но! Для модели игрока в Голдсорсе имеется баг, и отрицательное значение, наоборот, разворачивает модель игрока взглядом вверх. Называется это Stupid Quake Bug:
https://www.reddit.com/r/HalfLife/comments/6jjhbd/xash_guy_on_stupid_quake_bug/

Дядя Миша в Ксаше это исправил. Но в случае с моделью учёного как раз проблема в том, что в последнем билде наклон производится в противоположную сторону. А так, действительно, углы сейчас работают корректно. Pitch наконец-то учитывает положение модели по Yaw. Но поломалась поддержка angle. В общем, сейчас исправить нужно:
1. Инвертировать Pitch
2. Вернуть Yaw для angle

**Comment by Qwertyus3D** [comment]
[Revert engine "hardcoded" angles for bspmodels](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3553004059) Angle заработал, но направление Pitch осталось тем же, фикса не было? Или только для браш-моделей что-то изменилось?

**Comment by UnrealKaraulov** [comment]
> [Revert engine "hardcoded" angles for bspmodels](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3553004059) Angle заработал, но направление Pitch осталось тем же, фикса не было? Или только для браш-моделей что-то изменилось?

не знаю в каких случаях нужно отражать, т.к в большинстве случаев работает именно так как в игре, если делать минус PITCH то большинство моделей и сущностей ломается, только у покойника с c2a5 наклон исправляется)

пока ничего сделать лучше чем есть не могу :)

**Comment by Qwertyus3D** [comment]
Есть предложение добавить опцию инверсии Pitch, подобно опциям оптимизации. Чтобы можно было самому указывать, каким энтитям нужна инверсия. Хотя, по моему мнению, правило общее, и должно применяться к любой студиомодели. Потому что учёный - это частный случай студиомодели.

**Comment by Qwertyus3D** [comment]
Вот я задал углы в редакторе моделям солдат:
![PitGuy](https://user-images.githubusercontent.com/98685264/204095020-afb45e36-b7b4-46de-8c87-3e8151404fa0.jpg)

А в игре строго наоборот:
![PitGam](https://user-images.githubusercontent.com/98685264/204095044-a3291817-af26-44cb-9178-dcb1937e0ab6.jpg)

**Comment by Qwertyus3D** [comment]
Вот задал противоположный угол Pitch для двух func_door:
![DoorGuy](https://user-images.githubusercontent.com/98685264/204096011-68377118-626e-43d8-9414-b12cdb68b306.jpg)
В игре эти углы влияют на то в какую сторону смещается дверь при открывании.

Вот что в игре:
![DoorGam](https://user-images.githubusercontent.com/98685264/204096097-99c782d2-e797-41bf-b268-6b219c3da58e.jpg)
При положительном значении дверь уезжает вниз (ближняя), а при отрицательном - поднимается вверх (дальняя).

**Comment by Qwertyus3D** [comment]
Я так понимаю, проблема в том, что брашевые энтити следуют одним принципам наклона (положительное значение задаёт направление вниз), а студиомодели / точечные энтити - другим (положительное значение задаёт направление вверх).

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D как на счет **info_player_** ?

@Qwertyus3D func_door не поддерживает angles d

**Comment by Qwertyus3D** [comment]
Вот подтверждение, энтитя func_door_rotating (с официальной поддержкой angles) в редакторе:
![RotGuy](https://user-images.githubusercontent.com/98685264/204097771-bbac1520-331e-4b25-b0ea-71f8d82e16cb.jpg)

Вот она же в игре:
![RotGam](https://user-images.githubusercontent.com/98685264/204097802-fe70ed43-baa9-44e8-a4b8-bec082ac1d84.jpg)
Углы совпадают. А для студиомоделей - нет. Это и есть Stupid Quake Bug.

**Comment by Qwertyus3D** [comment]
> func_door не поддерживает angles

Формально - нет, а на деле - да. [func_door](https://twhl.info/wiki/page/func_door) и [func_button](https://twhl.info/wiki/page/func_button) - это практически одинаковые энтити. В них angles поддерживается, но задаёт не расположение энтити, а направление смещения после активации.

**Comment by Qwertyus3D** [comment]
> как на счет info_player_

Это, видимо, единственная точечная энтить, которая в игре работает по той же логике, что и брашевые. Да, она задаёт угол обзора так, как мы видим в редакторе, но это исключение. Другие точечные энтити наклоняются в противоположном направлении, включая любых монстров и трипмину. Любые студиомодели, короче. Не уверен, как ведут себя не-студиомодельные точечные энтити...

**Comment by Qwertyus3D** [comment]
Ну, в общем, я пробежался по разным типам энтить. Брашевые, которые поддерживают angles (и info_player_), соответствуют в редакторе и игре. Студиомодели - инвертированы. Остальные энтити можно оставить, как есть, т. к., если честно, у многих их них angles даже если прописаны в FGD, то по факту не делают ничего, либо работает только Yaw, и всё. Либо сложно проверять (да и большой потребности трогать их вроде нет). Допустим, освещение же не поменяется на карте, если энтить отредактировать. Поэтому предлагаю инверсию сделать для тех энтить, которые относятся к студиомоделям. Т. е. monster_, weapon_, ammo_, item_, xen_, weaponbox, worlditems, cycler_.

**Comment by Qwertyus3D** [comment]
Небольшая ошибочка, weapon_ поддерживает только Yaw (т. е. angle, а не angles).

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D мне кажется если в fgd прописано studio, это не значит что в игре тоже будет так. 

Может я сделаю список для этой цели в настройках и заполню его каким-то стандартным значением?

**Comment by Qwertyus3D** [comment]
> Может я сделаю список для этой цели в настройках и заполню его каким-то стандартным значением?

Я это и предлагал выше
> Есть предложение добавить опцию инверсии Pitch, подобно опциям оптимизации.

`Только было бы неплохо фильтр по маске сделать. С поддержкой *. Допустим, monster_* - любой монстр, или *item* - любой итем или worlditems, а weaponbox - просто конкретная энтить.`

>  мне кажется если в fgd прописано studio, это не значит что в игре тоже будет так.

studio в FGD обычно используется для замены простого цветного бокса моделью в тех редакторах, которые это поддерживают. Либо для указания спавна определённой модели через энтить. Т . е. никак не означает, что речь должна идти об инверсии Pitch для данной энтити.

**Comment by Qwertyus3D** [comment]
Либо можно окончание на "_" трактовать, как маску фильтра, если со звёздочкой проблемы. Тогда список должен быть:
```
ammo_
cycler
cycler_
item_
monster_
weaponbox
worlditems
xen_
```

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D дай прояснить

Во всех моделях идет **ROLL YAW PITCH**, а в указанных **PITCH YAW ROLL** ?

Или у всех моделях **" ROLL YAW PITCH "** а у указанных **" -ROLL YAW PITCH "**

**Comment by Qwertyus3D** [comment]
Во всех моделях идет **PITCH YAW ROLL**, а в указанных **-PITCH YAW ROLL** :D

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D 

![image](https://user-images.githubusercontent.com/88730285/204123912-a0a36f1f-12ed-4f56-8b2a-4077c83066d7.png)


https://user-images.githubusercontent.com/88730285/204123951-b7ab21e7-1b57-4e08-b83d-83b8afaa8c80.mp4


https://user-images.githubusercontent.com/88730285/204123952-943e9c53-d451-48f8-926f-24c50788865b.mp4


https://user-images.githubusercontent.com/88730285/204123953-491bc460-6137-454f-86fd-1cef906b5c86.mp4


Вот как углы работают для брашевой модели, именно так отображается в игре. Кто-то кого-то обманывает :(

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D ааа, или это обман зрения из-за того что стрелка расположена не по той оси? :)

**Comment by Qwertyus3D** [comment]
Именно!

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D да все кажется дошло, а то я все по ней смотрел)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D  https://github.com/UnrealKaraulov/newbspguy/commit/de3df90ebe43d602301713aa30172f70235b7c9c

пока еще настройку списка не добавил, проверить буде работать или нет

**Comment by Qwertyus3D** [comment]
Бинарник не скомпилился...

**Comment by Qwertyus3D** [comment]
C env_sprite вообще засада, т. к. там спрайты в нём по-разному ведут себя в зависимости от рендермода и типа спрайта. Но для спрайтов, чётко ориентированных в пространстве, тоже актуальна инверсия по Pitch. Но в других случаях поворот может не происходить, либо углы, указанные в трёх значениях, могут суммироваться друг с другом, а вращение будет строго вокруг одной оси. Вот тут подробнее разбирается: https://the303.org/tutorials/gold_sprite.htm Но всю схему будет сложно реализовать в редакторе :D

**Comment by Qwertyus3D** [comment]
Через env_sprite тоже можно вставлять модели, но:
1. Pitch инвертирован, если менять его в отдельности.
2. Pitch, Yaw и Roll крутят модель, взаимодействуя друг с другом, причём алгоритм вообще какой-то заумный. Например, чтобы модель повернулась к тебе спиной, нужно не значение 0 180 0 задать, а 180 0 180.

**Comment by Qwertyus3D** [comment]
Хотя, кстати, редактор воспроизводит для env_sprite именно указанное поведение, только Pitch не инвертирован.

**Comment by UnrealKaraulov** [comment]
> Бинарник не скомпилился...

https://github.com/UnrealKaraulov/newbspguy/actions/runs/3558327834

**Comment by UnrealKaraulov** [comment]
> Хотя, кстати, редактор воспроизводит для env_sprite именно указанное поведение, только Pitch не инвертирован.

так я делал поддержку там все просто было, может быть только pitch забыл инвертировать

**Comment by UnrealKaraulov** [comment]
https://github.com/UnrealKaraulov/newbspguy/actions/runs/3558434229

**Comment by UnrealKaraulov** [comment]
работает?

**Comment by Qwertyus3D** [comment]
Теперь что-то не то с поворотом модели. Yaw неправильно модель вращает. Нужно смотреть на направляющую, которая из энтити выходит. Она теперь вообще себя ведёт неадекватно.

**Comment by Qwertyus3D** [comment]
Убрал из настроек негативный питч, Yaw всё равно модель как-то некорректно разворачивает.

Было:
![barold](https://user-images.githubusercontent.com/98685264/204141796-fb6519a2-887e-408b-b5b4-52716c25a8f7.jpg)

Стало:
![barnew](https://user-images.githubusercontent.com/98685264/204141911-9de67bd8-7c97-48f8-bc58-cf35e630e93d.jpg)

**Comment by Qwertyus3D** [comment]
Было:
![sciold](https://user-images.githubusercontent.com/98685264/204142083-a2632e45-55af-44df-98ff-c48b56faa46a.jpg)
Здесь неправильно только, что направляющая смотрит вверх, должна смотреть вниз.

Стало:
![scinew](https://user-images.githubusercontent.com/98685264/204142089-d6793817-e4fd-46d6-a13e-17d29f91ad4d.jpg)

**Comment by Qwertyus3D** [comment]
[Fix pitch list bug](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3559178081) Судя по всему, заработало 👍

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D отлично :)

тогда закрываю)))
