### ISSUE TITLE
Filtering failure in Entity report

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#38]
Если используешь поиск в списке Entity report по Keyvalue, и поиск ничего не находит, либо находит, но ты затираешь или меняешь введённые значения, либо пытаешься добавить дополнительный фильтр, то постоянно происходит ситуация, что список перестаёт вообще отображать какие-либо энтити, даже если полностью убрать все текущие фильтры. Помогает только перезапуск программы.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D понял займусь завтра тем что сегодня не успел

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D исправил и добавил кнопки ADD/DEL для нескольких фильтров https://github.com/UnrealKaraulov/newbspguy/commit/2ff3acdc05aaa260e5aed0d9586d4c8e879a0105

Ошибка была в imgui_stdlib причем не первая) там изначально краш был при нажатии ctrl+v а затем ctrl+z... )
