### ISSUE TITLE
Artifacts in newest builds

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#39]
С билда [Select multiple ents. Part 2](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3541547049) при открытии карты обнаруживаются визуальные артефакты в виде множества жёлтых линий, тянущихся сквозь карту из бесконечности в бесконечность. Похоже, что это происходит на картах с открытым небом, допустим, crossfire. Линии видны сразу при спавне карты. Билд [Fixes and preparing to multiple ent selection](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3541336871) и ранее не выявляют проблемы.

**Comment by Qwertyus3D** [comment]
Оказалось, что предыдущий билд [Fixes and preparing to multiple ent selection](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3541336871) тоже добавил проблему, которая выявляется на картах, прошедших оптимизацию. Объяснить сложно, но постараюсь. Суть такая - если на карте есть триггер из категории optimizer_cond_ents, например, trigger_once или trigger_multiple, и с этим триггером связаны другие энтити (т. е. этот триггер при активации вызывает другие энтити, например), то при выделении этого триггера (который после оптимизации утратил часть хуллов и отображается в виде жёлтой прозрачной фигуры) возникает глюк: все линии, которые должны показывать взаимосвязанные с ним энтити, тянутся от них не к выбранному триггеру, а к другому объекту, который стоит последним в списке энтить.

Проблему, в принципе, выявить довольно легко, нужно просто сделать оптимизацию (можно даже не сохранять карту), а потом выбрать любой оптимизированный триггер и посмотреть, куда идут линии взаимосвязи. Похоже, что артефакты в виде линий, упомянутые выше, тоже имеют отношение к этому, как бы являются следствием или развитием проблемы.

Ошибка отсутствует в билде [Fix filter issue, added multiple key filtering](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3540863820) и ранее.

**Comment by UnrealKaraulov** [comment]
> С билда [Select multiple ents. Part 2](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3541547049) при открытии карты обнаруживаются визуальные артефакты в виде множества жёлтых линий, тянущихся сквозь карту из бесконечности в бесконечность. Похоже, что это происходит на картах с открытым небом, допустим, crossfire. Линии видны сразу при спавне карты. Билд [Fixes and preparing to multiple ent selection](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3541336871) и ранее не выявляют проблемы.

Да я понял в чем дело, должно исправится тут: 

https://github.com/UnrealKaraulov/newbspguy/commit/9bc50563e403715740030fb08b10b326eeee3bae

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D вторая проблема возможно тоже исправилась?!

**Comment by Qwertyus3D** [comment]
Проверил данный фикс и последующий. Исправилась проблема с выделением оптимизированных триггеров. Но жёлтые трейсеры на картах с небом остались, на том же crossfire хорошо заметно.

**Comment by Qwertyus3D** [comment]
Или boot_camp, там прям связка целая линий. Но что заметил, теперь проблема проявляется рандомно. При каждой новой загрузке карты по-разному вылезает. Иногда может только 1 линия быть, а иногда - пачка.

**Comment by Qwertyus3D** [comment]
Ещё один факт - линии видны при загрузке карты, пока ничего не выделено, просто режим обзора. Когда что-то выделяешь, трейсеры пропадают. И раз даже видел проблему на карте без неба, но рандомно.

**Comment by Qwertyus3D** [comment]
![lines](https://user-images.githubusercontent.com/98685264/203938157-09be555f-5dd0-455c-9356-cd4471037a0b.jpg)
Даже вот такое иногда видно, целая сетка. Тоже на карте без неба.

**Comment by Qwertyus3D** [comment]
Кстати, на скрине ещё одна проблема - если программа была закрыта с развёрнутым виджетом (в данном случае - Settings), то после перезапуска этот виджет тоже открыт, но те виджеты, которые находились под ним, отображаются поверх него (Entity Report & Limits). Это древняя проблема программы, всегда была.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D не сталкиваюсь но возможно в самом рендере проблема была, вернул код назад старый

https://github.com/UnrealKaraulov/newbspguy/commit/0d91e2af406ef655d37671b28d43f2654ac2bce2

Проблема еще присутствует ?

**Comment by Qwertyus3D** [comment]
boot_camp почти стабильно прогружается с веером трейсеров. На некоторых картах проблема не появляется, на некоторых трейсеры мелькают в момент загрузки карты, потом пропадают. В целом проблема есть, но реже попадается на глаза. В целом, то же самое можно сказать и про билд [Fix overflow warns. Fix updateEntConnections](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3546509444)

**Comment by Qwertyus3D** [comment]
Однако, с билдом [Fix filter issue, added multiple key filtering](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3540863820) проблемы нет вообще.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D как на счет https://github.com/UnrealKaraulov/newbspguy/commit/25e4394a97ad08a3c437f9d99749531417ab0e99  

там оказалось последние несколько билдов сломано VIS компиляция, странно что карты не крашились после оптимизации.
остальные изменения это все еще подготовка к возможности выделять несколько ENTITY сразу. (pickInfo структура слишком усложняла работу, т.к рассчитано было чисто на 1 сущность, на 1 фейс, или на 1 модель)

**Comment by UnrealKaraulov** [comment]
автор изначально накосячил и сделал этот pickInfo таким, что нельзя выбрать более одного объекта, теперь уже сколько времени пытаюсь избавиться, что бы добавить адекватный выбор множества объектов)

**Comment by Qwertyus3D** [comment]
Не помогло 
![lines2](https://user-images.githubusercontent.com/98685264/203993963-703717a2-fb8f-49c3-b2c0-006b85b44eb4.jpg)

**Comment by Qwertyus3D** [comment]
Бывает, что грузится без проблем, а иногда вообще вот так: 
![boot](https://user-images.githubusercontent.com/98685264/203994732-fd7ff0af-cb4c-4925-b94b-66377da92419.jpg)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D с последним билдом ничего не изменилось? :)

Проблема именно при загрузке, после загрузки все нормально?

Похоже на рендер wireframe но там должны быть белые линии? 

Может какой-то world leaves но с чего бы ему рисоваться если отключено и не загружен еще.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D если отключить чекбокс "World Leaves" в настройках, проблема пропадает?

**Comment by Qwertyus3D** [comment]
Не похоже, что от чекбоксов что-то зависит. Обычно это какой-то мусор, но изредка выглядит именно как wireframe текущей карты, перевёрнутый и искажённый. Иногда сразу линий не видно, но начинаешь двигаться в пространстве или крутить обзор, и они появляются. Иногда бывает, что целый букет линий исходит во все стороны из точки спавна на карте. Но как только тыкаешь в какой-то объект карты или worldspawn, глюк пропадает.

**Comment by Qwertyus3D** [comment]
С Part 4 тоже есть проблема.

**Comment by Qwertyus3D** [comment]
Похоже, что фикс [Fix tranformation window old bug! (Now all works)](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3549162203) исправил проблему, трейсеры не появляются!

**Comment by Qwertyus3D** [comment]
Я так понял, проблема не то чтобы исчезла, скорее замаскировалась. При старте карты теперь автоматически выделяется worldspawn, что предотвращает появление этих трейсеров. Но один раз, после процедуры оптимизации, я всё же имел случай опять увидеть эти жёлтые линии, когда сбросилось выделение объектов карты, видимо.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D что бы исключить проблему в рендере я вернул код VertexBuffer.cpp/h в исходное состояние (т.к там ничего особо не исправлял, только тестировал всякое)

Но похоже на то что рисуются wireframe линии (они есть желтого цвета) во время прогрузки карты, и возможно они еще не доконца заполнились по этому проявляется баг.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D ниче не изменилось в последних билдах, все еще проявляется?

**Comment by Qwertyus3D** [comment]
Ну, как я сказал, баг, возможно, остался, но в стандартных условиях загрузки карты больше уже не проявляется. В целом, можно закрыть, если нет идей, куда копать.

**Comment by UnrealKaraulov** [comment]
Ну я примерно знаю откуда эти желтые линии но не понимаю почему они появляются

Ладно пока это не приводит к крашам закрою
