### ISSUE TITLE
Keyvalue Editor некорректно редактирует свойства entity во вкладке Attributes

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#4]
При редактировании отдельных параметров энтити во вкладке Attributes вместо установки значения требуемого параметра создаётся его дубликат с изменённым значением Key. Похоже, что обычно это происходит в случае, когда ты пытаешься задать параметр, который в данный момент в энтити не прописан, но присутствует на вкладке Attributes. Допустим, у меня есть trigger_hurt с полями Target и Master на вкладке Attributes, но в режиме Raw Edit данных полей в энтити нет. Если попытаюсь ввести какое-либо значение для этих полей на вкладке Attributes, то вместо создания соответственно  параметров target и master в свойствах энтити программа прописывает параметры типа target#1, target#2, target#3 и т. д., причём может создать по мере ввода значения целый ряд таких ошибочных полей. Конечно, эти поля не дают эффекта, и на вкладке Attributes введённое значение не запоминается, но остаётся мусором в свойствах энтити, причём иногда этот мусор даже проблематично удалить, т. к. по мере удаления ошибочных значений автоматически создаются новые значения Key с нарастающим номером после #. В итоге корректно работает только ручное редактирование в режиме Raw Edit.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D понял, исправлено в https://github.com/UnrealKaraulov/newbspguy/commit/0568805131f483dca1df905bd131b722185b1ad4

**Comment by UnrealKaraulov** [comment]
Если будут проблемы то можно создать еще issue
