### ISSUE TITLE
Crash on cycler_weapon's model

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#40]
Такая проблема:
- Создаю энтить
- Меняю тип на cycler_weapon
- Выбираю поле model
- Crash

Либо может быть ситуация, что я потыкал другие поля перед этим, тогда при выборе поля model редактор не крашится. Но если я попытаюсь удалить cycler_weapon, не задав model, то опять краш.

**Comment by Qwertyus3D** [comment]
Хотя, крашится при удалении и после того, как задать поле model.

**Comment by Qwertyus3D** [comment]
Ещё есть глюк, нестабильный, что если создать новую энтить и выбрать что-то из cycler, то при попытке опять сменить класс энтити отображается не полный сисок энтить, а только 4 категории (func, momentary, trigger, other). Как я понял, тоже если перед этим ткнуть в какое-либо поле энтити.
![class](https://user-images.githubusercontent.com/98685264/204106602-4a095428-5c9f-4410-93eb-89829fd7f785.jpg)

**Comment by Qwertyus3D** [comment]
Причём, что интересно, предлагает точечной энтите классы брашевых энтитей на замену.

**Comment by Qwertyus3D** [comment]
Жёсткий глюк - при выборе поля Animation sequence в поле model начинает быстро прокручиваться текст, как будто бы строчки атрибутов энтити, но не полностью, а только несколько последних символов o_0
![me mdl](https://user-images.githubusercontent.com/98685264/204106922-2e047e72-2db1-4eca-a612-a6436246029c.jpg)

**Comment by Qwertyus3D** [comment]
Аналогично проблеме с cycler, также неправильно отображается меню смены класса для env_sprite, тоже брашевые энтити на выбор.

**Comment by Qwertyus3D** [comment]
И тоже краш при попытке редактирования поля model!

**Comment by UnrealKaraulov** [comment]
> * cycler_weapon

не смог повторить пока что

**Comment by Qwertyus3D** [comment]
Возможно, зависит от того, как энтить прописана в FGD. У меня так:
```
@PointClass base(Targetname, Target, Angles, RenderFieldsMdl, Sequence) size(-16 -16 -16, 16 16 16) color(0 192 255) studio("fgd/half-life/models/cycler_weapon.mdl") = cycler_weapon : "Weapon/model cycler (pickable, with first person animations)" 
[
	model(studio) : "Model (models/name.mdl)" : "models/zombie.mdl"
	body(integer) : "Body choice (if available)" : 0
	skin(integer) : "Skin choice (if available)" : 0
]
```
У меня расширенный FGD. В старом такое:
```
@PointClass base(Monster) size(-16 -16 -16, 16 16 16) = cycler_weapon : "Weapon Cycler" 
[
	model(studio) : "model"
]
```
Может, что-то из-за слэшей в строке? Либо потому, что указан дефолтный вариант для модели ("models/zombie.mdl"). И да, крэш происходит в режиме редактирования Attributes, а не при Raw Edit.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D а у меня halflife-cs.fgd там оказалось его нет совсем, проверю в общем позже чуть

**Comment by Qwertyus3D** [comment]
Самое главное, что прога почему-то думает, что cycler_weapon и env_sprite - это брашевые энтити, т. к. при смене класса точечных энтитей не предлагает. Уже от этого может быть ошибка, связанная с редактированием поля model.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D странное дело не хочет дебажится, выбивает в кучу и не известно откуда исходит ошибка. Посмотрю вечером.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D кажись пофиксил

**Comment by Qwertyus3D** [comment]
Неа, открываю карту с сохранённой пустой энтитью, один клик в поле Model в Attributes -  моментально вылет.

P. S. Хотя, возможно, дело именно в сохранении. Потестирую ещё.

**Comment by Qwertyus3D** [comment]
Нет, всё ещё вылетает, хотя менее стабильно. И был момент, когда в поле model тыкнул, и вылета не было. Пошёл в режим Raw Edit и стал удалять поля (пустые), появившиеся после тыканий :) . При попытке удаления поля model тоже крашнулось.

**Comment by Qwertyus3D** [comment]
В общем, кажется, удалось локализовать баг. Дело в строчке:
`model(studio) : "Model (models/name.mdl)" : "models/zombie.mdl"`
А именно, в значении "models/zombie.mdl". Похоже, как ни странно, проблема в том, что прописана реально существующая модель (zombie.mdl). Т. к. когда заменяю значение, например, на name.mdl, то вылетать перестаёт. В том числе на старой версии, где не было фиксов. И один раз опять, когда прописал zombie.mdl, то видел эффект прокручивания обрывочных строк (на старой версии).

**Comment by Qwertyus3D** [comment]
Хотя нет, не в реальной модели дело. Не понимаю, но, возможно, это что-то с лимитом символов на строку.

**Comment by Qwertyus3D** [comment]
В общем, глупо звучит, но из того, что вижу, выходит, что если прописано что-то длиннее, чем name.mdl, то начинаются вылеты. Допустим, zombi.mdl. Уже возникает глюк с прокручиванием строчек параметров энтити в поле model и вылеты.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я кажется исправил его теперь точно

**Comment by UnrealKaraulov** [comment]
а хотя нет :(

**Comment by Qwertyus3D** [comment]
Проверка:
- создать новый cycler_weapon.
- тыкнуть 1 раз в поле model.
- сохранить карту и закрыть.
- открыть карту, открыть cycler_weapon, ткнуть ещё раз поле model.
- попытаться удалить появившееся поле model в режиме Raw Edit -> вылет 100%.

При этом, когда карту сохраняешь, поле "model" "" в энтите создаётся (видно по энтпатчу), но после перезагрузки карты программа не показывает, что оно есть, хотя и пустое.

**Comment by Qwertyus3D** [comment]
Но если вместо "models/zombie.mdl" будет что-то короче на 2 символа - то вылета нет :D

**Comment by Qwertyus3D** [comment]
И ещё, один раз опять всё-таки видел жёлтые линии на карте после удаления энтити (т. е. тоже в тот момент, когда ничего не выделено). Но воспроизвести намеренно не получается.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D 

https://github.com/UnrealKaraulov/newbspguy/commit/a932904b793803d73d46d80420ffc72c88842f0d

Теперь возможно исправил краш?

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я заметил линии, нашел из-за чего они появлялись. Переполнение буфера было + не вызывался bind шейдера :) 

https://github.com/UnrealKaraulov/newbspguy/commit/5c60b49c3e1270e95861b547ec9a1ce6b309e28b 

исправил линии эти

**Comment by UnrealKaraulov** [comment]
https://github.com/UnrealKaraulov/newbspguy/commit/647d90c656891b127748bc7c5150f38dc1be4828

@Qwertyus3D Тут попытался исправить краш, теперь исправился ?

**Comment by Qwertyus3D** [comment]
Бинарник не скомипилился. 
> Process completed with exit code 2.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D да понял там из-за strlen. ImGUI InputText как-то странно со string работает, строка имеет размер 1 например, но strlen выдает 0, потому что оно почему-то добавляет NULL символы. 

сейчас должно скомпилится

**Comment by Qwertyus3D** [comment]
Исправился крэш. Но осталась ошибка со списком брашевых энтить на смену класса для cycler_sprite, cycler_weapon, env_sprite.

**Comment by UnrealKaraulov** [comment]
> Исправился крэш. Но осталась ошибка со списком брашевых энтить на смену класса для cycler_sprite, cycler_weapon, env_sprite.

ну как бы это и в изначальной версии bspguy имеется, проверяет наличие "model" 

я добавил проверку на звездочку еще, может это поможет : https://github.com/UnrealKaraulov/newbspguy/actions/runs/3574244238

**Comment by Qwertyus3D** [comment]
Да, помогло.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D вместо модели сделал что бы как положено fgdclass использовало для проверки типа (point/solid)

**Comment by UnrealKaraulov** [comment]
https://github.com/UnrealKaraulov/newbspguy/commit/2c995f9b607fc800d7226fcff8beaabca426f916

**Comment by Qwertyus3D** [comment]
Во, просто и чётко :)
