### ISSUE TITLE
Option to enable/disable FGDs

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#42]
Очередное пожелание: добавить возможность не только составлять список из нескольких FGD, но и включать/отключать их. Чтобы напротив каждой строчки FGD была кнопочка, к примеру, ON/OFF (или просто поле для галочки Вкл/Выкл). И можно было по её нажатию временно отключить любой FGD, занесённый в список. Так будет удобно всегда иметь любые FGD под рукой и не давать им конфликтовать, вместо того, чтобы добавлять и удалять сами пути, как сейчас.

**Comment by UnrealKaraulov** [comment]
сделаю, сначала закончу с багами и работой с несколькими сущностями(осталось только редактирование параметров)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D https://github.com/UnrealKaraulov/newbspguy/commit/097ac8630e5dc81ed04550730159a19a7c620c51 ?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Как обычно, :) не скомпилилось.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D не понимаю почему на linux такой тупой компилятор)))

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D https://github.com/UnrealKaraulov/newbspguy/commit/8785709caca07737733998c822ad4cafc2d26c20 должно собраться нормально на linux, работает?

**Comment by Qwertyus3D** [comment]
Обалденно, работает 👍 . Только нужно вручную перезапускаться, а само приложение об этом не намекает :) . Но это терпимо!

**Comment by UnrealKaraulov** [comment]
> Обалденно, работает 👍 . Только нужно вручную перезапускаться, а само приложение об этом не намекает :) . Но это терпимо!

всмысле не обновляется список FGD в редакторе после изменения настроек?

**Comment by Qwertyus3D** [comment]
Ну да. Пока не перезапустишься, изменения FGD игнорируются.

**Comment by Qwertyus3D** [comment]
Имею в виду, редактор продолжает работать с тем FGD, который был активен в момент запуска. Все энтити и их настройки не меняются, пока не перезапустишь программу. В идеале бы, конечно, чтобы обновлял список энтить при включении/отключении и т. д.

**Comment by Qwertyus3D** [comment]
Список самих FGD конечно же обновляется, он не может не обновляться, раз ты в него изменения вносишь.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D а сейчас? я вроде как сделал более полную перезагрузку после смены настроек

**Comment by UnrealKaraulov** [comment]
> Имею в виду, редактор продолжает работать с тем FGD, который был активен в момент запуска. Все энтити и их настройки не меняются, пока не перезапустишь программу. В идеале бы, конечно, чтобы обновлял список энтить при включении/отключении и т. д.

я добавлял полную перезагрузку после изменений настроек, это помогло?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Возвращаясь к вопросу. На данный момент используемый FGD не обновляется при включении/отключении, только после перезапуска программы. Можно дисклеймер добавить в настройках, что, мол, Program restart required что-то там, если нельзя сделать, чтобы изменения применялись "на лету".

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D странно должно там легко все перезагружаться, там список заново составляется... очень странно что не работает

**Comment by UnrealKaraulov** [comment]
Как сейчас перезагрузка списка фгд всё ещё не работает?

**Comment by Qwertyus3D** [comment]
Перезагрузка списка срабатывает. только если вручную виджет Настроек закрыть. Тогда изменения применяются.

**Comment by UnrealKaraulov** [comment]
Так после закрытия настроек, они и применяются, это нормально

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov  Возможно, это нормально, но, может, тогда кнопку добавить типа Apply settings, чтобы по её нажатию окошко само перезагружалось и открывалось снова? А то это вообще неочевидно, что нужно окошко закрыть, и это как-то повлияет.

**Comment by Qwertyus3D** [comment]
Просто у меня виджет настроек, например, вообще никогда не закрывается, я его только сворачиваю.

**Comment by UnrealKaraulov** [comment]
Там кнопка была но я иногда забывал ее нажимать ) думал лучше если автоматически будет применяться при закрытии :)

Могу сделать еще что бы ничего не работало пока открыто окно настроек )

ну или верну кнопку :)

**Comment by Qwertyus3D** [comment]
Верни кнопку, так удобно будет и понятно!

**Comment by Qwertyus3D** [comment]
Но при закрытии пусть тоже обновляется. И все довольны.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Кнопка **Apply settings** появилась, но она ничего не делает. Я вообще думал о том, что она будет непосредственно в разделе списка FGD, чтобы было понятно, что требуется её нажать для применения изменений. Хотя для списка WAD тоже нужно... Ну пусть будет там, где сейчас, но нужно, чтобы она виджет настроек перезагружала (закрывала и открывала снова), т. к. иначе настройки не применяются.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал что бы закрывалось кнопкой

Закрываю
