### ISSUE TITLE
Regarding the Welding Map Textures Feature

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [UnrealKaraulov/newbspguy#43]
Just to get this straight, does this feature basically make the maps have the textures welded for good, even if the WADs are missing? This is at least in similar vain to c0a0 for example, since textures are burnt into the map.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade I don't know about what you

Export all textures from map to .wad ?

or import all textures from wad to map ?

**Comment by ToxicHolyGrenade** [comment]
Importing.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade but what question ?

**Comment by ToxicHolyGrenade** [comment]
In terms of importing wad textures into maps.

**Comment by Qwertyus3D** [comment]
@ToxicHolyGrenade What the problem just to use feature instead of asking? I bet it's more simple, than bothering other people :) Especially when everything you need is few clicks...
![Merge](https://user-images.githubusercontent.com/98685264/205066767-d0a52bf6-ecf4-4872-9fea-8da2ca90d459.jpg)

**Comment by Qwertyus3D** [comment]
Your map will get all the textures from a chosen WAD.

**Comment by ToxicHolyGrenade** [comment]
That's no problem, just need to be sure guys. :)
