### ISSUE TITLE
Applying Multiple FGD Files

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [UnrealKaraulov/newbspguy#44]
Would it be possible to add the possibility of using more than one FGD file? Because when trying to use more than one, it doesn't seem to work, after all when you can add another line to another FGD file. I can't add more either because as a result, the entities would look off, and I cannot easily identify what entity it is exactly. The sort of FGDs I am taking about basically, are game and mod FGDs, like Half-Life Absolute Zero, Opposing Force, and Afraid of Monsters: Director's Cut. With also the problem with most of the entity names not showing up from either of them and vice versa.

Thanks for taking the time to read.

NOTE: I added this issue here as well for both efficiency reasons.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade you can't using more than one FGD file in this fork of bspguy??

**Comment by ToxicHolyGrenade** [comment]
Doesn't work, and doesn't seem to be implemented yet.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade really ? you use newbspguy, or original bspguy ?

**Comment by ToxicHolyGrenade** [comment]
New BSPGuy.

**Comment by Qwertyus3D** [comment]
![addfgd](https://user-images.githubusercontent.com/98685264/205062528-91bd54d9-e9fb-4104-a563-2cbb4193cfab.jpg)
Obviously, "Add fgd path" feature.

**Comment by Qwertyus3D** [comment]
Make sure you get latest build: https://github.com/UnrealKaraulov/newbspguy/releases (and install it properly).

**Comment by ToxicHolyGrenade** [comment]
Just to inform you, I am using the latest build, and I did try adding in another .fgd (what I am trying to use is both ssh.fgd and sven-coop.fgd), but it doesn't do that, and all that's only used is sven-coop.fgd. It would be cool if I can do that for more efficiency so I wouldn't have to change between FGD files, even as long as the entity names in the make entity list doesn't get overwritten.

That's basically what I was saying.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade you can use multiple fgd files in my fork, need enter full path to fgd files, or relative to mod directories (entered in assets paths)

You need option to enable/disable selected fgd in real time?

**Comment by ToxicHolyGrenade** [comment]
That can also be useful for BSPGuy users.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade I cant understand yoy.
