### ISSUE TITLE
There Are Some Inefficiencies + Updated

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [UnrealKaraulov/newbspguy#45]
My ideas are for getting rid of some inefficiencies.

Implement a feature where BSPGuy users, can select more than one entity like in J.A.C.K.

Implement a feature where BSPGuy users, can collectively select an entity group via an “advanced selection tool.”

In addition to the top one, implement a feature where BSPGuy users can not only select more than one entity like in J.A.C.K, but can change them simultaneously, whether its the attributes, flags, or raw edit tab.

2a. In a similar vein to the “advanced selection tool” idea, at least when in comes to monstermaker, squadmaker, and env_xenmaker entities, is to also have a tool to both search and collectively select them by spawning entities, making it much more easier and less time consuming when it comes to looking through each of the aforementioned three entities.

Implement a feature where BSPGuy users, can use CTRL + F, which can allow them to find entities by name by typing them in.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade maybe strange question, but... you uses build from https://github.com/UnrealKaraulov/newbspguy/releases or from original bspguy ??

**Comment by ToxicHolyGrenade** [comment]
The build you are working on, which is New BSPGuy.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade please stop it, if you uses bspguy by wootguy then you need create issues in origin repository.

**I cant understand you**...you can download binaries from newbspguy releases and test it, before create issues

In future, please you can use one issue for one request, and write more readable text
