### ISSUE TITLE
Load map from info_player_start POV, if it exists

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#46]
Предложение - добавить опцию для загрузки карты в редакторе с точки info_player_start. А то есть такие карты, на которых не сразу сориентируешься, где что находится, если загружаешься непойми где. Либо, допустим, даже так, сделать опцию, какую энтить искать для точки загрузки. info_player_deathmatch или, к примеру, trigger_changelevel. Это на случай, когда на карте нет info_player_start. Если таких энтить несколько, то выбирать первую по списку (чтоб всегда с одной точки обзор был вначале). Ну и учитывать angles в настройках энтити для выбора направления обзора.

**Comment by Qwertyus3D** [comment]
По поводу реализации данной фичи, можно так сделать: список энтить в настройках, с приоритетом. Первая энтить будет той, которую будет искать редактор в первую очередь, например info_player_start. Если не найдена, то ищет первую info_player_deathmatch по списку. Если не найдены обе, то смотрим следующую, или грузим карту, как обычно.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D начал делать

**Comment by UnrealKaraulov** [comment]
Что-то не пойму как "angles" в CameraAngles записать, то работает то не работает, как-то совсем странно. На одних картах получилось работает на других в обратное направление смотрит и т.п)

На счет trigger_camera, тоже думал добавить, но чет геометрию совсем подзабыл :D Думаю как получить vec3 angles из двух vec3 точек :)... )))) как найду, сделаю :)

**Comment by Qwertyus3D** [comment]
Для начала пойдёт и спавн в нужном месте 👍

**Comment by Qwertyus3D** [comment]
Я вижу, опция работает. Однако энтить в списке она выбирает НЕ первую. Например, на c1a0 выбирается вторая энтить info_player_start (удивительно, но там их две), которая находится почти в конце списка. Аналогично, на карте bounce выбирается вторая энтить, а не первая.

**Comment by Qwertyus3D** [comment]
Ну и поворачивает взгляд не туда. Было бы, кстати, неплохо помещать камеру за спиной модели игрока, т. е. на некотором оптимальном отдалении, а не внутри неё.

**Comment by Qwertyus3D** [comment]
Я бы предложил поднять камеру на 50 юнитов выше и отодвинуть на 50 юнитов назад. Тогда спавнишься за плечами модели и немного над ней. Ну или на 64 юнита, чуть подальше.

**Comment by Qwertyus3D** [comment]
Питч можно не учитывать, достаточно делать проверку Yaw, т. е. куда модель смотрит по сторонам света.

**Comment by Qwertyus3D** [comment]
![spawn](https://user-images.githubusercontent.com/98685264/210405870-6fe45c08-2fa6-49e4-a5ef-0cfdd49c7569.jpg)
Пример того, как выглядит спавн с отдалением на 64 юнита.

**Comment by Qwertyus3D** [comment]
![Spawn32](https://user-images.githubusercontent.com/98685264/210406411-5e331531-3f7e-41d5-b980-3b98c15bbf91.jpg)
А это 32.

**Comment by Qwertyus3D** [comment]
Ну и 50
![Spawn50](https://user-images.githubusercontent.com/98685264/210406851-93b8e0a0-2374-4d3d-be71-397c47774614.jpg)

**Comment by Qwertyus3D** [comment]
50. наверно, оптимально.

**Comment by Qwertyus3D** [comment]
Кстати, на данный момент, камера выбирает направление +90 градусов к дефолтному расположению энтити (без учёта значения Yaw, как если бы оно было = 0+90). Поэтому направление взгляда совпадает с расположением модели в тех случаях, когда Yaw = 90 (как на скринах выше).

**Comment by UnrealKaraulov** [comment]
ну я там слегка не разобрался как камеру поворачивать :)

**Comment by Qwertyus3D** [comment]
Хотя бы отдаление не помешает пока, а то стрёмно спавниться внутри модели.

**Comment by UnrealKaraulov** [comment]
> Хотя бы отдаление не помешает пока, а то стрёмно спавниться внутри модели.

Сделаю уже завтра если не забуду.
Казалась бы камеру должно быть очень легко повернуть но у меня какие-то трудности с этим возникают :)

**Comment by Qwertyus3D** [comment]
Ещё одна проблемка, на примере скинутой карты de_dust2x со вставленной моделью камня. Почему-то если есть такая модель на карте, и прога её загружает, то она уже не стартует с видом от info_player_start / info_player_deathmatch, а запускает карту с видом от нулевой точки. Т. е. как будто не находит нужную энтить. Возможно, ищет её в подгруженной модели.

**Comment by UnrealKaraulov** [comment]
Да и посмотрю что можно сделать с отображением текстуры, возможно нужно их во встроенные загрузить что бы нормально отображались в хл.

**Comment by Qwertyus3D** [comment]
Да, можно опцию сделать по сохранению с использованными вшитыми текстурами. И надо бы, кстати, доработать функцию экспорта wad в карту. Тоже не весь wad импортировать, это ведь ни к чему, а только использованные на карте текстуры.

**Comment by Qwertyus3D** [comment]
Логичный вопрос - вот в программе есть виджет Go To, в котором имеется 1) переход в указанную точку по указанным координатам, 2) поворот взгляда в заданном направлении. Так вот вопрос - если Go To делает то, что требуется, так почему какие-то сложности с перемещением игрока в нужную точку и указанием направления его взгляда при этом? Функция абсолютно одна и та же. Следственный эксперимент:
![GoTo](https://user-images.githubusercontent.com/98685264/211052302-f51230da-5e7f-4739-9ec7-b855d1bef330.jpg)

Сразу всплывает ряд ошибок. Во-первых, оси перепутаны. Coordinates и Angles - это не X Y Z, как указано в GoTo. Координаты - это Y X Z. Т. е. -621 - это глобальное "вперёд и назад", -1000 - это "влево и вправо", -166 - это "вверх и вниз". Я уже ранее писал, что Y и X поменяны местами в очереди. Во-вторых, камера, как выясняется, работает через задницу. А именно, то, что в графе Angles указано, как X Y Z на деле вообще является Y Z X (не Pitch, Yaw, Roll, а Pitch, Roll, Yaw). Т. е. первая цифра даёт наклон взгляда вниз-вверх (это Pitch, или Y по установленным правилам). Вторая при Go To не делает ничего, но по логике она должна давать крен обзора влево-вправо (это Roll, или Z). Третья цифра даёт поворот обзора вокруг вертикальной оси (это Yaw, или X). Но и это не всё. Третий косяк - отсчёт направления взгляда камеры соответствует углу 90 градусов. Т. е., чтобы нам камерой смотреть туда, куда будет смотреть игрок, развёрнутый с углом Yaw = 0, нужно в Go To прописать не X, а Z, и не 0, а 90. Но дальше самое смешное. Камера BSPGuy крутит обзор в противоположную сторону. Т. е. если info_player_start повёрнут на 90 градусов по angle, то нам в нужно не прибавить 90, а вычесть 90 из исходного направления 90 градусов. Т. е. мы будем смотреть в нужном направлении, если указать 0 в графе Z. Если энтить повёрнута на 180 градусов, то камере нужно задать значение -90 или 270. В общем, полный бред. Энтити вращаются против часовой стрелки, а камера - по часовой.

Что-то с этим надо делать...

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D ахах вот почему я не мог никак сделать что бы работало, у меня тоже сказачная хрень происходила когда пытался установить углы )) Ну посмотрю что с этим можно сделать

**Comment by Qwertyus3D** [comment]
Там ещё я хотел, чтобы обзор камерой отдалялся назад на 50 юнитов, но чтобы это работало, для начала придётся наладить управление камерой, т. к. само по себе "назад" определяется тем, как развёрнута энтить. Т. е. для начала нужно определить, где у неё, собственно, зад. И уже согласно этому отдалять камеру, относительно выбранного направления.

**Comment by Qwertyus3D** [comment]
Кстати, в меню Go To есть проблемка - размер окна фиксированный, его нельзя увеличить так, чтобы все опции были видны сразу, приходится использовать прокрутку вниз. И состояние данного виджета тоже не восстанавливается после перезапуска программы.

**Comment by UnrealKaraulov** [comment]
Нашел как угол правильно устанавливать https://github.com/rein4ce/hlbsp/blob/1546eaff4e350a2329bc2b67378f042b09f0a0b7/js/hlbsp.js#L266 :) я то думаю какого черта он кривой какой-то все время получался)))

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал как там, теперь углы правильно устанавливаются, и камера отодвигается выше

**Comment by Qwertyus3D** [comment]
Работает правильно, камера не то, чтобы выше, просто примерно на уровне глаз. НО пропущено то, на что я указывал - неправильное именование осей для Coordinates и Angles. Это базовая проблема редактора, оси поименованы не так, как их считает движок игры, и как они прописаны в любом FGD и редакторе карт.

**Comment by Qwertyus3D** [comment]
В общем, всё заново (выше немного неправильно объяснил, сам запутался), то, что у нас в окне **Go to** в графе **Coordinates** подписано, как оси X Y Z, на деле должно быть подписано, как **Y X Z**. Это вопрос №1. Первая координатная ось - это ось Y (фиолетовая), а не X (синяя).

Вопрос №2. Оси графы **Angles** (которые указывают, как разворачивать объект) - это **X Z Y**. Смотрим сюда: http://samselectronicsprojects.blogspot.com/2014/07/getting-roll-pitch-and-yaw-from-mpu-6050.html
В FGD порядок осей объектов указан, как PItch Yaw Roll (т. е. X Z Y).
Первая ось (Pitch) - это синяя ось X при выделении объекта в редакторе, вращение объекта вокруг которой вызывает наклоны-запрокидывания объекта вниз (+) / вверх (-).
Вторая ось (Yaw) - это зелёная ось Z при выделении объекта в редакторе, вращение объекта вокруг которой вызывает повороты объекта влево  (+) / вправо (-)
Третья ось (Roll) - это фиолетовая ось Y при выделении объекта в редакторе, вращение объекта вокруг которой вызывает крен в правую (+) или левую (-) сторону.

Т. е. в обоих случаях последовательность осей не X Y Z, как могло бы показаться логичным. Тем не менее, такой порядок принят, и следует просто подписать оси в соответствии с принятым порядком. Обращаю внимание, что координатные оси ещё прописаны и в виджете Трансформации, в графах **Move** и **Scale**. И там тоже должен быть указан порядок **Y X Z**. Надеюсь, теперь с этим всё понятно.

Вопрос №3. Когда в виджете  **Go to** в разделе **Angles** мы указываем, куда развернуть камеру, то тут сразу несколько проблем.

1) Вторая графа Angles (то, что сейчас указано, как Y, а на деле является Z) не даёт задать значение угла поворота. Т. е. ты просто вписываешь любое число, а оно тут же сбрасывается на 0.

2) Если мы оставляем значение Angles 0 0 0, то после перемещения камера на деле разворачивается в положение 0 90 0. Т. е. добавляет 90 градусов поворота по второй графе (если бы она работала).

3) Если мы что-то вписываем в третью графу, допустим, 90 градусов, то это вместо наклона камеры (который должен задаваться данной осью) приводит к повороту камеры по Yaw (вторая графа), причём с инвертированным значением. Т. е. камеру крутит по другой оси и в обратном направлении.

В итоге, наклон камеры (Roll) с помощью Angles не работает вообще, а поворот камеры (Yaw) просто поломан аж в трёх местах. Единственное согласованное значение - это Pitch из первой графы.

Вот теперь всё очень чётко объяснил, надеюсь.

**Comment by Qwertyus3D** [comment]
Ещё дополнение, неплохо бы, чтобы можно было сразу три значения граф вставлять из буфера обмена. Ну т. е., чтобы щёлкнув по первой графе, можно было туда скопипастить значение типа
100 200 -300
И сразу заполнялись все 3 графы, а не вручную каждую править.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D 
ну я поменял текст стало лучше или я не так понимаю, мне чето с этими углами и координатами плохо доходит)))))

**Comment by Qwertyus3D** [comment]
Ну я же всё расписал. Как я ещё должен объяснить? Ладно: Вопрос №1 и Вопрос №2 - это просто текст изменить.

Вопрос №3 - ну тут надо перечитать и врубиться, потому что там баг из трёх пунктов, каждый из которых следует исправить. Я максимально чёткое описание дал, на мой взгляд.

Я сейчас дам картинку, в чём проблема, а ты уж постарайся понять, вроде не на иностранном языке пишу.

![c1a0b](https://github.com/UnrealKaraulov/newbspguy/assets/98685264/a60fa856-0f96-47d1-9c43-a6db519dab2d)

Итак. это скрин с карты c1a0b. Пример взят по энтите info_player_start. Данная энтитя спавнит игрока с расположением строго по оси координат 0 0 0, т. е. вот как эта моделька расположена, так и должен смотреть взгляд камеры при перемещении Go To, если мы не меняем угол (Angles).

А фактически - БАГ №1 - если мы оставим угол 0 0 0 в Angles, камера разворачивает взгляд на 90. Т. е. мы будем смотреть вот так:
![90degreeZ](https://github.com/UnrealKaraulov/newbspguy/assets/98685264/5872300d-be52-417f-929d-aa77956458d5)
Внимание! Я на модельке показываю, как разворачивает камеру при значении 0 0 0. Т. е. моделька тут для понимания, в чём проблема камеры, а с самой моделькой всё нормально, поэтому на ней и показываю, что не так с камерой.

Как видно из примера, камеру разворачивает на 90 градусов по среднему значению, т. е. 0 90 0. Это у нас ось Z, а порядок осей Angles - X Z Y.

Для  X, соответственно, получается так:
![90degreeX](https://github.com/UnrealKaraulov/newbspguy/assets/98685264/443c7f86-cdc6-4f82-bcb2-1f4de860cf35)

А для Y так:
![90degreeY](https://github.com/UnrealKaraulov/newbspguy/assets/98685264/eace430f-68f1-4904-b119-610103fda259)

Ещё раз, это три примера, как ДОЛЖНА БЫЛА БЫ работать камера, если бы она работала правильно. Если бы мы вбивали в Go To Angles значения 90 градусов по каждой из осей и камера после этого правильно бы поворачивала нашу точку обзора.

Т. е. в виджете Angles порядок осей должен быть X Z Y. Это то, что было ранее обозначено, как Вопрос №2.

X управляет наклоном камеры вниз, в сторону пола при плюсовых значениях, в сторону потолка при отрицательных. Сейчас это так и работает, только ось в виджете не на своём месте по порядку.

Y управляет вращением камеры вбок, плюсовые значения (если мы считаем их с видом от первого лица) должны наклонять обзор по часовой стрелке, минусовые - против часовой. На данный момент с этой осью БАГ №2 - она вращает камеру по оси Z и в противоположном направлении. Т. е. вообще не за свою ось отвечает.

Z управляет вращением камеры вокруг вертикальной оси, и плюсовые значения - это ДОЛЖНЫ БЫТЬ повороты влево (считая вид от первого лица), а минусовые - повороты вправо. На данный момент эта ось вообще не управляема - это БАГ №3. Сначала вводимые значения сбрасывались, а теперь ты вообще отрубил возможность вводить туда значения.

Обращаю внимание, что в меню дебага текущее отображение углов Angles тоже выводится в порядке X Y Z, там тоже нужно поменять последовательность на X Z Y, чтобы везде всё совпадало.

Ещё раз, что требуется:
- поменять порядок осей Angles в виджетах Go To и Debug на X Z Y
- убрать дополнительный поворот камеры по оси Z на +90 градусов, когда мы вбиваем значения Angles в Go To.
- исправить то, что значения, вбиваемые в графу Y, крутят камеру по оси Z, и в противоположном направлении.
- исправить то, что ось камеры Z сейчас не управляется вообще, а только посредством неправильного вращения по Y.

Надеюсь, теперь всё ясно, потому что я уже не один час потратил на описание проблемы, и как бы уже запарился объяснять -_-

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D Можешь захочешь C++ изучить и сам поменяешь местами что надо))))



Ладно шучу, завтра еще что-нибудь попробую поменять сегодня на работу в ночную смену)))

**Comment by Qwertyus3D** [comment]
Ну, я не тороплю, просто я реально максимально доходчиво постарался изложить, хоть и на уровне не специалиста по коду. Естественно, что я не могу сказать, что именно исправить, тут придётся подумать. Но проблему нужно решать пошагово, порядок я указал. Начать с исправления порядка осей Angles, тогда уже проще будет вертеть обзор и сравнивать результат с поворотами того же info_player_start. И исправить то, что у камеры всегда меняется угол поворота  на дополнительные 90 градусов, это тоже не заметить нельзя, если сравнивать положение камеры и энтить.

**Comment by KarKarKarKarkarkar** [comment]
Да а я далек от геометрии этой всей) По этому для тебя это понятно, а я допереть не могу че от меня хотят 🤣🤣 но завтра точно попробую что-нибудь поменять в коде)

Еще с прозрачностью проблемы, ну это в другой issue, ее или не рисовать вообще или рисовать с такими косяками как перекрытие других прозрачных объектов.

Пробовал сортировать список ентить по отдалённости от камеры, это работает но у меня фпс упал до 10 кадров, вполне возможно что я делал что-то не так))))) Еще вариант поменять рендер на другой, но опять же для меня это не вариант т.к сложно:(

**Comment by UnrealKaraulov** [comment]
```
Y управляет вращением камеры вбок, плюсовые значения (если мы считаем их с видом от первого лица) должны наклонять обзор по часовой стрелке, минусовые - против часовой. На данный момент с этой осью БАГ №2 - она вращает камеру по оси Z и в противоположном направлении. Т. е. вообще не за свою ось отвечает.
```

@Qwertyus3D так я специально блокировал возможность это делать, выглядит как-то не естественно думал это вообще лучше не давать возможность наклонять обзор по стрелкам часовым этим))

Щас загрузил обнову, что-то еще поменял в ANGLES, лучше стало или хуже?)))

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Я вижу, задачи нужно ставить пошагово, иначе мы это так и не распутаем. Поэтому вопрос.

Ты сделал порядок осей Angles X Z Y. Та ось, которая для **Angles** называется сейчас **Y**, она так от балды называется, или она действительно как **Y** где-то в глубине движка прописана? Или перефразирую так, она к той оси, которая называется **Y** в разделе **Coordinates** имеет какое-то отношение? Или ты их просто как хочешь, так и называешь (по отдельности друг от друга)?

**Comment by KarKarKarKarkarkar** [comment]
@Qwertyus3D ты написал что они не соответствуют названию, я их поменял. Изначально соответствовало тому что в коде, там x/y/z ,  а есть функция flip которая корвертит между x/y/z и игровыми значениями. Вроде так.

**Comment by UnrealKaraulov** [comment]
```
renderCameraAngles = renderCameraAngles.flip();

renderCameraAngles.z = renderCameraAngles.z + 90.0f;

renderCameraAngles = renderCameraAngles.normalize_angles();
```

@Qwertyus3D может просто сделать так как я делал для "сущностей" ?:)

**Comment by Qwertyus3D** [comment]
Ещё раз, вопрос. Не надо, пожалуйста, вот этот код вываливать, а просто ответ на вопрос. Вопрос исходя из того, как сейчас, на данный момент, названы оси.

Ось Y по Coordinates - она соответствует оси Y по Angles, или такого соответствия не предусмотрено в принципе? Мне не важно, какая там буква у них была изначально приписана, а важно, связаны ли они друг с другом, или нет???

(просто у меня есть сильное подозрение, что та ось, которая сейчас называется Y по Angles, она должна модель не вокруг вертикальной оси крутить, как это сейчас настроено, а она должна крен модели вбок давать, который ты делать не захотел)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D изначально по OPENGL (хз как) оси ANGLES в GOTO, в последнем варианте хз как-то пытался местами менять.

Но если надо сделать как у ентить то я просто этот кусок кода с небольшими правками вставлю и станет как у них)))

**Comment by Qwertyus3D** [comment]
Блин, ответ на мой вопрос можно?

Ось Y по Coordinates - она соответствует оси Y по Angles??

**Comment by UnrealKaraulov** [comment]
> Блин, ответ на мой вопрос можно?
> 
> Ось Y по Coordinates - она соответствует оси Y по Angles??

не знаю, такой ответ устроит?))) 

серьезно ты тут распинаешься, но мне это вообще ни о чем не говорит, такой я туповатый оказывается)))

**Comment by Qwertyus3D** [comment]
Всё, ушёл на работу.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я сделаю точно так же как делал поддержку angles у сущностей и если сработает то скажешь)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D ну что как будешь готов проверь последний билд, должно быть теперь так как надо)

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Теперь почти правильно, но Yaw крутит в противоположную сторону. И сделай уж Pitch Yaw Roll подписи вместо капса.

**Comment by Qwertyus3D** [comment]
И в виджете дебага остался неправильный порядок - Pitch Roll Yaw, а также неправильно угол по Yaw указывается. И почему подписано в Go To "HL Angles", а в дебаге "GL Angles"?

**Comment by UnrealKaraulov** [comment]
OpenGL это те что в newbspguy
HL это goldsrc 

они отличаются, не спрашивай чем, но если надо и туда добавлю отображение HL angles)




> но Yaw крутит в противоположную сторону

ну я делал как "ANGLES" в ентитях, по моему совпадает с ними..

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D да я проверил и правда не в ту сторону вращается) ну ок это исправлю.

**Comment by Qwertyus3D** [comment]
Ну вот смотри - мы же глядим в виджет дебага для сверки. Зачем ему показывать другой порядок углов, это какая-то путаница. В игре ведь углы-то не в каком-то там OpenGL порядке отображаются, а именно в том же, как в FGD.

**Comment by UnrealKaraulov** [comment]
DEBUG это сборка всякого мусора там и то что нужно и то что не нужно. Для того и DEBUG )


@Qwertyus3D добавил игровые углы, и теперь должно в правильном направлении двигать

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Ну, не могу сказать, что у меня есть острая потребность сверять углы по Дебагу, но просто сама логика - зачем там другой порядок? С какой целью он там должен отличаться?

**Comment by KarKarKarKarkarkar** [comment]
@Qwertyus3D там нет логики, просто есть инфа и все) там много чего есть еще кроме углов тоже без какой-либо логики, просто есть))

**Comment by Qwertyus3D** [comment]
Вот именно, что эти GL Angles никому не нужны и будут запутывать людей. Нужно оставить HL Angles.

И сделать так, чтобы значение угла совпадало, потому что там по-прежнему галиматья со смещением, Причём смещение опять в противоположную сторону, как по GL Angles, так и по HL Angles.

Вместо вменяемого и понятного 0 0 0 имеем:
GL Angles 0 0 90
HL Angles 0 0 0

Вместо 0 90 0:
GL Angles 0 0 0
HL Angles 0 -90 0

Вместо 0 180 0:
GL Angles 0 0 -90
HL Angles 0 -180 0

**Comment by Qwertyus3D** [comment]
Надо всё к общему порядку приводить, чтобы потом тебе не репортили о проблемах непонятно про какие цифры Angles, если что. Так и будешь потом уточнять, какие Angles в виду имелись?

**Comment by KarKarKarKarkarkar** [comment]
> Надо всё к общему порядку приводить, чтобы потом тебе не репортили о проблемах непонятно про какие цифры Angles, если что. Так и будешь потом уточнять, какие Angles в виду имелись?



> Вот именно, что эти GL Angles никому не нужны и будут запутывать людей. Нужно оставить HL Angles.
> 
> И сделать так, чтобы значение угла совпадало, потому что там по-прежнему галиматья со смещением, Причём смещение опять в противоположную сторону, как по GL Angles, так и по HL Angles.
> 
> Вместо вменяемого и понятного 0 0 0 имеем: GL Angles 0 0 90 HL Angles 0 0 0
> 
> Вместо 0 90 0: GL Angles 0 0 0 HL Angles 0 -90 0
> 
> Вместо 0 180 0: GL Angles 0 0 -90 HL Angles 0 -180 0

Я же сделал что бы YAW стал отрицательным когда ты написал что он в обратную сторону работает, теперь HL ANGLES совпадает и в дебаг и в go-to ?но перепроверю завтра еще раз.

Angles в opengl тоже может понадобиться для отладки какой-нибудь проблемы с отрисовкой, углы я могу сделать например нижнюю панель где будут отображаться углы, координаты и что-нибудь еще. А дебаг это для разработчиков программы скорее чем для пользователей программы

**Comment by Qwertyus3D** [comment]
Правильные углы и порядок осей в дебаге нужны для того, чтобы подсмотреть там угол текущего направления взгляда и его вписать в параметры энтити, например.

**Comment by KarKarKarKarkarkar** [comment]
@Qwertyus3D так я сделаю нижнюю панель с этой инфой, дебаг жрет слишком много ресурсов когда открыт)

Если есть предложения что отображать в нижней полосе, я сделаю. Думаю туда как минимум углы и координаты вписать, какую-нибудь компактную панель сделать что бы не мешало работе.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал statusbar, показывает координаты, углы, и 3d точку куда был сделан клик мышью последний (хз зачем но может надо :) )

**Comment by Qwertyus3D** [comment]
Работает, только значения друг от друга отделены стрёмно, пробелами этими, которые то есть, то нет. Убрал бы уж пробелы совсем. И на всю длину экрана смысла, наверное, нет растягивать полосу, можно закрыть только столько, сколько нужно для выведения информации. Ну и в идеале можно статус-бар включать/отключать в меню виджетов, а в Настройках можно сделать галочки, какие "датчики" туда выводить (ну, пока, может, не так актуально, но если появятся идеи, что ещё там отображать, то пригодится).

Для клика по энтити, выделенной в последний раз (а не по пустому месту) можно было бы отображать расположение оригина энтити (будет, кстати, полезно для просмотра реального оригина браш-моделей). Пока что вижу, что при выделении энтити показывает какую-то точку в удалении, похоже что по ближайшей точке ворлдспапвна вычисляет, который за кликнутой энтитью располагается.

И если несколько объектов выделено, то можно отображать их число и усреднённый оригин.

Попутно замечу, есть такая проблемка, которую замечаю при перемещениях брашевых энтить, у них оригин зачастую после перемещения изменяется по всем осям не на целое число, а на 0,5 или иногда вообще какое-то длинное число после запятой. Неплохо бы было выравнивать до целых значений, а если кому надо не целые, то вручную изменят.

И кстати, можно сделать такую фишку (в виде отдельной кнопочки), как "запекание" нового оригина для перемещённых брашей? Чтобы энтить запоминала своё новое место, как будто она там и была :) (а оригин обнулялся, соответственно).

**Comment by UnrealKaraulov** [comment]
> Работает, только значения друг от друга отделены стрёмно, пробелами этими, которые то есть, то нет. Убрал бы уж пробелы совсем. И на всю длину экрана смысла, наверное, нет растягивать полосу, можно закрыть только столько, сколько нужно для выведения информации. Ну и в идеале можно статус-бар включать/отключать в меню виджетов, а в Настройках можно сделать галочки, какие "датчики" туда выводить (ну, пока, может, не так актуально, но если появятся идеи, что ещё там отображать, то пригодится).
> 
> Для клика по энтити, выделенной в последний раз (а не по пустому месту) можно было бы отображать расположение оригина энтити (будет, кстати, полезно для просмотра реального оригина браш-моделей). Пока что вижу, что при выделении энтити показывает какую-то точку в удалении, похоже что по ближайшей точке ворлдспапвна вычисляет, который за кликнутой энтитью располагается.
> 
> И если несколько объектов выделено, то можно отображать их число и усреднённый оригин.
> 
> Попутно замечу, есть такая проблемка, которую замечаю при перемещениях брашевых энтить, у них оригин зачастую после перемещения изменяется по всем осям не на целое число, а на 0,5 или иногда вообще какое-то длинное число после запятой. Неплохо бы было выравнивать до целых значений, а если кому надо не целые, то вручную изменят.
> 
> И кстати, можно сделать такую фишку (в виде отдельной кнопочки), как "запекание" нового оригина для перемещённых брашей? Чтобы энтить запоминала своё новое место, как будто она там и была :) (а оригин обнулялся, соответственно).

ну без 100грамм не разберусь сегодня, завтра попробую перечитать сообщение) может что-то и сделаю из этого)

**Comment by UnrealKaraulov** [comment]
я ничего не понял, конкретно загрузку с оригина сделал, по этому issue закрываю, для каждого нового случая лучше делать отдельный issue а то превращается в какую-то непонятную кашу из предложений )
