### ISSUE TITLE
Navigation improvements in Entity Report list

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#47]
Просьба добавить возможность перехода по списку Entity Report от энтити к энтите с помощью стрелок курсора вверх-вниз. Сейчас приходится тыкать каждый пункт мышкой, чтобы к нему перейти. Что неудобно в целом, а особенно, если ты пытаешься просматривать параметры энтити в соседнем виджете, то теряешь время на переход каждый раз. И, желательно, чтобы после перемещения выделения можно было перейти к обзору энтити при помощи Enter или Space (как сейчас при двойном клике мышью).

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D совсем забыл, я добавил управление стрелками, переход на пробел(стандартное поведение imgui) ну и плюс удержание shift для выделения нескольких сразу

**Comment by UnrealKaraulov** [comment]
Пока закрою если надо что-то улучшить то можно новый открыть
