### ISSUE TITLE
Host_Error: Mod_FindModelOrigin: EOF Without Closing Brace

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [UnrealKaraulov/newbspguy#50]
While this problem is not very common, it is still worth bringing some light onto it.

First, what I was basically doing, is that I am trying to cross over NPCs of Scientist Slaughterhouse into another mod campaign (Typical Disaster is one of them), even to make some of them attack the player like the NA Slaves.

In order to do that, I opened up the secondary training level, copied the MyClass function from one of the monstermaker entities spawning the NA Agents whilst using Raw Edit, I pasted it into the monster_na_slave NPC, and given the MyClass attribute "4," which is definitely the way to turn an NPC evil. Unfortunately, once I made an attempt to load the level where the edited NPC is, the game disconnects me from the level, and an error saying "Host_Error: Mod_FindModelOrigin: EOF Without Closing Brace" had shown up.

I addressed this problem to [a1batross](https://github.com/a1batross) first, and he explains the issue this way, at least in his words:

"It looks like there is an entity "monster_na_slave" with key "MyClass" but the problem is that at the end of the key, there is a NULL terminator (basically "MyClass\0", which then makes entities list parser think that it's where EOF is.

It's probably a bug of newbspguy if it allows pasting such data or inserts it with a bug."

So, my suggestion here, is to investigate the root cause of the problem and polish it off. Many thanks.

**Comment by UnrealKaraulov** [comment]
I think this issue already reported and fixed in one of previous commits.
imgui_stdlib.cpp produced unexpected null bytes in std::string, I think it fixed in latest nightly releases.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade just need to use latest build, closed as already completed
