### ISSUE TITLE
Translucency for selected types of entities

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#51]
Ещё одно пожелание в плане удобства работы с энтитями. Добавить возможность определить список энтить, которые бы рисовались полупрозрачными. Допустим, триггеры всякие, лестницы и т. д. Ну т. е. такие энтити, которые в самой игре вообще невидимы. А полупрозрачность будет давать возможность рассматривать объекты, попавшие внутрь них. Можно сделать общий регулятор степени прозрачности. Чтобы можно было выбрать, насколько прозрачными будут эти энтити (в случае, если на них вообще наложена текстура). Либо, допустим, сделать галку, чтобы вообще избранные энтити рендерить без текстур, как сейчас создаваемая модель триггера. Чтобы видны были только прозрачные стенки.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D добавил в последнем билде настройки, можно внести список текстур или имена классов сущностей.

**Comment by UnrealKaraulov** [comment]
Закрываю т.к вроде как все работает проверил
