### ISSUE TITLE
Add map name prefix to exported models

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#52]
Небольшое пожелание - к названию экспортируемой модели, типа model191(test1), добавлять префикс с названием карты, типа as_a1_. Чтоб было ясно сразу, откуда модель импортирована. И название потенциально не совпадало с моделями из других карт.

**Comment by Qwertyus3D** [comment]
И, кстати, что это такое, (test1)? Может, оно не нужно? Или это как версия файла?

**Comment by Qwertyus3D** [comment]
Есть, кстати, ещё один вопрос по экспорту. Если модель на карте была продублирована (Duplicate BSP model), то она не извлекается (не экспортируется).

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал в последней версии, исправил ошибку (как бы не ошибка, в дублированной версии больше данных сохраняется просто) убрал тест и добавил название карты

**Comment by UnrealKaraulov** [comment]
Спасибо за баг репорт
