### ISSUE TITLE
"Go to" current entity in Entity report.

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#54]
Мелкое пожелание, сделать кнопку "Go to (selected/current)" внизу списка энтить. Чтобы можно было фокус списка сместить к той энтите, которая выделена непосредственно в окне просмотра в данный момент. А то иногда нужно именно проверить местоположение по списку, и приходится листать вручную.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сделал при запуске выбор текущей модели, то есть вместо -1 вбивает текущую сущность и можно жать кнопку, перейдет к ней.

Так же пришлось G хоткей заменить, на ALT+G ( grab ) т.к конфликтовало с CTRL+G (GO TO)

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Я не понял, про что это: "-1". Видимо, я не был понят. Ещё раз. Вот в окне выделен объект:
![Entgo](https://user-images.githubusercontent.com/98685264/208437919-bea75ec1-745e-4eef-968c-cdec56d043e8.jpg)
А слева открыт список Entity report. Но он просто открыт в рандомном месте. А я хотел, чтобы по нажатию кнопки список сам переходил к той энтите, которая УЖЕ выбрана в окне просмотра. Т. е. я не про то меню Go to говорил, которое в отдельном окошке. А чтобы в Entity report была кнопка, которая фокусировала бы список по выделенной энтите, типа вот так:
![Goent](https://user-images.githubusercontent.com/98685264/208439432-9ecf2bec-5cec-4dae-82d2-d189d4b8da2f.jpg)
Не переход от списка к энтите, а смещение фокуса списка на выбранный объект.

**Comment by Qwertyus3D** [comment]
Чтобы не приходилось вручную пролистывать список энтить, чтобы найти уже выделенную энтить.

**Comment by Qwertyus3D** [comment]
Просто, может быть, название у кнопки должно быть какое-то другое, Go to - это просто первое, что в голову приходит.

**Comment by UnrealKaraulov** [comment]
Аа, я думал это про окно GO TO (которое на CTRL+G вызывается)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D добавил кнопку GO TO, но т.к ко всем сущностям сразу перейти нельзя, оно будет переходить к первой :)

Закрываю, думаю.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Кнопка делает совсем не то, о чём я просил. Она делает смещение фокуса вьюпорта к энтите, выделенной в списке. А я просил смещение фокуса СПИСКА к пункту, соответствующему энтите, выделенной во вьюпорте.

Т. е. я прошу, чтобы список сдвигался к той энтите, которую мы УЖЕ ВЫБРАЛИ во вьюпорте. Потому что сейчас энтить, когда выбрана в окне, она в списке находится неизвестно где. И нужно вручную прокручивать список, чтобы увидеть уже выбранную энтить на её месте в списке.

**Comment by Qwertyus3D** [comment]
Короче, чтобы не путаться в функциях, пусть кнопка Go To смещает и вьюпорт к энтите, выбранной в списке, и список к энтите, выбранной во вьюпорте. Синхронизирует их, короче.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D опять я все не так понял :)

На счет прозрачности текстур надо кое-что переделать что бы последний цвет являлся прозрачностью.

А оно случаем не берет 0,0,255 цвет (синий) за прозрачность даже если его нет в 255 ?

Потому что я делал экспорт и импорт wad, а у меня не сохраняется прозрачность, и она все еще работала на синем цвете

**Comment by Qwertyus3D** [comment]
Скорее всего, твой конвертер автоматически назначает синий куда надо, вот и всё.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D это вряд ли, т.к я не знал и не предусмотрел это :) разве что наугад могло каким-то образом совпать, что тоже вряд ли :)

**Comment by UnrealKaraulov** [comment]
Добавил рендер MDL моделей, но пока еще не включил его в код, радует то что работает и производительность довольно таки высокая. (Я думал будет фпс садить, но не особо садит)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D кнопка готова, проверял работает, помещает выделенную сущность в центр списка.

**Comment by Qwertyus3D** [comment]
Да, работает. Но можно было и просто одну кнопку сделать, с двойным действием.
