### ISSUE TITLE
Change Class Borked

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [UnrealKaraulov/newbspguy#55]
I had been experiencing another bug where despite connecting the FGD files exactly, the change class list still has nothing. This is happening with the more recent version as far as my knowledge goes.

[Bug Images.zip](https://github.com/UnrealKaraulov/newbspguy/files/10263270/Bug.Images.zip)

**Comment by Qwertyus3D** [comment]
Can confirm that. Problem appeared with build [Added kostil' for support UTF8 (cyrillic,etc)](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3694884752)

@UnrealKaraulov Класс энтити поменять нельзя сейчас. Появилось вместе с костылём для поддержки UTF8.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade @Qwertyus3D, исправил отсутствие классов
