### ISSUE TITLE
Support for more BSP goldsrc formats 

### ISSUE THREAD

**Issue by UnrealKaraulov** [UnrealKaraulov/newbspguy#56]
**Добавить поддержку большего числа BSP форматов.**

Какие BSP форматы не читаются, читаются с ошибками, или не сохраняются, кидайте сюда карту и название мода, и если есть ссылку на описание формата или какие изменения нужно внести для добавления поддержки.

**Comment by UnrealKaraulov** [comment]
Добавлена поддержка XASH карт BSP30ex 3 и 4 версии, и 32битные клипноды : https://github.com/UnrealKaraulov/newbspguy/commit/1552921ba34b06fc5528316a7e7774a10f2ca9f0

**Comment by UnrealKaraulov** [comment]
Частично добавлена поддержка 'BSP2' и '2PSB' карт, а так же карт с 'BROKEN CLIPNODES': https://github.com/UnrealKaraulov/newbspguy/commit/b013d2abf386d3e12690671c1281f1a8e63599e2

**Comment by Qwertyus3D** [comment]
Нужно проверить, чтобы используемые текстуры не только в экспортируемых моделях определялись и прописывались правильно, а и просто при работе с картами со вшитыми текстурами. Например, есть проблемы с созданием нового браша на карте, если в эту карту вшита своя текстура aaatrigger. BSPGuy при этом использует для отекстуривания созданной модели не aaatrigger, вшитый в карту, а текстуру из вадника (розовую лямбду), и каким-то образом портит сведения об использованной текстуре, в результате чего после сохранения карты Ксаш рисует вместо aaatrigger, который вшит в карту, aaatrigger из вадника, но со сломанной палитрой (т. е. принимает её за нестандартную текстуру и пытается применить к ней палитру Квейк).

Не уверен, в чём именно ошибка, но BSPGuy как будто вписывает в карту новые сведения о текстуре, если она отличается. Игра в приоритете всегда использует ту текстуру, которая вшита в карту, если только через специальный квар не задан запрет на использование текстур, вшитых в карту. По идее, BSPGuy тоже должен при обнаружении текстур, вшитых в карту, использовать именно их для отекстуривания имеющихся брашей и создания новых. Чтобы не ломать сведения о текстурах, которые уже прописаны в карте.

**Comment by Qwertyus3D** [comment]
Хотя сейчас вот проверил карту, на которой сталкивался с описанной проблемой, так вот в карту вшита такая же текстура aaatrigger, как и в halflife.wad. Но палитра на вновь созданных брашах всё равно ломается после сохранения карты в BSPGuy. Т. е. вроде как дело даже не в том, что сама текстура отличается. Значит, ошибка возникает просто при сохранении данных о текстуре, использованной на новом браше. Возможно, опять какие-то смещения не учитываются.

Но при этом всё же правило о том, что текстуры, вшитые в карту, имеют приоритет, должно использоваться тоже, исходя из того, что этот принцип применяется в самой игре.

**Comment by Qwertyus3D** [comment]
Хм, насчёт текстур вшитых в карту, я ошибся. BSPGuy всё же использует их для отрисовки объектов. По крайней мере, я использовал альтернативную версию halflife.wad, и импортировал в карту текстуры из неё. BSPGuy отобразил их, заодно исправилась проблема с поломкой палитры на созданном браше. Придётся ещё поковырять проблему, если нет никаких идей, что можно исправить из того, что может приводить к неправильному сохранению текстур.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я кое чего правил в последних билдах в текстурах, лучше стало?

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D в игре текстура в первую очередь берется из WAD даже если она есть в карте

**Comment by UnrealKaraulov** [comment]
Подготовил конвертер карт, пока на выходе можно получить только 2 формата. `File > Save As > Half-Life/BlueShift`

**Comment by UnrealKaraulov** [comment]
Сделал конвертер между известными форматами. (Функционал я уже "случайно" добавил в предыдущих обновах, когда сделал поддержку карт, тут просто флагами играться и можно на выходе нужный формат получать)

**Comment by Qwertyus3D** [comment]
Пока некогда тестировать, но за обновами слежу. Как будет время, продолжу.

**Comment by Qwertyus3D** [comment]
Там в свете добавления новых опций, типа экспорта моделей в разных форматах, появились разнообразные глюки меню, в виде отдельных "мелькающих" пунктов меню, которые то видно, то нет, в зависимости от движения курсора по выпадающим пунктам меню. Например,  в меню Файл > Импорт есть 2 пункта для импорта WAD, и нижний пропадает, когда курсор наводится на верхний. Или когда на брашевой энтите вызываешь контекстное меню, то там есть внизу 3 пункта, которые перескакивают в подменю, когда переходишь в меню Export BSP model > With origin. да ещё при этом пропадает пункт под ним, Without origin, и в него попасть не получается, потому что при движении курсора меню дёргается, и пункты скачут то туда, то сюда.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D Понял поправлю завтра сегодня на работе

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D исправил :)

**Comment by Qwertyus3D** [comment]
Пункт WAD в меню Import всё ещё пропадает.

**Comment by ToxicHolyGrenade** [comment]
А как насчет основного движка Quake, а также движка Half-Life 0.52, случайно?

**Comment by UnrealKaraulov** [comment]
> А как насчет основного движка Quake, а также движка Half-Life 0.52, случайно?

Не знаю, я добавлял поддержку BSP29, это он и есть?

**Comment by ToxicHolyGrenade** [comment]
Видите ли, причина, по которой я упомянул об этом, заключается в том, что всякий раз, когда я редактирую карты, которые были созданы исключительно для движков Quake или Half-Life 0.52, что-то не так, и это не то, что я обычно испытываю в прошлых версиях BSPGuy с самого начала. . Вы можете указать, где я ошибаюсь, и я предоставлю скриншоты и BSP-файлы того, о чем говорю.

Это также имеет отрицательный эффект при игре на самих картах.

[New WinRAR ZIP archive.zip](https://github.com/UnrealKaraulov/newbspguy/files/10509390/New.WinRAR.ZIP.archive.zip)

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade I don't know lightmap format in this files, without help I can't add support it.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Я так понимаю, там палитра Quake вроде как.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D может быть, если так, то как узнать что там палитра quake, вот в чем вопрос :(

Дать что ли возможность выбрать? но хотелось бы автоматически это определить

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Я, по видимому, ошибся. Ситуация, по всей видимости, такая: у нас есть BSP29 - это как бы карты Кваки, и BSP30 - это карты ХЛ. Но BSP29 зависит от компилятора. И есть карты ХЛ, которые скомпилены старыми компиляторами. У них в заголовке файла BSP29, соответственно. При этом ХЛ от Кваки отличается форматом лайтмапы. Там, я так думаю, должно довольно просто определяться, вроде как там есть (если я не ошибаюсь) лумпы, в которые пишутся сведения о текстуре, и вот размер этих лумпов должен отличаться. Ну или вообще размер лайтмапы разный. Т. е. по признакам размера лайтмапы или этих лумпов и можно определить, карта ли это Кваки, или карта ХЛ, скомпиленная старым компилятором. Если нужен косвенный признак, то у карт Кваки в свойствах ворлдспавна есть графа worldtype, которой нету у карт ХЛ. Ну и вообще у текстур Кваки, наверное, палитра специфическая, хотя это не будет надёжный признак, наверное.

**Comment by Qwertyus3D** [comment]
Хотя вот в Кваке есть ещё BSP-модели типа аптечек, патронов и т. п. У них не прописан worldtype в ворлдспавне.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade in latest build problem with read this maps solved ?

**Comment by KarKarKarKarkarkar** [comment]
пока не нашел игр goldsrc/bap29 движка карты которых не открывались бы

прикрою еа время и этот issue, как появятся еще игры которые могут поддерживаться то открою

xash открываются но там не вся инфа о фейсах извлекается и местами текстуры съехавшие, но это буду исправлять чуть позже

**Comment by ToxicHolyGrenade** [comment]
> @ToxicHolyGrenade in latest build problem with read this maps solved ?

...What?
