### ISSUE TITLE
[NOT FIXED] Unable to two Right-Click the Entities in the Entity Report Menu

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [UnrealKaraulov/newbspguy#57]
Ran into another issue regarding the entity report menu. I am supposed to right-click the entities within the list in order to delete them, but nothing happens.

Sometimes it comes up, but other times not for some reason.

**Comment by Qwertyus3D** [comment]
Sometimes it requires to click a second time. Or select a menu item before right-click. Or select some entity in the viewport.

**Comment by ToxicHolyGrenade** [comment]
@Qwertyus3D Tried that method already, but it doesn't always work unfortunately.

**Comment by Qwertyus3D** [comment]
It's not a method, it's how it work with https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2022.12.22_12-22. The issue does exist.

**Comment by ToxicHolyGrenade** [comment]
Method or not, it's a poor execution. Sorry for the bluntness, but this is the thing; if something barely works, it still must be overhauled.

**Comment by Qwertyus3D** [comment]
I checked it again with latest nightly build, and right-click menu seem to not work after first click on menu item ONLY if another menu is already popped-up after right-clicking on another entity. In any other case menu works properly after a single click. But after second click it works always.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D не пойму я только что проверял и вроде бы кликает с первого раза, что вообще не так ? :)

**Comment by Qwertyus3D** [comment]
Я заметил только, что если менюшка уже вызвана ранее, и ты кликаешь на другом пункте списка, то этим первым кликом выделяется щёлкнутый пункт, и только на второй клик можно вызвать меню. А так всё работает с первого клика. Я лично бага не вижу, как он описан изначально, что, мол, меню не вызвывается ни в какую.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D а вот это я не знал, ну щас тоже попробую исправить

**Comment by Qwertyus3D** [comment]
Нашёл проблему. Если самый нижний пункт в списке щёлкаешь, то на нём меню совсем не появляется.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D похоже это такое поведение у ImGUI, блокирует ввод когда открыто всплывающее окно.

**Comment by UnrealKaraulov** [comment]
@ToxicHolyGrenade
Если найду как заставить всплывающие окна не блокировать ввод, то исправлю а пока что закрываю. 
На данный момент первый клик правой мышью работает с первого раза, нужно выбрать что-то в всплывающем окне или один раз кликнть в окно. 
Такое поведение у IGMUI к сожалению https://github.com/ocornut/imgui/issues/718

**Comment by Qwertyus3D** [comment]
Но то, что последний пункт списка не работает, это объективно баг. И не связано с наложением окон.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D не знал что такой баг есть :) исправил!
