### ISSUE TITLE
Add support for model submodels

### ISSUE THREAD

**Issue by Psycrow101** [UnrealKaraulov/newbspguy#58]
Недавно здесь появилась поддержка студио моделей и это очень крутая функциональность! К сожалению, на данный момент модель не отображается полностью, а только одна часть первой бадигруппы. Параметр "body" также не учитывается.

Я попробовал заменить в [BspRenderer.cpp](https://github.com/UnrealKaraulov/newbspguy/blob/newbspguy_master/src/editor/BspRenderer.cpp#L2010)
```c++
renderEnts[i].mdl->DrawModel(0, 0, 0);
```
на
```c++
// renderEnts[entIdx].modelBody = atoi(ent->keyvalues["body"].c_str());

auto* phdr = renderEnts[i].mdl->m_pstudiohdr;
auto* pbodypart = (mstudiobodyparts_t*)((unsigned char*)phdr + phdr->bodypartindex);
for (int bg = 0, body = renderEnts[i].modelBody; bg < phdr->numbodyparts; bg++)
{
    renderEnts[i].mdl->DrawModel(bg, body % pbodypart->nummodels, 0);
    body /= pbodypart->nummodels;
    pbodypart++;
}
```

И это работало до последних двух коммитов. Сейчас модели на карте в большом количестве очень сильно сжирают ФПС и может быть лучше добавить опцию для их отключения?

**Comment by Qwertyus3D** [comment]
Опция для статичной анимации (по первому кадру) тоже не помешает. Снизит нагрузку, но модели будет видно. В идеале, ещё добавить поддержку выбора нужной анимации модели через FGD. А также поддержку выбора нужных субмоделей (головы учёных) и скинов. В FGD это всё прописывается - sequence, body, skin.

Ну и я отписался на КСМ, сейчас есть баг "перепрыгивания" моделей с одной энтити на другую. На своём месте модель не рисуется, зато рисуется вместе с другой моделью в точке расположения другой энтити. До трёх моделей в одной точке.

**Comment by Qwertyus3D** [comment]
Ещё не помешает Loading при загрузке карты, а то с моделями пауза бывает довольно большая, и если карта расположена в обратной стороне от ракурса спавна, то вообще непонятно, что сейчас творится.

**Comment by Psycrow101** [comment]
Тогда еще colormap можно добавить

**Comment by UnrealKaraulov** [comment]
@Psycrow101 @Qwertyus3D Пока ожидайте, я уже подготовил вчера базу для поддержки всех этих параметров ну там включение и отключение рендера моделей/анимации, вечером постараюсь протестировать все. (вроде как все ключи из fgd/сущностей учел)

Меня немного беспокоит вопрос в body.

Сейчас если ничего не трогать, то я так понял у меня есть набор subbody и набор мешей для каждого из subbdoy. 

Есть функция принимающая два числа, SetBodyGroup(body, value), и вот я не могу въехать почему у нее два параметра, если первый выбирает body, то я пока не могу сообразить что даёт второй.

**Comment by UnrealKaraulov** [comment]
Так же теперь крайне необходимая функция это проверка находится ли объект в поле зрения, из-за рендера моделей теперь это кажется очень нужной вещью, тогда ФПС станет куда лучше во многих случаях, если не обновлять модель и не рисовать ее, так же можно будет и ко всем другим моделям применить.

**Comment by Psycrow101** [comment]
@UnrealKaraulov значение body определяет совокупность комбинаций бадигрупп и мешей. У модели может быть, к примеру, 2 бадигруппы по 6 мешей в одной группе и 8 в другой. Первая бадигруппа пускай будет отвечать за головы, а вторая - за тела. В итоге модель содержит 48 (6 * 8) комбинаций голов и тел. Значение body как раз лежит в диапазоне из 48 значений.

Если нам нужно назначить вторую голову с третьим телом, то нужно вызвать SetBodyGroup(0, 2) и SetBodyGroup(1, 3). body в этот случае будет равен 20 (3 * 6 + 2).

**Comment by UnrealKaraulov** [comment]
ну допустим, а что тогда значит значение value в SetBodyGroup(body, value)

или оно если body поменять, то понятно что будет, а что будет если value ставить отличное от нуля?

**Comment by UnrealKaraulov** [comment]
в общем вечером разберусь что там такое)

**Comment by Psycrow101** [comment]
value - это номер меши в бадигруппе. В первом сообщении я привел код как его определять по значению body.

**Comment by UnrealKaraulov** [comment]
если придется каждый кадр обновлять буфер модели, то ФПС точно упадет в 0, в любом случае вечером буду проверять, можно какото пример карты или модели из hl1/cs16 (других игр на ПК нет) где не отрисовывается целиком?

**Comment by Qwertyus3D** [comment]
Абсолютно любая карта с учёными.

**Comment by Qwertyus3D** [comment]
c1a0 хотя бы. Если подключен Свен-Кооп за базу, то там ещё и модели ХДшные.

**Comment by UnrealKaraulov** [comment]
Ну у меня SveenCoop нет если честно то я даже не в курсе что это за игра как ни странно))))

**Comment by Qwertyus3D** [comment]
Вот баг, о котором я писал. Некоторые модели не отрисовываются на своих местах, но рисуются вместе с другими:
![model0](https://user-images.githubusercontent.com/98685264/209436303-0c4b4c1d-df78-4d9a-9d76-21be2e152c1c.jpg)
![model1](https://user-images.githubusercontent.com/98685264/209436307-ac387fe0-7ee4-43b0-8087-d0150f42170a.jpg)
Пока не ткнёшь в пустое место, где должна быть энтить, и пока она не выделится, нет никаких признаков что там вообще что-то есть.

Свен из Стима ставится, как отдельная игра, бесплатно, вроде. Или, может, требует ХЛ, это точно не помню.

**Comment by Qwertyus3D** [comment]
Свен - это тот же ХЛ + Блюшифт + Опфор + ещё куча всего сразу. Рассчитано на совместное прохождение, но некоторые миссии можно и одному пройти. Там, где прохождение не требует взаимодействия с другими игроками.

**Comment by UnrealKaraulov** [comment]
Я скачивал потом забыл для чего, и удалил))) надо будет ещё раз скачать для тестов. 

Да сейчас модели будут рисоваться "абы как"

**Comment by UnrealKaraulov** [comment]
потому что я вообще не знаю как они рисуются, всмысле я ведь забыл добавить кое что важное в код, даже не представляю как оно работает сейчас :) Но я уже вчера вечером почти все пофиксил и сегодня вечером планирую доделать

**Comment by UnrealKaraulov** [comment]
@Psycrow101 @Qwertyus3D обновил, кажется все работает на первый взгляд :)

**Comment by Qwertyus3D** [comment]
Круто, реально работает. Даже мины правильно размещаются, работает выбор боди и секвенсов. Из недоработанного - рендерфлаги у моделей, типа:
```
$texrendermode "Cabin_G.bmp" "masked_solid" 
$texrendermode "GlassChrome.bmp" "flatshade" 
$texrendermode "GlassChrome.bmp" "chrome" 
$texrendermode "GlassChrome.bmp" "additive" 
```
Включая возможность одновременного применения хрома и аддитива. И ещё у Ксаша и Свена есть рендерфлаг "fullbright", который также может быть добавлен поверх других.

Ну и на закуску, пока не работает вставка моделей через другие энтити, типа env_sprite / cycler_sprite.

**Comment by Psycrow101** [comment]
Кроме вьюверов есть сорцы хорошего рендерара с этими флагами
https://github.com/hzqst/MetaHookSv/tree/main/Plugins/Renderer

**Comment by UnrealKaraulov** [comment]
Наверное слишком сложно будет перенести, да и не знаю увеличится ли фпс.

Флаги читаются и chrome и flatshade, но в общем когда я подключаю освещение, фпс падает минимум в 2 раза, это слишком уж затратно. Пока ничего изменять не буду, может быть когда-нибудь возьму другой рендер приспособлю. Так хоть как-то но работает :)

**Comment by Qwertyus3D** [comment]
Рендер Ксаш-мода брать можно, в теории. :) Там оптимизация под высокополигональные модели и всё, что нужно для ХЛ.

**Comment by UnrealKaraulov** [comment]
Ну я смотрел и тот и тот, но пока не знаю как перенести, если честно пока что не хочется еще раз ту же самую работу проделывать)

**Comment by Qwertyus3D** [comment]
Я пока не понял, что произошло, но почему-то у меня после установки нового билда стали внезапно загружаться низкополигональные халфовские модели на карту, вместо моделек из Свен-Коопа. И я как-то даже немного не врубаюсь, откуда эти лоу-поли модели вообще берутся. Могу предположить, что программа сама определяет наличие стимовской ХЛ и берёт их оттуда, несмотря на прописанные настройки.

**Comment by UnrealKaraulov** [comment]
А, я добавил в пути поиск файлов из папки где находится карта...
Возможно перенесу его в конец списка тогда приоритеты изменятся.

Ещё чёт на ксаш моделях падает, буду думать чего не читает их, может там увеличенные лимиты какие-то.

Щас ещё разгребать бардак что натворил когда добавлял поддержку новых и старых карт, слегка проблем скопилось, функционал очистки и редактор карты освещения придется слегка переделать, и т.п

**Comment by UnrealKaraulov** [comment]
На счёт рендера, я не знаю в оптимизациях, возможно можно ускорить, но я не разбираюсь сейчас могу только хуже сделать 🤣 

И переносить из других исходников лень пока что.

**Comment by UnrealKaraulov** [comment]
Ещё может быть возможно ускорить не загружая одну и ту же модель несколько раз, а использовать уже существубщую, просто рисовать ее несколько раз, проверю это сегодня

**Comment by Qwertyus3D** [comment]
Вообще, это хорошая опция, в плане подгрузки ресурсов из директории с текущей картой. Но, возможно, нужно тогда сделать какую-то опцию, которая бы регулировала это. Потому что в целом - это хороший ход. Но стоит оставить и возможность отключения.

**Comment by Psycrow101** [comment]
В xash3d моделях как минимум новые сегменты добавлены для поддержки Vertex Weights

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D в последнем обновлении https://github.com/UnrealKaraulov/newbspguy/commit/e4e1e9c737a35b8d6981ea6252a2e0185faaebf6

Сделал что бы этот путь использовался автоматически но в крайнем случае (если в других не найдено ничего)

Переделал загрузку моделей, теперь вместо того что бы грузить по 100500 моделей одинаковых, загружается единственная модель, и просто рисуется столько сколько нужно раз.  (Это ускорило фпс, но не во всех случаях, например если используется одна и та же модель, с разными параметрами, может слегка снизится, но в общем то увеличивает неплохо фпс, но это надо тестировать)

**Comment by Qwertyus3D** [comment]
Самый свежий билд [Speedup clipnodes, revert some changes (EPSILON)](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3807645518) поломал отрисовку оптимизированных энтить, например, trigger_multiple (у которых часть хуллов удалена). Теперь прога их не показывает совсем. И ещё я заметил рандомные крэши программы, без видимых причин. Просто падает спустя какое-то время.

**Comment by Qwertyus3D** [comment]
![hulls](https://user-images.githubusercontent.com/98685264/210091883-dc08fcbe-6139-4154-bdcc-06f998e56c3e.jpg)
Я вот про такие энтити. Предыдущий билд их рисует, и крэшей вроде нет.

**Comment by Qwertyus3D** [comment]
Ещё клик на точечных энтитях вызывает урезанное меню, только пункты Hide и Properties. Это с билда [Fix LIGHTMAP corrupted. Fix content menu, etc.](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3786416995).
![HidePro](https://user-images.githubusercontent.com/98685264/210093508-79986748-7704-4ecb-857b-2a3091ecf1a5.jpg)

**Comment by Qwertyus3D** [comment]
Вижу, что отрисовка клипнодов заработала. Менюшка пока ещё обрезанная.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D спасибо за инфу! 

Ускорял загрузку клипнодов различными способами, если щас все работает то оставлю как есть, скорость куда выше чем была раньше.

Краши остались? или тоже пропали? там из-за того что в нескольких потоках сделал загрузку, могли быть ошибки загрузки текстур и краш драйвера.

**Comment by Qwertyus3D** [comment]
Вроде стабильны последние билды.

**Comment by Qwertyus3D** [comment]
Фикс проблемы с оптимизированными энтитями неполноценный вышел. При загрузке карты энтити рисуются (точнее, их клипноды), но стоит выделить такую энтить, как она снова перестаёт отрисовываться, насовсем.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D и правда, посмотрю что можно сделать

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D пофиксил! это когда добавлял кэширование клипнодов не усмотрел :)

**Comment by Qwertyus3D** [comment]
Опять поломался экспорт моделей с карты. Последний билд, на котором не вылетало [Ignore pickObject for hidden ents!](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3786540491).

**Comment by UnrealKaraulov** [comment]
> Опять поломался экспорт моделей с карты. Последний билд, на котором не вылетало [Ignore pickObject for hidden ents!](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3786540491).
понял спасибо за инфу

https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2022.12.31_09-38

тут тоже не работало?

**Comment by UnrealKaraulov** [comment]
А все вижу, крашит, странно вроде как тогда тестил все норм было :)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D кажись пофиксил :)

**Comment by Qwertyus3D** [comment]
Починилось. И теперь сохраняется освещение, а до этого было без освещения.

**Comment by Qwertyus3D** [comment]
Есть проблема с моделями и механизмом субмоделей. Началось примерно с момента, когда ты сначала сделал подмену рабочей директории с ресурсами на верхнюю папку по отношению к карте, а потом вернул назад приоритет на указанную папку игры. Теперь, во-первых, неправильно субмодели отрисовываются, во-вторых - анимации. Тупо рисуется одно и то же тело у всех учёных и одна и та же анимация, для всех моделей, находящихся на карте. И если начинаешь у одной модели менять тип тела или анимацию, то изменение происходит со всеми остальными моделями на карте. Последний билд с изначально рабочей схемой - [More verbose logs](https://github.com/UnrealKaraulov/newbspguy/actions/runs/3798325688).

**Comment by UnrealKaraulov** [comment]
А, это когда я кэширование модели сделал скорее всего началось. Я тогда и думал что может что-то плохое случится, ну в общем постараюсь исправить завтра утром

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D да проблему вижу, сегодня пару других багов фиксил, завтра уже сделаю модели назад.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D исправил вроде как, стало лучше?

**Comment by Qwertyus3D** [comment]
Стало лучше :) но не исправилось до конца. Если на карте есть 2 одинаковых модели учёного (например, Slick), то им присваивается и анимация одинаковая.

**Comment by UnrealKaraulov** [comment]
Ну понял просто фокус с кэшированием теряется если создавать всем по модели :) Так хоть фпс немного выше. Ну ладно раз так надо то сделаю что бы и в этом случае создавалась модель.

**Comment by Qwertyus3D** [comment]
Ну, я анимацию заморозил, и не парюсь :)

**Comment by Qwertyus3D** [comment]
Я вижу, ты сделал поддержку отрисовки моделей, вставленных через env_sprite. Но тут возникает проблема. Энтить точечная, а отрисовывается только модель. Кубик энтити не рисуется. Из-за чего зачастую невозможно выделить энтить. Т. к. модель по клику не выделяет энтить, а сама энтить маленькая, и непонятно, куда тыкать, чтобы её найти, особенно, когда модель большая. Или если сделан в одной точке "бутерброд" из нескольких энтить, тогда невидимую выделить нереально. В связи с чем я бы всё-таки предложил рисовать контуры любых энтить, относящихся к моделям (как обычно, синенькими линиями, когда они не выделены).

**Comment by UnrealKaraulov** [comment]
> Я вижу, ты сделал поддержку отрисовки моделей, вставленных через env_sprite

@Qwertyus3D я не делал, она или должна быть или нет, не важная какой класснейм у сущностей :) :)

Я так понял надо кубик рисовать, и какую-то нить к модельке что бы разобрать где чья?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov В случае, когда выводится модель, то контур энтити тоже отрисовывать, но без заливки граней.
![cube](https://user-images.githubusercontent.com/98685264/210526327-8553f380-6c1b-4899-8e8a-e16884b2eb2c.jpg)
Вот сейчас энтить выделена и виден жёлтый контур. А нужно, чтобы такой же контур , только синий, был, когда энтить не выделена.

**Comment by KarKarKarKarkarkar** [comment]
@Qwertyus3D а что я тут не доделал? Цвет поменять надо просто?

**Comment by Qwertyus3D** [comment]
Имелось в виду, что если моделька не выделена, то у неё не видно ббокса энтити. Вообще нет куба-контура вокруг модели (который можно было бы рисовать синим цветом, пока модель не выделена).

**Comment by KarKarKarKarkarkar** [comment]
А ну это можно думаю mins/maxs получить при загрузке модели не должно быть проблемой. Посмотрю что можно сделать

**Comment by Qwertyus3D** [comment]
Так а зачем получать какие-то мин-максы, если границы энтити либо 16х16х16 дефолтные, либо указаны в FGD? Вот те границы, которые указаны в FGD, их и отрисовывать. Моделька же просто визуализирует энтитю.

**Comment by UnrealKaraulov** [comment]
> Так а зачем получать какие-то мин-максы, если границы энтити либо 16х16х16 дефолтные, либо указаны в FGD? Вот те границы, которые указаны в FGD, их и отрисовывать. Моделька же просто визуализирует энтитю.

Я думал тебе надо что бы вокруг модели была рамка ))))

**Comment by Qwertyus3D** [comment]
Ну, может, в идеале было бы лучше, чтобы к модели рамка была привязана, для удобства. Вопрос главным образом в том, чтобы было удобно манипулировать энтитью. Чтобы было понятно, куда тыкать, чтобы выделить энтить. Потому что моделька может быть вставлена, например, через env_sprite и т. п. Моделька может быть какой-нибудь огромной фигнёй, а ты пытаешься в неё тыкать, чтобы выделить, и не попадаешь в саму энтить.

**Comment by KarKarKarKarkarkar** [comment]
Я понял ага это очень неудобно) тогда уж лучше сделаю что бы выделялось кликом по модели

**Comment by UnrealKaraulov** [comment]
@Psycrow101 @Qwertyus3D 

В последнем билде можно выбирать кликом по моделям, и если отключить рендер моделей то будет рисоваться куб размером с модель.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Недоделато, рано закрыл.

![subcube](https://github.com/UnrealKaraulov/newbspguy/assets/98685264/4027c0e1-e754-4d64-8d2f-97f27d185111)

Границы модели некорректно определяются, когда модель просто поделена на части или состоит из субмоделей.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Я ещё предложил бы эту рамку отрисовывать синим цветом, пока модель не выделена, жёлтый ведь цвет у выделенных энтить используется.

**Comment by Qwertyus3D** [comment]
Вот эту тему надо бы открыть, рамки моделей ещё не фурычат, как надо.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D а я забыл чето про эти рамки)
