### ISSUE TITLE
Не работает сортировка в окне Entity Report

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#6]
При выборе из выпадающего списка какого-либо класса entity не происходит фильтрация списка по данному классу, список остаётся неизменным.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D спасибо удалил ненужный код который это делал :)

https://github.com/UnrealKaraulov/newbspguy/commit/3ecb55295e4f4d9c1acbc93cfb87f664161cb6a4
