### ISSUE TITLE
Widgets state

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#60]
Там промежду делом возникла проблема, что программа не восстанавливает состояние окон Settings и Keyvalue Editor. Раньше, если при закрытии программы они были открыты, то и после перезапуска они отображались, в свёрнутом, либо развёрнутом виде. А теперь всегда закрыты после перезапуска. Settings уже давно не открывается, а Keyvalue Editor перестал открываться в недавних билдах. И ещё я просил о том, чтобы после нажатия кнопки "Apply settings" виджет Settings тоже открывался заново, а не закрывался насовсем. Просто лично мне эти окна всегда нужны под рукой, а не закрытые, чтоб каждый раз в меню за ними лезть.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D а я просто забыл упомянуть что опцию "Сохранить состояние окон" добавил в настройки. То есть что бы был выбор, открывать все окна при запуске, или нет.

**Comment by UnrealKaraulov** [comment]
На счет Apply Settings думаю можно сделать

**Comment by Qwertyus3D** [comment]
Опция есть, и галочка на ней у меня стоит, но виджеты после перезапуска не показываются при этом (конкретно эти два, а остальные - показываются).

**Comment by UnrealKaraulov** [comment]
По моему я специально делал что бы настройки при запуске не открывались, посмотрю завтра

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D настройки я специально сделал что бы не открывались, при загрузке можно краш поймать если настройки будут открыты и что-нибудь там жать. 

keyvalue и goto окна теперь должны сохраняться :)

**Comment by 0x4E69676874466F78** [comment]
У меня на винде виджеты не восстанавливаются, на оригинальном bsgguy всё работало. 
В особенности надо Debug info, Keyvalue editor, Face editor.

**Comment by Qwertyus3D** [comment]
У меня все виджеты нормально работают, их состояние сохраняется в файле imgui.ini. Возможно, это проблема с поиском пути к файлу, наверное, должно быть исправлено в новых билдах.

**Comment by UnrealKaraulov** [comment]
@0x4E69676874466F78 Face Editor и LightMap Editor не могут быть открыты по умолчанию т.к по умолчанию всегда выбор объектов а не фейсов.

Остальное восстанавливается если включено в настройках.

**Comment by 0x4E69676874466F78** [comment]
У меня до этого файла чтение даже не доходит. 
Я заметил в коде форка и оригинала есть расхождение по части этого файла:

https://github.com/wootguy/bspguy/blob/63086b3f366cf8b26dee9ead63156d060d2de3b5/src/editor/Gui.cpp#L18

https://github.com/UnrealKaraulov/newbspguy/blob/54879b5d1938f74925b20200886798c6fef61b84/src/editor/Gui.cpp#L39

**Comment by 0x4E69676874466F78** [comment]
Галку поставил, сами открытые окна восстанавливаются, ~~но позиции у них не те что были при закрытии.~~ Хотя ресайз окна помог.

**Comment by UnrealKaraulov** [comment]
@0x4E69676874466F78 то есть первый раз координаты окон не сохранились, после изменения размеров сохранились?

**Comment by 0x4E69676874466F78** [comment]
@UnrealKaraulov да, при изменении размеров главного окна (самого редактора), не окошка виджета (его изменение ничего не даёт). Причём почему-то даже не всегда ресайз окна помогает.

**Comment by UnrealKaraulov** [comment]
@0x4E69676874466F78 @Qwertyus3D в последних версиях имеются какие-то проблемы с сохранением окон или все исправлено?

Я просто проблем найти не могу, если что-то будет, маякните еще раз)
