### ISSUE TITLE
[Crash]merge map and import bspmodel(native)

### ISSUE THREAD

**Issue by PersonForever** [UnrealKaraulov/newbspguy#63]
Crash......

**Comment by PersonForever** [comment]
[NightBuild_2023.01.14_05-27] This version

**Comment by PersonForever** [comment]
I want to know can i export the obj with clipnodes or export .map with clipnodes

**Comment by PersonForever** [comment]
export clipnodes as bsp brush

**Comment by PersonForever** [comment]
When I import the bsp model as func_breakable, it worked but when i touch the bsp model that I imported I will stuck in the game.

**Comment by PersonForever** [comment]
Can i import the bsp model and removed the sky or I will stuck in the game when i touch the bsp model

**Comment by UnrealKaraulov** [comment]
@ManevogerKrCode native bsp import fixed in latest build, 
But "merge maps" — I can't test at this moment, because no has Sven Coop installed :(

But firstly need setup all valid path to game and fgd/wad files.

**Comment by UnrealKaraulov** [comment]
@ManevogerKrCode Map merge widget crash also solved in latest build!
