### ISSUE TITLE
Can't move camera with "wasd" on Linux

### ISSUE THREAD

**Issue by ghost** [UnrealKaraulov/newbspguy#64]
Built from last commit newbspguy 

Ubuntu 22.04

**Comment by UnrealKaraulov** [comment]
@gabuch2 at all maps ? 

Just no effect when press 'wasd' buttons ?

**Comment by ghost** [comment]
Hello, I tested with Counter-Strike's `de_dust2` and Sven Co-op 5's `desertcircle`, both were showing the same behavior.

This doesn't happen with wootguy's bspguy. 

If you need more information just tell me.

**Comment by UnrealKaraulov** [comment]
@gabuch2 you can increase move speed in settings

**Comment by ghost** [comment]
Hello, adjusting the move speed in settings had no effect.

**Comment by Nord1cWarr1or** [comment]
Same on arch-based distro
@UnrealKaraulov

**Comment by UnrealKaraulov** [comment]
I can't test on linux now, I can tried to install VM on Windows

**Comment by UnrealKaraulov** [comment]
@gabuch2 @Nord1cWarr1or all other functional works correctly ? (Move entities/GOTO window/FPS counter)

**Comment by Nord1cWarr1or** [comment]
Checked on the latest version of the program. I can't move, can't select any entity with the left mouse button. All I can do is rotate the camera with the right mouse button.

I also checked the original bspguy, no such problems there

**Comment by UnrealKaraulov** [comment]
imgui works? (menu items can be clicked, selected, etc?)

**Comment by Nord1cWarr1or** [comment]
> imgui works? (menu items can be clicked, selected, etc?)

yep, menu, widgets works

**Comment by UnrealKaraulov** [comment]
> yep, menu, widgets works

https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.05_17-32

You can now open DEBUG widget and test mouse (coordinates, left/right button, and current time)

**Comment by UnrealKaraulov** [comment]
@gabuch2 @Nord1cWarr1or in latest build https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.06_05-56 , keyboard issue fixed ?

**Comment by Nord1cWarr1or** [comment]
> @gabuch2 @Nord1cWarr1or in latest build https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.06_05-56 , keyboard issue fixed ?

no

**Comment by Nord1cWarr1or** [comment]
![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/4921490f-d7b9-45c6-bb5f-8fc29b7c6cdd)
When I left-click, this window shows this, but no entities are selected

**Comment by UnrealKaraulov** [comment]
left = 1 when you do click ?

**Comment by Nord1cWarr1or** [comment]
> left = 1 when you do click ?

yep

**Comment by Nord1cWarr1or** [comment]
https://github.com/UnrealKaraulov/newbspguy/assets/47604048/41652848-9e68-48d2-83f5-d7e3288221e3

**Comment by Qwertyus3D** [comment]
Напишу здесь, последний билд (№437) не до конца пофиксил баг камеры, возникший с билда №432 - движение камеры по WASD идёт рывками, на несколько юнитов проходит вперёд и останавливается, нужно снова отпускать клавишу и повторно нажимать.

Пофикшено в №438

**Comment by KarKarKarKarkarkar** [comment]
I think imgui can't detect window focus. if main window not focused or focused any widget, WASD movement is locked in this fork

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or keyboard works for Widgets? (You can enter text in settings, etc?)

yes it works

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or @gabuch2 please try latest build.

**Comment by Nord1cWarr1or** [comment]
@UnrealKaraulov still not works

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or @gabuch2 

fixed in latest build (something bad in vec3 struct)

**Comment by Nord1cWarr1or** [comment]
confirm
