### ISSUE TITLE
Добавить поддержку верного масштабирования моделей и текстур для Xash3d

### ISSUE THREAD

**Issue by CASPER-X69X** [UnrealKaraulov/newbspguy#65]
Вот как это выглядит на данный момент. 

Ознакомиться с ключевым форком можно тут
https://github.com/FWGS/xash3d-fwgs

Ознакомиться с модом (если быть точнее сдк) на чем был сделан скриншот

https://github.com/SNMetamorph/PrimeXT

![image](https://user-images.githubusercontent.com/79316607/221310520-dcbb1b15-0b40-4804-82a3-b38d0a8d1b9f.png)

**Comment by Qwertyus3D** [comment]
@CASPERX69XSOFT  Надо было написать, о каком параметре энтити идёт речь, который должен считываться из модели. Если речь идёт о возможности масштабировать модель, как в Спирите. Size, видимо, если я не ошибаюсь.

**Comment by UnrealKaraulov** [comment]
Я щас не очень активно обновление делаю :(

Выдохся уже :)

Достаточно тяжело одному над этим работать:(

Ушел в Warcraft 3 пока что ....

**Comment by UnrealKaraulov** [comment]
@CASPERX69XSOFT можно карту для примера? А то у меня уже нет их)

Там вроде как для XASH нужно менять параметр TEXTURE SAMPLES в настройках, с 16 на что-то другое. 

Если карта будет скажу точно

**Comment by CASPER-X69X** [comment]
[Desktop.zip](https://github.com/UnrealKaraulov/newbspguy/files/13559373/Desktop.zip)

Вот тестовая карта, там два формата ентить которые понимает ксаш env_model и env_static, так же стоят двери в дверном проеме для понимания как нарушилось масштабирование

**Comment by UnrealKaraulov** [comment]
@CASPERX69XSOFT сделал https://github.com/UnrealKaraulov/newbspguy/commit/f76cd179f61dcbe4d5fa968f02d631f839a163e2

![image](https://github.com/UnrealKaraulov/newbspguy/assets/88730285/8cc601b4-86db-4205-ba09-bbf2e06607a7)

**Comment by UnrealKaraulov** [comment]
https://github.com/UnrealKaraulov/newbspguy/commit/f76cd179f61dcbe4d5fa968f02d631f839a163e2
