### ISSUE TITLE
Program crashes when invoked in cmd.exe

### ISSUE THREAD

**Issue by mfaizsyahmi** [UnrealKaraulov/newbspguy#67]
The program just crashes when attempting to run via cmd.exe. Hence I couldn't test if the CLI interface is still available for this fork.

**Comment by UnrealKaraulov** [comment]
@mfaizsyahmi how to reproduce this error?

1. run cmd.exe
2. enter bpsguy.exe path
3. press enter

works, starting GUI without map.

**Comment by UnrealKaraulov** [comment]
@mfaizsyahmi in latest build this issue is fixed.
