### ISSUE TITLE
Update CLI with new features

### ISSUE THREAD

**Issue by mfaizsyahmi** [UnrealKaraulov/newbspguy#68]
Can't test for the extent of this as implemented at the moment because of #67.

I'd like to have some of the new export features available via the command line interface. Examples:

1. Exporting/Importing WADs
2. Exporting/Importing brush model BSPs (mostly exporting)
3. Exporting/Importing lumps in general
4. A way to export/merge a delta of changed lumps, so you have only the added/changed/removed point or brush entities written in said lumps
    - Focus on added brush entities as their unique model \#s are easy to enumerate
    - Later on could be expanded to point entities. A convention is needed to remove entities during merge. Maybe have a special entity e.g. `bspguy_delete` occupying the same origin as, or targeting, the entity name/class to be deleted.

No. 4 is a stretch goal even for me, so I'll be glad to have at least the first 2 items.

p.s. thank you for the great work on this program so far. It's a literal game-changer.

**Comment by UnrealKaraulov** [comment]
@mfaizsyahmi I no have time for this, maybe sometime later... :(

**Comment by UnrealKaraulov** [comment]
@mfaizsyahmi I can do something of this if I can find the time ...)

**Comment by UnrealKaraulov** [comment]
@mfaizsyahmi Updated https://github.com/UnrealKaraulov/newbspguy/commit/702ed71b2a0dd666ab60d0972899fb0a7ff65ab6 

Need more?
