### ISSUE TITLE
Merge verts - optimizing settings option

### ISSUE THREAD

**Issue by EmmaCarro** [UnrealKaraulov/newbspguy#69]
Some maps get corrupted if this option is checked and doing an Optimize. It will destroy clipping on the map, but it is unnoticeable at first glance. But you can see when it happens that some surfaces start flickering, specially the worldspawn boundary clips that are light blue colored, sorrounding the map. 
When this happens, the maps play just fine ingame, with an occasional crash that very rarely happens, without error message.
But the issues are seen when merging the maps. The maps having this problem will be merged and get brush models stretched across the map from the point of origin to infinity. Opening them with the old bspguy is the only way to see that, because newbspguy will crash when trying to open these merged maps, and ingame the maps will crash on load with a Bad extents error.
After many trials and errors, I pinpointed the issue to this "Merge verts" setting. 
If it is working as intended, I don't know, but at least a warning should be placed about this.

**Comment by UnrealKaraulov** [comment]
@EmmaCarro thanks, added warnings for this option!
