### ISSUE TITLE
В виджете Debug дублируются поля Map и Selection

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#7]
Если в виджете Debug свёрнуто поле BSP Tree, то под ним добавочно отображаются поля Map и Selection. Если BSP Tree развёрнуто, то Map и Selection не дублируются.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D удалил в https://github.com/UnrealKaraulov/newbspguy/commit/1bdaded3dd58383994c010e8214f520fd24e81f6
