### ISSUE TITLE
Widget "Go to" is broken

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [UnrealKaraulov/newbspguy#71]
У меня не работает перемещение к энтити под нужным номером. Вбиваю номер и он сбрасывается на 0.

**Comment by UnrealKaraulov** [comment]
Блин как же вы мне все дороги)))....))  🥲 

ну ладно как-нибудь гляну, хоть уже и не хочется заниматься этим редактором (

**Comment by Qwertyus3D** [comment]
> Блин как же вы мне все дороги)))....)) 🥲
> 
> ну ладно как-нибудь гляну, хоть уже и не хочется заниматься этим редактором (

Ну, ты же сделал шикарный редактор. А забросил насовсем рано, баги-то остались. Хотя бы баги пофиксить. :)

**Comment by UnrealKaraulov** [comment]
@0x4E69676874466F78 @Qwertyus3D  pofixil eto
