### ISSUE TITLE
Copying face id of selected faces

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [UnrealKaraulov/newbspguy#72]
Насколько сложно добавить горячую клавишу копирования в буфер обмена face id выделенных граней?

**Comment by UnrealKaraulov** [comment]
@0x4E69676874466F78 отображение информации о выделенном объекте есть в DEBUG окне , могу еще в GOTO добавить

**Comment by 0x4E69676874466F78** [comment]
@UnrealKaraulov мне бы именно скопировать в буфер, в дебаге я знаю, но мне приходится руками переписывать идентификаторы, что неудобно. Либо куда-нибудь в файл написать эти выбранные идентификаторы.
Масштаб проблемы: https://github.com/w23/xash3d-fwgs/blob/vulkan/ref/vk/data/valve/luchiki/maps/c1a1b.patch и это только 1 карта.

**Comment by UnrealKaraulov** [comment]
@0x4E69676874466F78 так уж и быть, сделал, правильно или нет не знаю)

Выделить в нужном порядке и нажать CTRL+C , в буфер скопируются id фейсов (которые в массиве faces)

**Comment by 0x4E69676874466F78** [comment]
@UnrealKaraulov приду домой обязательно проверю. Спасибо огромное!

**Comment by UnrealKaraulov** [comment]
@0x4E69676874466F78 забыл загрузить обнову) сейчас загрузил. 
Но если честно я так и не понял для чего это нужно было копировать их)))

Еще надо что?

**Comment by 0x4E69676874466F78** [comment]
@UnrealKaraulov не работает, может просто в файл писать выделенное или в какое-то дебаг окошко где можно выделять и копировать?
Кстати я открыл лог и там куча ошибок `Got OpenGL Error: 1282` это нормально? это ещё раньше видел но не придавал значение, так-то оно работает нормально.

Пока больше ничего особо не нужно.

> Но если честно я так и не понял для чего это нужно было копировать их)))

Для лучевой халфы https://github.com/w23/xash3d-fwgs чтобы патчить кривые трубы и не только, чтобы что надо было сглаженным, а что не надо прямым, т. к. автоматика срабатывает не везде хорошо.

**Comment by UnrealKaraulov** [comment]
@0x4E69676874466F78

Выбрать фейсы через CTRL, нажать CTRL+C , список помещается в буфер обмена.

Просто ничего не может мешать работе этого простого действия.


В следующем билде добавил в меню EDIT->COPY то же самое.

@0x4E69676874466F78  точно последняя версия?

**Comment by UnrealKaraulov** [comment]
@0x4E69676874466F78 

https://github.com/UnrealKaraulov/newbspguy/assets/88730285/faa14d92-92af-48da-a95f-9b914a193c45

1489 1481 1482 1490 1484 1485 11451 1472 11438 11435 11436 11451 11455 11451 1472 11449 1473

**Comment by 0x4E69676874466F78** [comment]
@UnrealKaraulov прошу прощения, я лоханулся с заменой файла, похоже если редактор запущен он блокирует exe файл и видимо архиватор на этом протупил и я вместе с ним. Всё работает, ещё раз огромное спасибо!
