### ISSUE TITLE
BSPGuy crashes when i change a setting on the entity like the sound of a door and such

### ISSUE THREAD

**Issue by PentiumMMX166** [UnrealKaraulov/newbspguy#73]
Whenever i attempt to change anything on a entity like the sound of the door opening or the button sound when pressed, the whole program just crashes out.

**Comment by Qwertyus3D** [comment]
Maybe it's a problem of FGD? Try to use another one. Could relay on FGD for J.A.C.K. maybe.

**Comment by UnrealKaraulov** [comment]
@PentiumMMX166 crashes with all maps ?

OS Windows/Linux ?

**Comment by UnrealKaraulov** [comment]
> Whenever i attempt to change anything on a entity like the sound of the door opening or the button sound when pressed, the whole program just crashes out.

@PentiumMMX166  In latest build this problem solved?

**Comment by Qwertyus3D** [comment]
Я думаю, надо закрыть эту жалобу. Топикстартер не отзывается, лично я не наблюдаю никаких вылетов, подобных заявленным.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я сам с этим не сталкивался, раньше в старых версиях косяки были при вводе текста рандомные краши и т.п, но это уже давно пофиксил, щас недавно упрощал работу keyvalue editor, много кода повырезал лишнего. Крашей по идее быть не должно. 

Вообще да если автор отзовется то откроем назад а пока закрываю.
