### ISSUE TITLE
Brush model import: lightmaps and texinfos broken

### ISSUE THREAD

**Issue by Outerbeast** [UnrealKaraulov/newbspguy#74]
When importing BSP model the lightmaps on the imported model are broken

**Comment by Qwertyus3D** [comment]
It may depend on version of BSP format you are choosing to export. Also maybe on exporting with WAD or embedded textures.

**Comment by Qwertyus3D** [comment]
I just tested this and yes, there is a problem with lightmaps. They're getting broken not only when you import a model, but also even if you duplicate a model. I also can't get ligthmap import feature to work, it doesn't import the earlier saved file.

The models are exported properly, they have lightmaps, as intended, so the problem is not there.

As I found, the last time lightmaps got properly fixed in this build: https://github.com/UnrealKaraulov/newbspguy/actions/runs/3786416995
But few builds later they got broken again.

Looks like significant problem fo re-fix.

**Comment by Qwertyus3D** [comment]
https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2022.12.27_09-14
This works properly for importing objects (but has other problems).

https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2022.12.27_09-37
And this is probably the last build which saves a map properly with properly restored lightmaps. Next build corrupts the BSP on saving, others do not restore lightmaps.

**Comment by UnrealKaraulov** [comment]
@Outerbeast  I think model exporting works properly. Lightmap, collision (hulls) and textures saved correctly in latest version. It can be used in AMXX plugins (instead of .MDL) or directly in map using unbreakable func_breakabl flag and gibs model as precache option.

But yes, when do import model to bsp structure, it cause something in code to undefined behavior. Need some time to found and fix it.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я проверил сейчас, сохранение модели, импорт/экспорт карты освещения работает без проблем, vis тоже целый, достаточно запустить VIS дебаггер в Debug окне, если VIS читается плохо, вместо отображения синих фейсов будет рандомно красным заполнятся некоторая часть или отдельные фейсы, но этого не происходит, и при экспорте BSP модели сейчас все корректно записывается. Карта освещения в Light Map Editor выглядит адекватно после экспорта.

Есть проблема только с импортом BSP модели, почему-то текстура рандомная берется из карты, хотя нужная добавляется в карту(вроде как), и полностью сломана карта освещений при импорте, набор байт. (Возможно при импорте думает что карта QUAKE, и пытается брать карту освещение из Quake Palette). Буду изучать проблему :)

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Есть дополнительный вопрос по лайтмапам. На данный момент, если двигаешь развёртку текстуры, то и лайтмапа двигается. Так что, исправляя маппинг текстуры, ломаешь освещение на объектах. Иногда заметно, иногда нет. Это баг? Или нет, но можно сделать так, чтобы лайтмапа не смещалась?

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D а вот этого даже не знаю надо будет как-то затестить что в игре покажет

**Comment by Qwertyus3D** [comment]
На данный момент лайтмапа как-то иначе смещается в игре, нежели в редакторе. После изменения развёртки текстуры её освещение в редакторе может никак не поменяться, а в игре будет чёрное пятно где-нибудь в углу. Или тень сместится.

**Comment by Qwertyus3D** [comment]
Основная проблема, думаю, в том, что лайтмапа смещается вместе с текстурой. Желательно, чтобы такой привязки не было, ну или редактор должен корректировать положение лайтмапы после редактирования текстуры. Напомню, что также есть проблема с тем, что после перемещения браш-моделей их освещение тоже ломается. Возможно, нужно для начала пофиксить текущий баг с освещением, а потом смотреть, что ещё потребуется изменить.

**Comment by UnrealKaraulov** [comment]
возможно косяк в рендере т.к я не трогал шейдеры отрисовки лайтмапов

**Comment by UnrealKaraulov** [comment]
> Основная проблема, думаю, в том, что лайтмапа смещается вместе с текстурой. Желательно, чтобы такой привязки не было, ну или редактор должен корректировать положение лайтмапы после редактирования текстуры. Напомню, что также есть проблема с тем, что после перемещения браш-моделей их освещение тоже ломается. Возможно, нужно для начала пофиксить текущий баг с освещением, а потом смотреть, что ещё потребуется изменить.

А это проблема видно с оригинал bspguy, lightmap походу не расстягиваются после изменений размеров текстур))))) А изменений не видно сразу т.к текстуру не обновляет инструмент FACE.

очень странно что нет изменений размера автоматического после изменения текстуры. буду фиксить.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Да, я когда переводил, то как раз и увидел подсказки по манипуляции лайтмапой, что мол, в одном из случаев лайтмапа ломается "иногда", а в другом - "всегда" :)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D реально карту освещения не меняет размер самостоятельно, ну это сделать не проблема думаю. Но если я сделаю по простому, то пару раз изменить туда-сюда, и лайтмапы с фейса вообще перестанут быть похожими на оригинал) но пока хоть так сделаю

**Comment by Qwertyus3D** [comment]
Не знаю, в тему ли будет упомянуть, но я как-то занимался экспортом-импортом моделей, и в одну из сохранённых моделей затесалась вшитая текстура. После импорта данной модели в другую карту эта текстура была вшита в неё, а позже я обнаружил, что она выдаёт ошибку переполнения буфера данных текстуры. Т. е. каким-то образом возникают косяки со вшитыми текстурами. Кстати, вообще, думаю, нецелесообразно вшивать в карту текстуры, которые и так уже имеются в WADах, загруженных вместе с картой. И неплохо было бы иметь опцию удаления из карты вшитых текстур, а также напротив - опцию вшивания в карту используемых текстур. Сейчас есть опция вшивания вадов целиком, что нецелесообразно, т. к. раздувает размер карты. По сути, вообще неправильная опция в текущем виде.

**Comment by Qwertyus3D** [comment]
Причём, что интересно, сейчас проверил, я примерно помню, какую модель в карту импортировал, т. к. специально обтягивал её этой текстурой, {blue. И вот получается, что в модели вшитой текстуры нет, а BSP-guy, получается, самовольно её вшил в карту при импорте, да ещё и с ошибкой :( Впрочем, ошибка могла случиться со старой версией программы, т. к. специально не получилось повторить эту проблему. Ну или какие-то условия необходимы, буду следить теперь.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D скорее всего переполнение буфера текстур косячит проверка, потому что на стандарт картах тоже выдает. 

Ну проверка чет типа такого
```
int texOffset = ((int*)textures)[i + 1];
if (texOffset >= 0)
{
    int texlen = getBspTextureSize(i);
    int dataOffset = (textureCount + 1) * sizeof(int);
        if (tex->nOffsets[0] > 0 && dataOffset + texOffset + texlen > bsp_header.lump[LUMP_TEXTURES].nLength)
        {
            print Текстур большой!;
        }
}
```

возможно что-то из переменных лишнее из-за чего проверка не работает

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я посмотрел сегодня как карта освещения сохраняется, в общем код очень странный и мне не понятный по этому я его решил упростить, или же усложнить хз) но мне будет спокойней после этого 🗡️

Например при перемещении модели, изменялись оффсеты карты освещения только для измененных в модели фейсов, но если после этой модели еще идут фейсы, то они как бы по идее не будут обновлены, по этому решил обновлять все вне зависимости от этого. 

Щас тестирую поможет ли это.

Еще там дичь ненужная какая-то передается в функцию изменения размеров лайтмапы. Просто вообще бессмысленная по этому я убираю все лишнее)

**Comment by UnrealKaraulov** [comment]
Не понимаю че там делает qrad_get_lightmap_flags, после изменения размера карта освещения съезжает из-за использования этих флагов, если ее просто изменять как изображение, то по идее съезжать ниче не должно.

**Comment by Qwertyus3D** [comment]
Ну, я могу только догадываться, что это какое-то наследие Кваки...

**Comment by Qwertyus3D** [comment]
С новым билдом наблюдаю, что те изменения лайтмапы, которые я видел только в игре после сдвига текстуры, теперь стали видны и в редакторе.

**Comment by KarKarKarKarkarkar** [comment]
> С новым билдом наблюдаю, что те изменения лайтмапы, которые я видел только в игре после сдвига текстуры, теперь стали видны и в редакторе.

Это хуже чем было?

**Comment by KarKarKarKarkarkar** [comment]
> Ну, я могу только догадываться, что это какое-то наследие Кваки...

Похоже какие-то оффсеты получает что бы лайтмапа не растягивалась вместе с объектом, а как бы повторялась.  Пока не особо понял фишку.

**Comment by KarKarKarKarkarkar** [comment]
После дублирования модели лайтмапа полностью убитая получается у нового объекта, пока тоже не понял че так. Казалось бы все ок должно быть завтра буду доделывать фикс.

**Comment by KarKarKarKarkarkar** [comment]
Импорт модели в native варианте сломано конкретно, тоже после фикса дублирования займусь, хотя может и само пофиксится ведь там одни и те же функции используются

**Comment by Qwertyus3D** [comment]
> > С новым билдом наблюдаю, что те изменения лайтмапы, которые я видел только в игре после сдвига текстуры, теперь стали видны и в редакторе.
> 
> Это хуже чем было?

Это лучше, теперь вид в редакторе совпадает с игрой. А раньше не совпадало.

**Comment by KarKarKarKarkarkar** [comment]
Я там тупо половину кода убрал, просто автор наверное чет курить начал, там двести раз одни и те же действия повторялись если не углубляться в детали. Теперь кода в разы меньше стало связанного с картой освещения, и разобраться легче в нем что бы пофиксить проблемы

**Comment by KarKarKarKarkarkar** [comment]
Еще бы сделать слияние моделей. А то толку от создания моделей если их нельзя объединить с worldspawn к примеру что бы не создавать каждый раз новую сущность для них

**Comment by Qwertyus3D** [comment]
Меня тоже посещала эта мысль. Ещё я себе сделал одну заготовку из браш-моделей и кинул их в один файл. А оказалось, что при импорте обратно в карту импортируется только та модель, которая считается ворлдспавном. Опять получается незадача.

**Comment by Qwertyus3D** [comment]
У меня стал крашиться редактор при попытке сдвига текстуры. Немножко пододвигаю - норм, двигаю дальше - вылет. Крашится обычная версия, дебаг не крашится. Вижу, что при смещении текстуры в дебаге периодически появляется "Загрузка". Видимо, обычная в этот момент вылетает.

И, до кучи, у меня такие же проблемы перед этим были при проверке/очистке карты с ошибками. Обычная версия крашилась, а дебаг - нет. Возможно, какая-то проблема с доступом к логу либо каким-то другим необходимым функциям?

И вот ещё что, у меня в логе постоянно вылезает сообщение об ошибке OpenGL 1282, почти после любых действий. и в процессе запуска тоже.

**Comment by UnrealKaraulov** [comment]
Вот ошибку 1282 не могу поймать, но связана с рендером моделей я так понимаю, если отключить рендер моделей то пропадает?

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D ну дубликат моделей почему-то начал дублировать leafs хотя не делал этого ранее, какие-то фиксы внес вроде как стало лучше. 

Когда жмешь duplicate модель, и очищаешь карту, карта сохранялась с ошибками "LEAF не соотвествует количеству". 

Создание моделей сломал, в последнем билде пофиксил. 

Поймать краш с передвижением текстуры пока не могу

**Comment by Qwertyus3D** [comment]
Да, без моделей нет ошибки.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D самое странное что я не могу увидеть эту ошибку OPENGL но о ней сообщают многие) Если бы увидел то давно уже пофиксил бы

**Comment by Qwertyus3D** [comment]
Перестало вылетать при смещении текстуры.

**Comment by UnrealKaraulov** [comment]
Сделал новую функцию для дублирования структур модели, то есть делает ее редактируемой но не создает новую копию структуры, вообще не знаю зачем новую создавало но теперь два варианта будет.

**Comment by Qwertyus3D** [comment]
Класс, как говорится, зачем плодить сущности?

**Comment by UnrealKaraulov** [comment]
> Класс, как говорится, зачем плодить сущности?

Оно создавало новую BSPModel в BSP файле каждый дубликат. Но цель не понятна совсем. По этому теперь есть упрощенный вариант который не делает этого.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D Починил импорт BSP моделей, карта освещения и текстуры, кажется все в порядке.

@Outerbeast In latest build this problem solved ?

**Comment by Outerbeast** [comment]
Working good so far, but there was sometimes a crash on loading the bsp file.  A bug I noticed was opening a big map where there was a lot of brush models, I couldn't scroll past model32, the list just cut off at the bottom of the screen without scrolling

**Comment by Qwertyus3D** [comment]
@Outerbeast Any sample map?

**Comment by KarKarKarKarkarkar** [comment]
@Outerbeast Yes this is imgui regression maybe... Thanks for report, i can try fix scrolling, but how to get bsp fort test crash?

**Comment by KarKarKarKarkarkar** [comment]
@Qwertyus3D в любой карте похоже прокрутка длинных списков меню перестала фурычить)

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov У меня вот лог не прокручивается после некоторых действий. То ли от выполнения ряда операций, то ли лимит у него на размер файла, ХЗ.

**Comment by KarKarKarKarkarkar** [comment]
список экспорта и лог должен был пофикшен по идее в последних билдах.

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Я смотрю, лог дописывается каждый раз при запуске, и пухнет неограниченно. Надо бы опцию на ограничение размера файла, либо вообще отключения дописывания.

**Comment by Outerbeast** [comment]
@Qwertyus3D @KarKarKarKarkarkar I think I might have done it wrong:  so I exported a brush func_tracktrain from cz_silo05.bsp in condition zero deleted scenes "with wad" and when I loaded it into anything it crashed on the load button.  But when I exported with the "with internal textures" and imported it seemed to work fine

**Comment by UnrealKaraulov** [comment]
@Outerbeast you can test in latest build no issues with import/export BSP models ? 


I do test with some maps, and think this issue fixed. If this issue not fixed, please tell me.
