### ISSUE TITLE
[Mod compatibility] Half-Life: Enriched maps are crashing

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#75]
https://www.moddb.com/mods/half-life-enriched/downloads

**Comment by UnrealKaraulov** [comment]
> https://www.moddb.com/mods/half-life-enriched/downloads

у меня все карты открываются без ошибки

**Comment by Qwertyus3D** [comment]
Сейчас тоже опробовал текущую версию, и тоже открываются без проблем. Ну, тогда закрываю.
