### ISSUE TITLE
About undo feature

### ISSUE THREAD

**Issue by UnkwUsr** [UnrealKaraulov/newbspguy#76]
In "Added new features in this fork:" section:

> * Added "undo/redo" for any manipulation. (Move ents/origin, etc)

and right after that:

> The editor is full of bugs, unstable, and **has no undo** button yet. ...

**Comment by Qwertyus3D** [comment]
Lol, you are the king of constructive criticism :D. I think, most bugs have their source in the predecessor, so I'd recommended to don't blame the fork, because it's much more better than original version.

**Comment by UnkwUsr** [comment]
No, sorry, I'm not trying to blame this project in any way. I just wanted to clarify this thing so future people will not be confused with it. I thought about just creating pull request with removing old sentence about "has no undo button", but I don't know what author personally think about state of the project (he knows much more then us :D), so would he wish to remove whole block or only 4 words about undo feature.

P.S. I also love this fork and respect the work of @UnrealKaraulov. This is why I created this tiny issue (little contribution, isn't it?). Sorry if this sounded rude :(

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D @UnkwUsr в последних обновлениях поработал над undo/redo, теперь должно работать стабильнее и работать для большего числа случаев.

**Comment by UnrealKaraulov** [comment]
Я думаю проблемы с Undo/Redo должны быть решены в последних версиях, если это не так то откройте issue заново.
