### ISSUE TITLE
VIS Prt File Export Doesn't Export all VIS Data

### ISSUE THREAD

**Issue by marigi64** [UnrealKaraulov/newbspguy#79]
Exporting any VIS prt from maps (tested with hl1 retail maps) exports a file only containing a single number (the leaf count).

![image](https://github.com/UnrealKaraulov/newbspguy/assets/53112738/5712c92f-5f2c-445e-b106-e448b90fc9cf)

**Comment by UnrealKaraulov** [comment]
@marigi64 yes, I can't do export .ptr file, goldsrc BSP has very hard to understand structure, so this feature not completed.

Now only RAD.exe data can be exported for rerun rad.exe compiler.
