### ISSUE TITLE
Проблемы при создании / удалении браш-моделей

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#8]
После обновления программы столкнулся со следующим. Имеется карта после оптимизации. На ней есть 2 trigger_autosave, но из-за оптимизации у них удалены все хуллы. Получается пустой неработающий триггер без физических границ. Пытаюсь заменить эти триггеры, создав новые браш-модели. Создаю func_wall, придаю ему нужную форму и размещаю на место первого триггера. Оба trigger_autosave при этом отсортированы в списке энтить с помощью Classname filter. Преобразовываю func_wall в trigger_autosave, после чего удаляю первый имевшийся старый триггер. Во-первых, новый созданный триггер не появляется сразу в списке (но это характерно и для оригинала BSPGuy). Во-вторых, после удаления первого старого триггера второму старому триггеру присваивается та же самая браш-модель, которую я создал заново, причём эта модель "улетает" в рандомное место, т. е. оказывается не там, где изначально располагался второй старый триггер. Если я пытаюсь менять форму браш-модели, которая присваивается старому триггеру, то тем самым одновременно меняется и форма исходной браш-модели. Прилагаю карту-пример.
[darkf24.zip](https://github.com/UnrealKaraulov/newbspguy/files/8132500/darkf24.zip)

**Comment by Qwertyus3D** [comment]
Собственно, как оказалось, присвоение новой браш-модели (ещё в виде func_wall) на второй trigger_autosave происходит сразу же. Т. е. до преобразования её в trigger_autosave и до удаления первого триггера. Фактически, она сразу же присваивается обоим trigger_autosave, если сначала создать её, а потом попытаться найти триггеры через список.

**Comment by UnrealKaraulov** [comment]
я не уверен тк не за компом но есть вроде бы функция регенерации клипнодов, она не помогает в этой ситуации? 

завтра гляну, хоть я и не особо понял что случилось)

**Comment by Qwertyus3D** [comment]
Ну, дело не в регенерации клипнодов. В оригинале программы я создаю на этой карте BSP-модель и делаю с ней, что нужно, всё ОК. А под форком происходит конкретный баг присвоения только что созданной BSP-модели на вот такие энтити с удалёнными хуллами. Она как бы дублируется автоматически сама по себе и привязывается к ним.

**Comment by Qwertyus3D** [comment]
Ну, и в плане регенерации клипнодов, я не нашёл такой функции.

И там ещё очень забавная вещь происходит, если под форком выбрать второй trigger_autosave на карте-примере (он находится в конце списка энтить, возможно, это как-то влияет) и нажать Duplicate BSP model. На словах объяснить сложно, нужно увидеть это. В оригинале такой проблемы нет.

**Comment by UnrealKaraulov** [comment]
спасибо за баг репорт постараюсь поправить, слишком много изменений, из-за чего автор не захотел их принимать в основную ветку bspguy, большая часть изменений свзяна с рендером BSP моделей и оптимизацией. Плюс была добавлена поддержка работы сразу с несколькими картами, но по просьбе автора bspguy отключал, но можно и назад включить.

в общем все это могло привести к небольшим проблемка ;)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D можно вкратце что надо сделать что бы получить эти баги?

а можно по пунктам?))) что бы я мог легко их повторить и не тратил время на чтение стены текста)

**Comment by Qwertyus3D** [comment]
Для начала:
- открываем карту darkf24.bsp.
- фильтруем список Entity Report по энтити trigger_autosave.
- щёлкаем на второй trigger_autosave, смотрим, как он выглядит и где расположен (пустая крестовина в одном из проходов).

Баг 1:
- жмём Create -> BSP model.
- снова щёлкаем на второй trigger_autosave, смотрим, как он теперь выглядит и где расположен. Видим, что trigger_autosave теперь "вылетел" за пределы карты и выглядит, как только что созданная BSP model.

Баг 2:
- жмём Edit -> Duplicate BSP model.
- происходит неведомая хрень, дополнительно рассмотреть которую можно, вылетев за пределы карты.

**Comment by Qwertyus3D** [comment]
Баг 2 нужно воспроизводить отдельно, а не после создания BSP model.

**Comment by UnrealKaraulov** [comment]
Я так понял что это ошибка в последней добавленной фишке, "CRC хак" , постораюсь исправить вчера был на работе, сегодня голосование было)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D сейчас загружается обнова, с ней проблема исправилась?

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Да, исправилось, спасибо. Хотя взлом CRC я отключил, т. к. у этой опции есть подводные камни. Т. к. если, к примеру, через другую программу (например, редактор энтпатча) внести изменения в карту, пересохранённую после взлома CRC, то потом эта карта вообще не открывается BSPGuy.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D еще там в этой карте 1 из моделей нигде не используется это пишет при загрузке, не знаю почему.

Ок тогда закрываю. Взлом CRC требует наличие лишних данных, или же запись значение куда-нибудь в неиспользуемые данные. По этому добавляю 1 модель времменную.
