### ISSUE TITLE
Language parse fatal error: ini file not found

### ISSUE THREAD

**Issue by Nord1cWarr1or** [UnrealKaraulov/newbspguy#80]
language.ini лежит рядом с bspguy, что не так?
[log.txt](https://github.com/UnrealKaraulov/newbspguy/files/13562230/log.txt)

**Comment by Qwertyus3D** [comment]
Может, не соответствует версия файла, или нет строчке в конфиге. Нужно взять bspguy.cfg и language.ini, идущие в комплекте с билдом. Ну или проверить, есть ли в текущем конфиге строчка:
language=EN

**Comment by UnrealKaraulov** [comment]
> Может, не соответствует версия файла, или нет строчке в конфиге. Нужно взять bspguy.cfg и language.ini, идущие в комплекте с билдом. Ну или проверить, есть ли в текущем конфиге строчка: language=EN

Да нет оно просто файл найти не может, щас сделаю меньше спама и больше инфы в дебаге

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or по умолчанию файл language.ini берет из папки с конфигом bspguy.cfg

В https://github.com/UnrealKaraulov/newbspguy/actions/runs/7103563650 будет писать путь к файлу полный. Скоро сборка завершится будет доступно для скачивания.

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or вот собралось, https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.05_16-20 что теперь пишет?

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or вот собралось, https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.05_16-20 что теперь пишет?

оказывается файл должен лежать `/home/user/.config/bspguy/language.ini` (на linux). В ридми на нашел такого, поэтому ланг файл клал рядои с программой

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or а вообще на linux нормально если конфиг будет рядом с программой? оно раньше и в Windows сунуло этот файл хрен пойми куда)))

Я бы убрал и сделал как на Windows просто в папку с программой если для linux систем это нормально будет считаться)

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or а вообще на linux нормально если конфиг будет рядом с программой? оно раньше и в Windows сунуло этот файл хрен пойми куда)))

Да не знаю, у меня "портабл" программ мало, в основном все установлены из репозиториев.
Думаю нормально, декомпилятор моделей от ксаша например рядом с собой хранит файл с активити для sequences activities.txt

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or тогда так и сделаю, как минимум можно будет для нескольких модов хранить копии bspguy тогда, и все будут знать где находится конфиг с lang файлом/файлами)

**Comment by UnrealKaraulov** [comment]
> Да не знаю, у меня "портабл" программ мало, в основном все установлены из репозиториев.
> Думаю нормально, декомпилятор моделей от ксаша например рядом с собой хранит файл с активити для sequences activities.txt

https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.05_17-13

Если ничего не сломал то эта версия должна брать конфиг и языковой файл из папки с программой. Возможно повлияет на косяк с управлением, вдруг конфиг устаревший хранился, не?)
