### ISSUE TITLE
не читается fgd файл (linux)

### ISSUE THREAD

**Issue by Nord1cWarr1or** [UnrealKaraulov/newbspguy#81]
![изображение](https://github.com/UnrealKaraulov/newbspguy/assets/47604048/33d901a3-7bac-43d7-91bb-fef31aef6263)

**Comment by KarKarKarKarkarkar** [comment]
@Nord1cWarr1or так на против него галка не стоит которая включает fgd

**Comment by KarKarKarKarkarkar** [comment]
Так же там можно вписывать относительный путь, например установить путь к игре, а там /valve/game.fgd достаточно будет. С путями к вад файлам так же можно сделать.

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or так на против него галка не стоит которая включает fgd
> 
> Возможно там нужно добавить упоминание того что перед нужным файлом необходимо активировать чекбокс

Я ее ставлю, нажимаю применить, она снимается обратно

**Comment by Qwertyus3D** [comment]
Это FGD для Джека, видимо. Они пока не совместимы. https://github.com/UnrealKaraulov/newbspguy/issues/77

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D нет проблема просто в поиске путей, если галка пропадает - путь не найден. У меня нет linux для тестов вот и косяки появляются там)))


@Nord1cWarr1or 
Я думаю решил эту проблему в последнем билде, получится проверить? 
https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.06_06-39

Еще должно теперь писать о путях которые не существуют в логи.

**Comment by Nord1cWarr1or** [comment]
```
Error[1]: Workdir bspguy_work/ not exits!
Error[2]: Workdir /home/maks/LGSM/serverfiles/cstrike/bspguy_work/ not exits!
Missing fgd home/maks/LGSM/serverfiles/cstrike/halflife-cs.fgd. Now this path disabled.
-------------START PATH TRACING-------------
Search paths [1] : [home/maks/LGSM/serverfiles/cstrike/halflife-cs.fgd]
Search paths [2] : [/home/maks/PortableApps/CS/bspguy/home/maks/LGSM/serverfiles/cstrike/halflife-cs.fgd]
Search paths [3] : [home/maks/LGSM/serverfiles/cstrike/halflife-cs.fgd]
Search paths [4] : [/home/maks/LGSM/serverfiles/cstrike/home/maks/LGSM/serverfiles/cstrike/halflife-cs.fgd]
Search paths [5] : [moddir/home/maks/LGSM/serverfiles/cstrike/halflife-cs.fgd]
Search paths [6] : [moddir_addon/home/maks/LGSM/serverfiles/cstrike/halflife-cs.fgd]
-------------END PATH TRACING-------------
```
файл у меня лежит по пути `/home/maks/LGSM/serverfiles/cstrike/halflife-cs.fgd`

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or а указан он тоже с начальным слэшем или без него ?

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or а сейчас?

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or а указан он тоже с начальным слэшем или без него ?

был указан без него. 
взял последний билд сейчас и указал со слешем - fgd подгрузился

**Comment by UnrealKaraulov** [comment]
@Nord1cWarr1or да предыдущая версия обрезала слэш когда не нужно, вероятно.
