### ISSUE TITLE
Latest build is completely broken

### ISSUE THREAD

**Issue by DenAkimov** [UnrealKaraulov/newbspguy#82]
1. When I start the program, Entity Report window is open and cannot be closed.
2. The camera automatically moves to the right
3. Moving the mouse makes "GO TO MENU" and "Transformation" menus open and close constantly. 
4. Clicking anything will select every single entity on the map and then remove it.

**Comment by UnrealKaraulov** [comment]
@GusTheForkliftOperator 

I can't reproduce this errors in latest build

OS Windows or Linux ?

**Comment by DenAkimov** [comment]
Linux

Happens with both native version and windows version running through wine (no camera movement and entity selection in linux version, but it is an old bug). Doesn't happen in builds from yesterday. 

EDIT:
Doesn't happen in a build from 5 hours ago. Errors started happening in the build with "Replace keyboard monitor from loop to callback" change.

**Comment by DenAkimov** [comment]
All the mentioned problems are fixed as of the newest build.
