### ISSUE TITLE
Issue with editing brush entities

### ISSUE THREAD

**Issue by DenAkimov** [UnrealKaraulov/newbspguy#83]
Problem appears when working with a newly created BSP model:

1. When changing the scale using "scale" axes (issue does not appear if X,Y,Z values are changed instead).
2. Using texture tool to change a texture on the BSP model

Once the action is done camera is automatically moved to the top of the map, position of many entities is changed and no new entities can be created anymore. 

The issue is not happening in builds prior to the update with 'Big big undo/redo upgrade!' change. 

Additional issue: in the newest build the axes for changing scale are invisible.

**Comment by UnrealKaraulov** [comment]
@GusTheForkliftOperator in latest build this issue fixed?

**Comment by DenAkimov** [comment]
Transforming brush entities and changing textures on them now works.

However, scale axes are still not visible. And now moving any entity using move axes is impossible - axes move but object always stays in its place.

**Comment by DenAkimov** [comment]
Entities can be moved until the new bsp model is created. When it is created, no entities can be moved anymore.

**Comment by DenAkimov** [comment]
Ok, I wasn't correct with that.  

Entities can be moved with axes in Move - Object mode. In Move - Origin mode the axes are present but entity cannot be moved. 

Now for brush entities - they can be moved in Move - Object mode but the axes are invisible (just like with Scale). If I switch to Move - Origin then axes appear but don't do anything just like with normal entities.

**Comment by UnrealKaraulov** [comment]
> Entities can be moved until the new bsp model is created. When it is created, no entities can be moved anymore.

@GusTheForkliftOperator you can give me example map with this issue?

**Comment by DenAkimov** [comment]
> @GusTheForkliftOperator you can give me example map with this issue?

@UnrealKaraulov Read my last message, I was incorrect with that assumption. The issue is just with invisible axes when trying to move or scale brush entities in Object mode.

**Comment by UnrealKaraulov** [comment]
@GusTheForkliftOperator it can be if you tried to move/scale INVALID SOLID

**Comment by DenAkimov** [comment]
> @GusTheForkliftOperator it can be if you tried to move/scale INVALID SOLID

@UnrealKaraulov I can scale and move entities normally, there is no issue with that. The axes are just invisible. I can still "pick" them with mouse and move/scale the object, but they are not visible.

**Comment by UnrealKaraulov** [comment]
@GusTheForkliftOperator no opengl errors in debug console ?

**Comment by DenAkimov** [comment]
> @GusTheForkliftOperator no opengl errors in debug console ?

@UnrealKaraulov Only error 1282 spammed but it always does that. 
Looks like the issue started appearing with "Remove useless code, add shader for models." build from 3 days ago. 
Also axes appear normally on all brush entities already present on the map. Only newly created mdl models have issues. 

And axes are not actually invisible. They actually render, but somewhere else... And they also get highlighted when you move the mouse where they actually should be. I included an image. 

![bug](https://github.com/UnrealKaraulov/newbspguy/assets/153075618/dd794c6f-37e3-48a0-8f90-4e1f62fc5feb)

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov  Думаю это то, о чём я писал, после перемещения энтити курсор улетает в другое место. https://github.com/UnrealKaraulov/newbspguy/issues/84#issuecomment-1846175296 И билд указал.
