### ISSUE TITLE
[Request] Worldspawn lock feature

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#84]
В общем, есть такая проблема, иногда пытаешься выделить группу энтить через CTRL, чтобы её подвигать, и случайно задеваешь worldspawn. И после этого при попытке двигать энтити начинает двигаться вся карта. Хотелось бы иметь возможность установки замка, чтобы ворлдспавн не двигался, пока замок не снят. А то прям сильно мешает при манипуляциях.

**Comment by Qwertyus3D** [comment]
По поводу бага с трансформацией есть такое наблюдение, что именно происходит. С билда https://github.com/UnrealKaraulov/newbspguy/actions/runs/7110630687 появился баг с крестовиной. Когда создаёшь объект или импортируешь его, и начинаешь двигать, то после первого перемещения крестовина смещается сторону от объекта. Примерно как если бы ты двигал на 100 юнитов, а она смещалась на 200. И вот так она улетает в сторону, при этом, наводя на объект мышь, видно, что эта смещённая крестовина реагирует на указатель мыши и подсвечивает оси, на которые бы должен указывать курсор мыши, если бы она была на месте. Т. е. можно продолжать двигать объект таким странным способом, но крестовина продолжает улетать дальше от объекта вслед за перемещениями. Баг происходит для новых объектов, как я понимаю.

**Comment by Qwertyus3D** [comment]
И ещё обратил внимание на такой косяк с трансформацией. Допустим, есть у нас какой-то объект, который уже сохранён на карте и который можно трансформировать, допустим trigger_once. И я хочу его перевести в другой тип модели, например func_wall. И вот если ему удалить ненужные поля, поменять класс, а потом начать трансформировать, то после трансформации ему возвращаются назад все изменённые свойства - класс, отредактированные поля и т. п. И так продолжается, пока не нажмёшь сохранить карту, только тогда прежние значения не восстанавливаются.

**Comment by Qwertyus3D** [comment]
Так, ну всё, про что тут писал, вроде бы решено.

**Comment by Qwertyus3D** [comment]
Но вот на это внимание обрати: https://github.com/UnrealKaraulov/newbspguy/issues/58#issuecomment-1849092277

**Comment by KarKarKarKarkarkar** [comment]
@Qwertyus3D я вроде бы не пробовал ещё решить это, может случайно)))

**Comment by Qwertyus3D** [comment]
По этому вопросу вроде всё.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D я не знаю вроде бы не исправлял, но если исправилось само по себе то хорошо)

**Comment by Qwertyus3D** [comment]
Ну, перестал добавляться ворлдспавн к выделяемым энтитям, в принципе, этого достаточно, если не углубляться.
