### ISSUE TITLE
Broken controls since "Tried to fix ANGLES in GOTO" build

### ISSUE THREAD

**Issue by DenAkimov** [UnrealKaraulov/newbspguy#85]
1. Cannot select anything with the mouse. 
2. Movement doesn't follow camera direction
3. A and D buttons move the camera down and up respectively instead of left and right.

**Comment by UnrealKaraulov** [comment]
@GusTheForkliftOperator, yes WASD can't works if camera "roll" value changed. I just lock ROLL camera value now. 

Fixed in latest build https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.10_12-13 ?

**Comment by DenAkimov** [comment]
@UnrealKaraulov Yes, controls work normally now. Axes on new brush entities are fixed too.
