### ISSUE TITLE
Предложения по выделению объектов

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#88]
Есть ли возможность научить редактор выделять объекты группами в 3D, подобно выделению в списках?

Сейчас есть сложность, например, с тем, чтобы выделить несколько объектов, когда они находятся примерно в одной точке. Иногда бывает, что они могут совпадать по размерам, тогда без Hide никак не доберёшься до объектов, скрытых друг за другом.

В идеале бы иметь возможность, удерживая, к примеру, Shift, растянуть мышью рамку в окне обзора, и чтобы все объекты, которые находятся в поле, окружённом рамкой, выделились. При этом, если за выделенными объектами находится часть ворлдспавна, то чтобы она отсекала выделение тех объектов, которые потенциально расположены за ней. Ну т. е., чтобы учитывался факт PVS для выделения рамкой.

Если можно такое сделать, было бы идеально.

**Comment by UnrealKaraulov** [comment]
вряд ли я такое смогу сделать :(

**Comment by Qwertyus3D** [comment]
По поводу текущих проблем выделения. Если выделено несколько объектов, то контекстное меню у них будет правильно отображаться только при его вызове на первом выделенном объекте (Вырезать / Копировать / Удалить / Скрыть // Свойства сущности). На остальных появится только неактивное Вставить / Вставить на место.

Кроме того, пункты меню Правка вообще толком не работают на чём угодно. Вырезать / Копировать / Удалить активны только для ворлдспавна, для остального доступно только Вставить / Вставить на место / Отобразить всё, остальное неактивно и работает только через контекстные меню.

Функция Grab вообще непонятные штуки творит (и не переведён этот пункт). Alt+G сдвигает объекты в рандомное место, какая-то ерунда бесполезная. Либо на выделенном объекте, когда он уже сместился, куда ему хотелось, переключает видимость крестовины перемещения. В Справке указано, что при нажатии G (наверное, всё же Alt+G?) выделенный объект должен "отпускаться", но и это не работает.

**Comment by Qwertyus3D** [comment]
> вряд ли я такое смогу сделать :(

Хорошо, а, допустим, можно ли сделать такое (удерживая Shift / Ctrl / Alt или просто сделав двойной клик на объекте) - чтобы выделялся не один объект, а все те объекты, которые находятся "внутри" него? Как раз для того, чтобы решить вопрос с выделением наложенных друг на друга объектов?

Альтернативно, если и с этим проблема, то такая функция: зажимаем клавиши Ctrl+Alt (Ctrl+Shift?), кликаем на объекте. Это скрывает указанный объект, но при этом добавляет его к группе выделения. Так что можно дальше выбирать объекты, скрытые за ним (и тоже добавлять их к выделению). Можно сделать, чтобы скрытие включённых в группу выделения объектов действовало, пока удерживается зажатой Alt (Shift), а когда отпускаешь, то чтобы всё выделенное становилось видимым. Ну либо какая-то подобная механика, если в голову приходит что-то лучше.

**Comment by UnrealKaraulov** [comment]
> Функция Grab вообще непонятные штуки творит (и не переведён этот пункт). Alt+G сдвигает объекты в рандомное место, какая-то ерунда бесполезная. Либо на выделенном объекте, когда он уже сместился, куда ему хотелось, переключает видимость крестовины перемещения. В Справке указано, что при нажатии G (наверное, всё же Alt+G?) выделенный объект должен "отпускаться", но и это не работает.

Жмешь ALT+G и объект прилипает к камере, двигается вместе с камерой, повторное нажатие ALT+G отпускает объект.

**Comment by Qwertyus3D** [comment]
> Жмешь ALT+G и объект прилипает к камере, двигается вместе с камерой, повторное нажатие ALT+G отпускает объект.

Это какой-то крайне специфический способ перемещения, разве что для быстрого переноса объектов на значительные расстояния. И подсказка какая-то неполноценная о нём, да ещё с неточностью. Ну, ладно хоть работает, а не просто место занимает :D

**Comment by UnrealKaraulov** [comment]
Я не буду делать это слишком сложное выделение для меня. Pull request'ы не запрещал если кто-то захотит я не против буду.
