### ISSUE TITLE
Брашевые модели не передвигаются без Duplicate BSP model

### ISSUE THREAD

**Issue by Qwertyus3D** [UnrealKaraulov/newbspguy#9]
Задумано так, или баг, но в оригинале BSPGuy при выделении брашевых моделей сразу же появляется крестовина для перемещения объекта, и его можно двигать. В форке до тех пор, пока не используешь функцию "Duplicate BSP model", никакую брашевую модель переместить нельзя, даже если она не привязана ни к какому другому объекту на карте (крестовина перемещения просто не появляется). Если перед этим была выбрана энтить, которую двигать можно, и на ней появилась крестовина, то при выборе брашевой модели через список энтити (а не непосредственным выделением объекта во вьюпорте) крестовина как бы "перекидывается" и на браш-модель, тогда её можно двигать.

**Comment by UnrealKaraulov** [comment]
в оригинале нельзя было двигать не знаю почему, но помню что не двигались, странно)

**Comment by UnrealKaraulov** [comment]
поправлю если попаду за комп)

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D двигать нельзя даже в оригинале потому что некоторые браш сущности не поддерживают такое, делать исключение только для некоторых - костыль который может легко сломаться и привести к необратимым последствиям.

В последнем обновлении немного поправил отображение инструмента перемещения. (ошибка в оригинале)

**Comment by Qwertyus3D** [comment]
@UnrealKaraulov Я на деле тестировал текущую версию оригинала, двигать там можно абсолютно любую браш-модель. При выделении сразу же появляется крестовина, можно двигать, и никаких дополнительных действий делать не нужно.

**Comment by UnrealKaraulov** [comment]
@Qwertyus3D но в коде прямо прописан запрет на перемещение без создания дубликата, в редакторе модель переместится а в игре нет, например func_wall точно, т.к там оригин обнуляется
