### ISSUE TITLE
lightmap render issue in latest builds

### ISSUE THREAD

**Issue by KarKarKarKarkarkar** [UnrealKaraulov/newbspguy#91]
Black color instead of lightmap.

**Comment by Qwertyus3D** [comment]
Latest build that doesn't have the problem: https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.21_08-16

Or disable lightmaps' rendering to view a map in fullbright mode.

**Comment by Nin10doGMod** [comment]
> Latest build that doesn't have the problem: https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2023.12.21_08-16
> 
> Or disable lightmaps' rendering to view a map in fullbright mode.

This isn't working! All the screen are pitch black!

**Comment by Qwertyus3D** [comment]
@Nin10doGMod 
You didn't understand what I'm talking about (go to the Settings and remove "Lightmaps" checkbox) or you didn't revert your bspguy.exe to mentioned version.

**Comment by UnrealKaraulov** [comment]
@Nin10doGMod @KarKarKarKarkarkar @Qwertyus3D fixed in https://github.com/UnrealKaraulov/newbspguy/commit/a469c5355448590a12e43f060c06ae5a433f6842 path.
