### ISSUE TITLE
[Bug] При выборе нескольких энтитей в списке, зажатии CTRL и нажатии ПКМ - из выбора пропадает энтити на которой это задействовалось

### ISSUE THREAD

**Issue by SmileyAG** [UnrealKaraulov/newbspguy#93]
Сам баг:

https://github.com/UnrealKaraulov/newbspguy/assets/58108407/e67ce7a7-7ee5-4efe-88b8-4e5373df5623

Но кстати, если всё же нажать в списке на этот энтити и уже после сделать ПКМ - то тогда все выделяются как и должно это по факту быть:

https://github.com/UnrealKaraulov/newbspguy/assets/58108407/7153c1ba-9142-41f8-b034-7f9e5380cc25

**Comment by UnrealKaraulov** [comment]
Это видно один и тот же баг с https://github.com/UnrealKaraulov/newbspguy/issues/94
