### ISSUE TITLE
[Enhancement] Сохранять выделенные энтити в списке без зажатия SHIFT / CTRL

### ISSUE THREAD

**Issue by SmileyAG** [UnrealKaraulov/newbspguy#94]
https://github.com/UnrealKaraulov/newbspguy/assets/58108407/bc583a48-00ff-4500-9aea-3c2c9ff6464a

Как можно видеть, то можно выбрать какие-то энтити и после этого всё же отпустить клавишу, но когда доходит очередь до нажатия ПКМ для выбора опций и при этом мы не держим SHIFT или CTRL клавишу (в зависимости от того хотим мы выделить ряд энтитей идущих по списку или же выборочно), так всё это сразу же ресетается.

**Comment by UnrealKaraulov** [comment]
@SmileyAG да спасибо думаю логику можно улучшить

**Comment by UnrealKaraulov** [comment]
Должно быть исправлено в https://github.com/UnrealKaraulov/newbspguy/commit/1f6c7e2ab6950c87d8551e8e9347c3749f3449e3
