### ISSUE TITLE
[Enhancement] PVS editing

### ISSUE THREAD

**Issue by mfaizsyahmi** [UnrealKaraulov/newbspguy#95]
### Proposed mechanisms

1. Marking Leaf B visible from leaf A
    - While the camera is positioned inside leaf A, select a face on leaf B, then a button/menu/command in Face Properties dialog or elsewhere to mark leaf B as visible from current leaf
2. Marking leaf A visible from every other leaf
    - While the camera is positioned inside leaf A, a menu/button/command to mark leaf A visible from all other leafs
    - (analog to zhlt's `info_overview_point` with reverse flag on)
3. Marking every leaf visible from leaf A
    - While the camera is positioned inside leaf A, a menu/button/command to mark all leafs visible
    - (analog to zhlt's `info_overview_point` normal mode)

### Impractical but fun implementation idea
4. Export/Import PVS matrix as 1-bit bitmap

**Comment by KarKarKarKarkarkar** [comment]
Yes this is can be easy added, now added 'add/remove faces from leaves', in next update can be added 1-3, but 4... Your really think 1bit matrix can be appended to VIS?)))

**Comment by KarKarKarKarkarkar** [comment]
@mfaizsyahmi you can test 1-3 functions in latest build (pvs edit button in toolbar)

**Comment by UnrealKaraulov** [comment]
@mfaizsyahmi completed in latest build.

Added sample map https://github.com/UnrealKaraulov/newbspguy/tree/newbspguy_master/demo
