### ISSUE TITLE
[Enhancement] Replace Bsp Model Without changing its Model Number

### ISSUE THREAD

**Issue by marigi64** [UnrealKaraulov/newbspguy#96]
This is more of a question but is it possible to entirely replace a BSP model with another without changing its model number? Alternatively, having the ability to change the model number of a given BSP model in a map?

I ask this as I want to replace a model with an imported one but also keep the number of BSP models for the map consistent.

**Comment by KarKarKarKarkarkar** [comment]
In debug widget "swap model" option?

**Comment by marigi64** [comment]
I've tried that but all that does is swap what model for entities with the corresponding model number. It doesn't change the number of the bsp model.

**Comment by UnrealKaraulov** [comment]
@marigi64 fixed in latest build ? (this is language.ini file IMGUI issue, ##mdl1 hash used for two models)

**Comment by marigi64** [comment]
@UnrealKaraulov Yup! Working now! Thank you!
