### ISSUE TITLE
PVS Editor Highest Number Leaf Not Being Counted

### ISSUE THREAD

**Issue by marigi64** [UnrealKaraulov/newbspguy#97]
There is a problem with how leaf numbers are counted or listed in the PVS Editor. I doesn't count the highest number leaf in the map.

For example, editing c2a2b1.bsp, leaf "1489" (the highest number in the map) isn't on the list for either visible or invisible leafs (nor the faces it uses get highlighted red or blue), this results in it being discarded when making changes to other leafs that can see it. 

![image](https://github.com/UnrealKaraulov/newbspguy/assets/53112738/fc6ae167-f630-4962-8350-32d3701e5bd1)
![image](https://github.com/UnrealKaraulov/newbspguy/assets/53112738/be405830-6c68-4f3c-ba73-72fa950f6a9d)

**Comment by UnrealKaraulov** [comment]
@marigi64 thanks, fixed in latest build
