### ISSUE TITLE
Error when launching from terminal

### ISSUE THREAD

**Issue by Outerbeast** [UnrealKaraulov/newbspguy#98]
When launching the application from cmd, the following errors are printed:

```BSPGUY:NewBSPGuy v4.10
std::filesystem fatal error.
what():  canonical: unknown error: "bspguy"
path1(): "bspguy"
path2(): ""
code().value():    2
code().message():  unknown error
code().category(): system
```
I'm unable to use commands because of this

**Comment by UnrealKaraulov** [comment]
Fixed in latest build ? 
https://github.com/UnrealKaraulov/newbspguy/releases/tag/NightBuild_2024.01.19_09-53

**Comment by Outerbeast** [comment]
That error no longer happens, but when trying to use the `merge` command to combine bsps, the application just crashes. Nothing is printed in terminal.
The other commands do not work, for instance `info` does nothing

**Comment by KarKarKarKarkarkar** [comment]
And GUI not showing?

**Comment by Outerbeast** [comment]
GUI still works just fine

**Comment by UnrealKaraulov** [comment]
@Outerbeast fixed in latest build https://github.com/UnrealKaraulov/newbspguy/commit/9ad3f7454d9f8f72d46943e63b224708b17012fd ?

**Comment by Outerbeast** [comment]
Thanks, this is fixed. I can merge maps now.

One remaining issue is that there is no console output during/after the merge process, for instance the new merged bsp stats won't be displayed https://github.com/wootguy/bspguy/wiki/Merging-workflow#first-step

**Comment by UnrealKaraulov** [comment]
@Outerbeast very strange because I can see this info 

![image](https://github.com/UnrealKaraulov/newbspguy/assets/88730285/4d473c9a-0aa0-4d26-b479-db9bf1775bb5)
